### ISSUE TITLE
Incorrect timestamp returned by LinuxSerialDevice

### ISSUE THREAD

**Issue by a2hill** [dji-sdk/Onboard-SDK#101]
In the function [LinuxSerialDevice.getTimeStamp()](https://github.com/dji-sdk/Onboard-SDK/blob/3.2/platform/linux/src/LinuxSerialDevice.cpp#L70-L72) the linux system function [time](http://man7.org/linux/man-pages/man2/time.2.html) is used to return a timestamp. The return type is `time_ms` implying that the value is a timestamp in milliseconds. However per the documentation for that function (linked above), the timestamp returned is in full seconds, not ms. This causes issues in SDK functions that rely on the `getTimeStamp` function to evaluate the timeout duration of various commands.

**Comment by rohitsantdji** [comment]
Good catch, thanks! I'll update this when a fix is out.
