### ISSUE TITLE
DJI Gimbal Z15-A7 not working with Onboard-SDK

### ISSUE THREAD

**Issue by NielsPaul** [dji-sdk/Onboard-SDK#103]
I am currently facing the problem that the Z15-A7 Gimbal, combined with the A3 flight controller, is not working with the OSDK (Version 3.2).
The computer running my own program is able to communicate with the drone. It also is able to use SDK functions like manipulating the flight status or receiving the broadcast data. 
However, all functions related to the gimbal control return a 'SerialWrite returns 26 Success', but nothing happens. Also, all gimbaldata in the broadcast data is '0'.
The functions used are taken from the Linux examples, i.e., GimbalSpeedControlSample and GimbalAngelControlSample. 
On the Matrice M100 with a X3 Gimbal being at my disposal, too, the whole software works completly fine. Hence i must assume, that the sdk is not able to communicate with the Z15 gimbal, respectively the Z15 Gimbal is not functioning with the OSDK.
If the latter is the case, are there any other possibilities to control the gimbal, e.g., by position or rate?

**Comment by lanyusea** [comment]
Z15 is not supported.


Only X3/X5/X5s/XT/RoninMX are supported. The Z series are not supported. (well, but sorry I cannot say the reason)
