### ISSUE TITLE
STM32 Camera Shot functionality not working

### ISSUE THREAD

**Issue by eyesonlyhack** [dji-sdk/Onboard-SDK#106]
Hi, I am trying to trigger a camera using the sdk but the camera functionality is not responsive. I cannot even get the gimbal values for the camera in the API. I am using the ZenMuse Z15 with Sony Alpha 7 R camera on the M600. I am using the Onboard-SDK for the STM32 example (Versions 3.1 and 3.2). Camera triggers fine manually and through the mobile app.

I am calling the camera shot functionality as follows:
camera->setCamera(Camera::CAMERA_CODE::CODE_CAMERA_SHOT);

**Comment by amenonDJI** [comment]
@eyesonlyhack Z15 is not supported with the Onboard SDK

Only X3/X5/X5s/XT/RoninMX are supported. The Z series are not supported.
