### ISSUE TITLE
 Data frames are not received in order

### ISSUE THREAD

**Issue by alexandrubichis** [dji-sdk/Onboard-SDK#109]
Hello,

I'm working with Mobile Onboard SDK using Data Transparent Transmission, to send a data frames from Mobile Device to an Onboard Embedded System through A3 with Lb2. My issue is that my data frames (6 bytes the size of data frame) are not received in order (I've created a sequence number in my data frame that is incremented on mobile device when sending the message). I've checked the protocol frame, and the frame sequence number from header it is received correctly. Can you please check if this issue is on Mobile SDK or on Onboard SDK.

A3 firmware version is 1.7.0.0
OSDK version 3.1.9
Mobile SDK version  3.5

Thank you

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
