### ISSUE TITLE
Cannot read RC signal strength with OES

### ISSUE THREAD

**Issue by newtoniant** [dji-sdk/Onboard-SDK#113]
There doesn't seem to be a way to read the signal strength from the remote control with the onboard sdk.

**Comment by amenonDJI** [comment]
@newtoniant Could you tell us your use case of how you plan to use the signal strength?

**Comment by newtoniant** [comment]
I want to monitor the signal in preparation for signal loss. If signal is getting low, store waypoint data to follow backwards when signal lost.

**Comment by newtoniant** [comment]
@amenonDJI 
If I could control the the M100 when RC signal is lost with OSDK, I wouldn't need to monitor RC signal strength. I could handle all other logic without getting a value for RC signal strength. If you have comments on that, please let us know.

**Comment by amenonDJI** [comment]
@newtoniant The only way to control the aircraft without RC signal is using Virtual RC. You could register the GPS value during Take Off and write a controller to get the aircraft back to homepoint. Just a fair warning about Virtual RC, this feature is deprecated on the A3/N3 Flight controllers and will not be available on any aircraft other than the M100. In the future, you will be able control the aircraft, run missions from the OSDK using our A3/N3 flight controllers. Hope this helps.

**Comment by newtoniant** [comment]
@amenonDJI 
Just to clarify, for flight controllers/UAVs other than M100, the OSDK can maintain control after RC signal loss.  

Just the M100 needs VirtualRC as a workaround to maintain control?

**Comment by amenonDJI** [comment]
@newtoniant The Virtual RC feature has been deprecated, instead, full control of all the features from the OES will be available in future versions of the A3/N3 flight controller series.  From OSDK documentation: " Virtual RC has been deprecated and is unavailable for A3 FW > 1.6.0.0 and for N3."
