### ISSUE TITLE
Build fails on Linux

### ISSUE THREAD

**Issue by mtzm** [dji-sdk/Onboard-SDK#117]
I just cloned the repo and tried to build it.
It failed with:
`Onboard-SDK/osdk-wrapper/src/LinuxCamera.cpp:173:52: error: ‘fabs’ was not declared in this scope`

Adding `#include <math.h>` in Onboard-SDK/osdk-wrapper/src/LinuxCamera.cpp solves the issue for me

**Comment by brentalanmiller** [comment]
I had the same problem too. Created PR #128

**Comment by rohitsantdji** [comment]
Merged PR #128 .
