### ISSUE TITLE
VERT_VEL stopped working in latest firmware

### ISSUE THREAD

**Issue by maciekd** [dji-sdk/Onboard-SDK#119]
Hi,

Im running an A3 using Ubuntu. A3 is on the latest firmware (1.7.x)

Before the latest firmware upgrade I could control the craft using VERT_VEL control mode. Now this does not seem to work - it's as if the flight control commands are ignored completely. VERT_POS works fine.

Is this by design or could it be a bug?

**Comment by maciekd** [comment]
Throttle control does not seem to work either. Throttle control is a requirement for our application. :/

**Comment by maciekd** [comment]
Turning off the safety max distance in DJI Assistant solved the problem.

**Comment by maciekd** [comment]
Sorry, turns out that did not help at all. Still at a loss here.

**Comment by rohitsantdji** [comment]
This turned out to be a bug on the OSDK. We just pushed a hotfix, could you please try it out?

**Comment by maciekd** [comment]
It works! Thanks for the help.
