### ISSUE TITLE
RTK latitude and longitude output issues - loss of precision due to double

### ISSUE THREAD

**Issue by SkyJerms** [dji-sdk/Onboard-SDK#121]
Hello DJI Developers & Community,

I've integrated the D-RTK module with an M600 and can successfully read and record data onto a Linux-based computer. I purchased the ~$5000 D-RTK module because of it's outstanding sensor specs (2-3cm accuracy), however the OSDK Documentation Appendix says that it saves as a double (as opposed to int32 for regular GPS, which oddly enough, is less accurate) when used with the A3 flight controller! Double only gives four decimal places on the latitude and longitude coordinates, which is +/-10m or so in real life. 

How can I change the output so it records into an int32? Alternatively, are the RTK outputs actually stored in the regular GPS variables?

Jeremy

**Comment by Ray-Airdog** [comment]
Double has **15** decimal places. I suppose it is a formatting issue on your side that rounds it down to 4 when converting to a string (printing to stdout, log etc.)

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
