### ISSUE TITLE
Odroid XU4 +ROS + Matrice 100_Error 449

### ISSUE THREAD

**Issue by AWKIONG** [dji-sdk/Onboard-SDK#122]
Hey guys, need the community advice on this matter. Been cracking my skull over this.

Trying to link my Odroid XU4 (Ubuntu 14.04 + Onboard SDK ROS 3.2) with my Matrice 100. Received the following message:
![inkedcapture1_li](https://cloud.githubusercontent.com/assets/28199120/25572526/c75c0ade-2df0-11e7-84db-f75f05448623.jpg)

I have read through issues #77, #104 and config my setup according:
- Latest firmware for DJI Go app, Remote control,  Matrice 100, Onboard-SDJ-ROS 3.2

- All connections are made; 
    DJI GO app connected to Remote Controller
    Matrice 100 connected to Odroid GPIO with careful emphasis on Tx and Rx matching
    Matrice 100 connected to Laptop via USB
    Running DJI Assistant 2, with API checked
    Running SSH connection to my Odroid (with internet connection)

- Configured the sdk_manifold.launch file:
    Updated App ID and Key
    Serial set to `ttySAC0`
    Baud rate unchanged at 230400

- Toggled the F mode around, kept it and ran it in F mode

My initial thought is that I got the serial_name wrong. So I experimented with all the available ttySAC* available from `dmseg | grep tty*`

Any recommendations or suggestions?

**Comment by rohitsantdji** [comment]
Did you add your user to the `dialout` group using `sudo usermod -a -G dialout $USER`?

**Comment by AWKIONG** [comment]
@rohitsantdji, I have checked the groups rights.
![capture2](https://cloud.githubusercontent.com/assets/28199120/25606097/86116144-2ec4-11e7-9da8-be3e7d8be583.JPG)

Some more photos for troubleshooting. 
![capture3](https://cloud.githubusercontent.com/assets/28199120/25606106/94376192-2ec4-11e7-9c35-0eb898f3c016.JPG)

To verify the wiring of Odroid GPIO
![dsc_1436](https://cloud.githubusercontent.com/assets/28199120/25606109/95f2b1e4-2ec4-11e7-8289-66849f6a0ad2.JPG)

I noticed for the new firmware of the Remote Controller, we do not have the option to turn off the IOC. The settings only have the multiple flight modes. I have also tried toggling the F mode around, and leaving it on F mode before `roslaunch`

=|

**Comment by chuong98** [comment]
The odroid xu4 GPIO use 1.8V level, while most of the other external uses 3.3V. So you need a level shift converter to connect them.

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
