### ISSUE TITLE
How to interpret RTKData structure

### ISSUE THREAD

**Issue by alexandrubichis** [dji-sdk/Onboard-SDK#124]
Please tell us how to use the yaw, posFlag, yawFlag from RTKData structure. Specifically what measure unit does yaw have and what resolution (degrees, tenth or hundredth). 

typedef struct RTKData
{
  uint32_t date;
  uint32_t time;
  float64_t longitude;
  float64_t latitude;
  //! @warning the 'Hmsl' field will be renamed in a future release.
  float32_t Hmsl;

  float32_t velocityNorth;
  float32_t velocityEast;
  //! @warning the 'velocityGround' field will be renamed to velocityDown in the next release.
  float32_t velocityGround;
  
  int16_t yaw;
  uint8_t posFlag;
  uint8_t yawFlag;

} RTKData;

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
