### ISSUE TITLE
OnBoard SDK can't connect to Matrice 100

### ISSUE THREAD

**Issue by lfway** [dji-sdk/Onboard-SDK#125]
Hi! I have built PureQT example for Raspberry Pi 3.
I enabled API control in DJI Assistant2 for Matrice.
I connectted M100 to RPi using UART-CAN2 cable.
I registered as DJI developer and I getted app key and app id.
I copied getted app key and app id to PureQT.
I opened ttyAMA0 port
BUT
When I click "Version" program is doing nothing.
When I click "Activate" I see "ERROR activate,line 451: Please call getDroneVersion first."
![1](https://cloud.githubusercontent.com/assets/817536/25936662/61793568-3631-11e7-9bf2-c8eccb7707b4.png)
I tryed with different baud rates.
Help me please!

**Comment by kkoppul2** [comment]
I am having the same issue with getDroneVersion either not being called or not returning anything to the version data struct. I am using the Manifold OES, but I believe that this issue may have common cause for both of us. Have you had any luck fixing this issue?

**Comment by adamwathieu** [comment]
I have a similar issue, any help would be great:
https://github.com/dji-sdk/Onboard-SDK/issues/143

**Comment by OmkarSavant** [comment]
+1 Also having this issue

**Comment by justwillim** [comment]
hi all, If you are using ubuntu,  try to use this sample under sudo, make sure you have already added usergroup dialout.

**Comment by justwillim** [comment]
if all these movement you already tried, please ensure your hardware connection is right, use cat /dev/YOURTTY_DEVICE to see if the FC is sending out datas.

**Comment by Jai-GAY** [comment]
It seems like many [experienced this issue](https://github.com/dji-sdk/Onboard-SDK/issues/374#issuecomment-421901219).

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
