### ISSUE TITLE
troubles using puck lidar sensor-integration

### ISSUE THREAD

**Issue by natelannan-osu** [dji-sdk/Onboard-SDK#126]
I would like to integrate Puck Lidar logging capabilities with a Tegra TX-1 running ubuntu 14.04.  Is this possible?  I am having difficulties compiling the example located in ~/Onboard-SDK/sensor-integration/velodyne_vlp16puck_lite_API_example.  I followed the instructions to the best of my abilities here:

http://developer.dji.com/onboard ... elodyne/readme.html

any pointers for how to compile for logging would be great.
thanks

**Comment by natelannan-osu** [comment]
while attempting to run cmake on vlp16lidar-driver, cmake is not properly finding libpcap, though apt-get shows that it is the newest version:

--  Pcap cannot be found. Installing libpcap-dev package
Reading package lists...
Building dependency tree...
Reading state information...
libpcap-dev is already the newest version.
The following packages were automatically installed and are no longer required:
  cmake-data libjsoncpp0
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
CMake Error at CMakeLists.txt:21 (find_package):
  By not providing "FindPCAP.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "PCAP", but
  CMake did not find one.

  Could not find a package configuration file provided by "PCAP" with any of
  the following names:

    PCAPConfig.cmake
    pcap-config.cmake

  Add the installation prefix of "PCAP" to CMAKE_PREFIX_PATH or set
  "PCAP_DIR" to a directory containing one of the above files.  If "PCAP"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
