### ISSUE TITLE
GPS coordinate offset

### ISSUE THREAD

**Issue by lbdhr** [dji-sdk/Onboard-SDK#127]
The GPS coordinate read from the SDK has a large offset (about 7 km) compared with the original point.
How should I solve this problem?
Thanks a lot.

**Comment by justwillim** [comment]
hello lbdhr,
China Mainland and other region are using different Map coordinates, you could enable or disable it in DJI GO app.

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
