### ISSUE TITLE
Data Transparent Transmission

### ISSUE THREAD

**Issue by Valkaryne** [dji-sdk/Onboard-SDK#129]
How much data I can send from mobile level to onboard level through "Data Transparent Transmission"? I tried to send a sequence of bytes from mobile, but onboard received only the first. It's ok or not? Can I send 10 or at least 5 bytes?

**Comment by lovesmall** [comment]
According to DJI [DTT user guide](http://download.dji-innovations.com/downloads/dev/OnboardSDK/Data_Transparent_Transport_Introduction_v1.0.0_en.pdf), both way data is no more than 100 bytes.

**Comment by rohitsantdji** [comment]
Closing since there's been no follow up from the OP. If questions still exist, please re-open the issue. Thanks!
