### ISSUE TITLE
readUserConfig only allows for 20 character device names

### ISSUE THREAD

**Issue by mk2017** [dji-sdk/Onboard-SDK#131]
Using the UserConfig.txt, the function readUserConfig will segfault if you try to list a device that has longer than 20 characters. This is important when you want to specify a usb device by anything other than /dev/ttyUSB# (e.g. /dev/serial/by-id/...)

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
