### ISSUE TITLE
Can you advise on current state of M600 support?

### ISSUE THREAD

**Issue by stefangordon** [dji-sdk/Onboard-SDK#134]
Release notes say use 3.3 if you have an M600, but version matrix says "coming soon".

**Comment by rohitsantdji** [comment]
The version matrix is the source of truth - M600 firmware supporting the SDK should be out very soon. Sorry for the lack of clarity on this!

**Comment by stefangordon** [comment]
Thanks! The M600 is very large so it is a hassle to drag it out to test :)
