### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by jhaws1982** [dji-sdk/Onboard-SDK#136]
I fixed a bunch of compiler issues that cropped up when adding -Wall -Wpedantic.  Take a look at the patch and see if you want to roll these changes in or not.

[0001-Fixing-compiler-warnings-when-enabling-high-verbosit.patch.txt](https://github.com/dji-sdk/Onboard-SDK/files/1103761/0001-Fixing-compiler-warnings-when-enabling-high-verbosit.patch.txt)

**Comment by rohitsantdji** [comment]
Thanks for the effort, much appreciated! We're currently lacking the bandwidth to evaluate this and run it through our testing infrastructure, but we will certainly spend some time on it later this month. I'm closing this issue for now, will re-open it when we start work on it again.
