### ISSUE TITLE
QT Example & M600 Firmware Release

### ISSUE THREAD

**Issue by pingualoty** [dji-sdk/Onboard-SDK#141]
Is there any ETA on both the QT Example release that is labelled as coming soon in 3.3 or the required M600 firmware to use 3.3. Thanks.

**Comment by rohitsantdji** [comment]
We're currently looking at an end-July/early August timeframe for both.

**Comment by rohitsantdji** [comment]
@pingualoty M600 firmware with OSDK 3.3.1 support has been released today.
