### ISSUE TITLE
OSDK v3.3 throwing up error on running sample

### ISSUE THREAD

**Issue by taurean1192** [dji-sdk/Onboard-SDK#142]
I am getting the following error upon running the sample for telemetry. Earlier my flightcontrol sample was running fine but now even that is throwing error.

![djiosdkerr](https://user-images.githubusercontent.com/24839780/27781772-28861ff6-5fed-11e7-9eae-aa6fcb33f54c.png)

Some help will be really great.

**Comment by rohitsantdji** [comment]
@taurean1192 it appears that there is no data on the line. Could you provide some more information to help us debug:

1. Is this a Pi2 or a Pi3 or a Pi zero?
2. Do you have permissions to write to the serial port (did you run sudo usermod -a -G dialout $USER ?)
4. After upgrading firmware on your A3/N3, did you ensure that the baud rate to the correct value, and reboot the flight controller after clicking enable API control?
5. Could you try the sample at baud rate 230400?

A similar issue is also being tracked here : dji-sdk/Onboard-SDK-ROS#98

**Comment by taurean1192** [comment]
@rohitsantdji  
1. This is a Pi3 running Raspbian
2. Yes, I do have permissions to write to the serial port.
3. I am connecting to an A3
4. Yes, I had checked for the API control. I had cross-checked for matching baud rates as well, the flight control sample did run as a matter of fact
5. I tried changing it to 230400 and check, the output was same as last time.

**Comment by adamwathieu** [comment]
I have a similar issue, any help would be great:
https://github.com/dji-sdk/Onboard-SDK/issues/143

**Comment by chutsu** [comment]
I was having the same problem but I think I found a solution, the approach I took to fix this issue is to **simply plug the USB-UART directly into the computer's USB port** (not USB hub).

**Comment by taurean1192** [comment]
@chutsu I did that.. still the same issue.. as 
![image](https://user-images.githubusercontent.com/24839780/28201591-65309760-688f-11e7-9918-646d5729a3f4.png)

**Comment by chutsu** [comment]
When you copied the `UserConfig.txt` did you actually put in your own APP ID and APP KEY? in your above screenshots it does not look like you edited it.

**Comment by taurean1192** [comment]
If you know in 3.3 it doesn't show up when the code executes. Yes, I have
my API ID n Key

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
