### ISSUE TITLE
.

### ISSUE THREAD

**Issue by jhmoon999** [dji-sdk/Onboard-SDK#148]

**Comment by rohitsantdji** [comment]
I'm putting this up on the Wiki here on Github for better visibility. Thanks a lot for contributing this!

**Comment by rohitsantdji** [comment]
https://github.com/dji-sdk/Onboard-SDK/wiki/Tips-on-connecting-the-Raspberry-Pi-to-the-Matrice-100

**Comment by adamwathieu** [comment]
This is perfect. Thanks for the contribution!

**Comment by titulebolide** [comment]
Why has this wiki been deleted?
