### ISSUE TITLE
Ronin MX control not yielding expected behavior (limits, units, etc.)

### ISSUE THREAD

**Issue by jhaws1982** [dji-sdk/Onboard-SDK#150]
I'm working with an M600 Pro and a Ronin MX gimbal.  For the most part I have my software interfacing with the API correctly (I think).  I'm able to pull navigation data from the A3 and point the Ronin around.

However, I've found that the Ronin doesn't behave quite like I would expect.  I've got it more or less balanced, but when I move in pan or tilt, I also get small motion in the other axes.  This is just a minor annoyance.

The major issues I'm having are dealing with weird limits.  I'm just running through the simulator in DJI Assistant 2.  

If I ask for a 45 degree pan (yaw) and -75 degree tilt (pitch) It gives me +30 degrees of pan and -45 degrees of tilt. If I ask for a -45 degree pan (yaw) and 30 degree tilt (pitch) It gives me -30 degrees of pan and +20 degrees of tilt.

From there I have code that just bumps it one direction by one degree.  That isn't working as expected either.  If I'm at +20 degrees tilt and try to go to +21, it moves the wrong direction and goes to something like +15.  If I try and bump to +19 degrees from +20, it goes way beyond that to +12 or so.  Same for when I'm at -45 and try something similar.

Right now I don't have a camera mounted at all, so motor strength settings shouldn't matter (I've got it set to DSLR).  Also, I've checked that I'm in Free mode and have verified all my limits are set reasonably (pan at 179 for left and right, tilt at 45 up, 90 down).

Thoughts?

**Comment by jhaws1982** [comment]
I should also mention that everything behaves properly when I operate close to 0,0 position.

**Comment by jhaws1982** [comment]
I did find that if I auto-tuned the motors things improved greatly.  I also found that when pointing at extreme tilts it motors couldn't hang on (again, no camera) so I rebalanced and then it could hold on just fine.

Right now my main issue is the fact that I can't point more than +/- 30 degrees in yaw in the simulator.  Is this because it is looking at a landing gear sensor or something?  My application requires that I can point at least as far as the landing gear, which is at more or less +/- 45 degrees.

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
