### ISSUE TITLE
M100. Cant start to use samples apps. (Activation problem)

### ISSUE THREAD

**Issue by Martintl** [dji-sdk/Onboard-SDK#151]
I've just started to learn Onboard SDK. So i tried to run some samples , and have 2 errors 
![terminal_scr](https://user-images.githubusercontent.com/30313964/28415601-c011690a-6d50-11e7-854a-2d1fecb828e9.jpg)
That error for ./djiosdk-linux-sample , and that error and "Error in setControl API function" for ./djiosdk-linux-sample-nonblocking 

I'm using the latest version of software ( Dji assistance 2 for mac , dji go for iPad ) and Osdk 3.2 .
What should i do ? Thanks!

**Comment by rohitsantdji** [comment]
Please see #145 - in brief, this is a known issue with the DJI Go app v3.1.13 on iOS. If you have an Android device, please attempt to activate using that. This issue has been fixed in DJI Go v3.1.14, which will release for iOS in the next couple of weeks. Thanks for your patience!
