### ISSUE TITLE
Inconsistency between document and sample code

### ISSUE THREAD

**Issue by groundmelon** [dji-sdk/Onboard-SDK#16]
In "Monitor Command Set: 0x02" > "Command ID 0x00 Message Package":

The type of item **magnetometer** is **```float32```**. See 

Chinese Version: https://github.com/dji-sdk/onboard/blob/master/Onboard_API_Doc/Onboard_API_%E8%AF%B4%E6%98%8E%E6%96%87%E6%A1%A3.md#命令码-0x00-标准数据包 

English Version: https://github.com/dji-sdk/onboard/blob/master/Onboard_API_Doc/Onboard_API_introduction.md#command-id-0x00-message-package 

But in DJI_Onboard_API_ROS_Sample, the **```sdk_3_6B_data_t```** is using **```int16_t```**
https://github.com/dji-sdk/onboard/blob/master/Onboard_SDK_Sample/DJI_Onboard_API_ROS_Sample/dji_sdk/src/sdk_lib/DJI_Pro_App.h#L124

**Comment by lanyusea** [comment]
the new document has updated it into int16_t
