### ISSUE TITLE
Waypoint sample with MissionPlanner (M100 OSDK 3.2)

### ISSUE THREAD

**Issue by Martintl** [dji-sdk/Onboard-SDK#164]
I have problems with starting waypoint mission by using file from MP. 
I have message "Invalid waypoint point data". 

I do the same thing as in example -> https://github.com/dji-sdk/Onboard-SDK/blob/3.2/osdk-wrapper/src/LinuxWaypoint.cpp
Only i change longitude , altitude , and latitude .

**Comment by rohitsantdji** [comment]
What lat/lon/alt values are you inputing? Note that the values must be in radians.

**Comment by Martintl** [comment]
@rohitsantdji Hi! I think i found my problem . It causes bc i set home position in simulator same as on foto , but function "getBroadcastData().pos" return lon(0.873999) lat(0.251656) . How can i fix it? 
![nbt2zhyqjve](https://user-images.githubusercontent.com/30313964/29360656-414aa048-8284-11e7-9163-3a7eb83ce57c.jpg)

**Comment by Martintl** [comment]
@rohitsantdji Hello and thank you for response! I think i found my problem . That happens bc i dont know how to convert data from GPS ( long , lat .. ) to lon/ lat that i get by "api->getBroadcastData().pos" .

**Comment by rohitsantdji** [comment]
The values you get from `getBroadcastData().pos()` are in radians; to convert them to the values you set in mission planner you need to do a radians-->degrees conversion (*180/pi). Also for waypoint values, you need to set altitude < 400 ft (~120m) since it is interpreted as a relative altitude above takeoff point.

**Comment by rohitsantdji** [comment]
Closing since the issue seems to be resolved - if you have follow-ups, please re-open.

**Comment by semihyildirim** [comment]
I want to enter my own gps coordinates to waypoint example. I get an error as WAYPOINT_MISSION_INVALID_POINT_DATA. I  need to change in function of createWaypoints(line of 198 at Onboard-SDK/sample/linux/mission_sample.cpp). The function arguments provided by subscribeGPosition but I want to supply my own. How to do it?

**Comment by nkkoufo** [comment]
hi semihyildirim, have you made sure that when you set the latitude and longitude for your waypoints that they are in radians? The documentation for dji says that it needs to be in radians you can convert from degrees by (pi * (latitude or longitude in degrees)) / 180

**Comment by semihyildirim** [comment]
Yes, I have done it.
