### ISSUE TITLE
Could OBSDK provide api to set home point position?

### ISSUE THREAD

**Issue by magenious** [dji-sdk/Onboard-SDK#165]
Hi, Dear developers, 
            I have one question that mobile SDK provide api to set home point for drone, but why not open for 3.2 and 3.3 onboard SDK?  We are eager to use this api  in long distance flight for urgent landing when battery is low. Thanks.

**Comment by rohitsantdji** [comment]
Hi @magenious, this is on our long term roadmap for the OSDK. Stay tuned!
