### ISSUE TITLE
Matrice 600 Pro FW 1.0.1.60 - usable range with the SDK ?

### ISSUE THREAD

**Issue by flytrex-vadim** [dji-sdk/Onboard-SDK#166]
The M600 FW 1.0.1.60 that was released today has the following line in release notes: 

"For increased safety, the flight is restricted to a height of 30 m and distance of 50 m when not connected
or logged into the app during flight, including DJI GO* and all apps compatible with DJI aircraft."

Does that imply that without RC connection the SDK control would be limited to operating inside these limits ? If so the upgrade would effectively brick the drone for us ...

**Comment by rohitsantdji** [comment]
Hi Vadim - that restriction only applies if you are attempting to fly the M600 in Mainland China, as per local laws and regulations. You can safely ignore that restriction if you are elsewhere.
