### ISSUE TITLE
Programatically Enable API Control? (OSDK 3.1.7 on Linux)

### ISSUE THREAD

**Issue by rpici** [dji-sdk/Onboard-SDK#168]
Using OSDK version 3.1.7 on Linux, I previously successfully activated the API connection through DJI::onboardSDK::CoreAPI::activate() with the "Enable API Control" checkbox checked in DJI Assistant 2.

However, the "Enable API Control" checkbox sometimes seems to get automatically unchecked in different scenarios (firmware update, etc.), without me knowing.  In this situation, if I restart my app, the API connection still gets successfully activated.  I still get GPS data from the API port, but all that data is zeroed out.

While my app is running, if I then go into DJI Assistant 2 and manually check the "Enable API Control" checkbox, I then start getting good GPS data.

So even if "Enable API Control" is unchecked, it seems like there is still some sort of communication going on over the API port, even though the (GPS) data is bad.

My question is, given that there seems to be communication taking place even with "Enable API Control" unchecked, is it possible to programmatically check the "Enable API Control" checkbox through the SDK somehow, so that we don't have to open DJI Assistant 2 to manually check that checkbox?

**Comment by amenonDJI** [comment]
@rpici At the moment, there is no way to Enable API programmatically. We do realize this is a useful feature to have, thanks for your feedback and we will incorporate this in the future.
