### ISSUE TITLE
MFIO的demo说明序号有误

### ISSUE THREAD

**Issue by wushifu32** [dji-sdk/Onboard-SDK#171]
https://github.com/dji-sdk/Onboard-SDK/blob/52d49339ef3f9ac50e66cc3cc71c3f909fc1bd1f/sample/linux/mfio/mfio_sample.cpp#L36
此处在配置上应该选择SDK4

**Comment by lanyusea** [comment]
Translation:

Title: The Demo of MFIO has incorrect instruction.
Content: To correct, the SDK1 should be replaced by SDK4.

**Comment by rohitsantdji** [comment]
Thanks for catching the bug. Will be fixed in the next release!
