### ISSUE TITLE
Unexpected MISSION_IN_PROGRESS error and weird behaviour

### ISSUE THREAD

**Issue by talz** [dji-sdk/Onboard-SDK#179]
I've been getting MISSION_IN_PROGRESS errors in some unexpected scenarios.

1. The drone has completed a waypoint mission in the air (without landing) and I'm uploading a new route while it's in the air.

2. Calling waypoint mission stop (after the drone has landed, or in the previous scenario before uploading a new route) - returns with this error.

3. After landing (manually or via the 'land' control command) and starting a new mission - calling the waypoint mission start will fail with this error - but the drone will take off non the less.

**Comment by tahsinkose** [comment]
Hi @talz, I wonder did you find out any solutions?

**Comment by talz** [comment]
No.
IIRC, I just teared down the connection to the drone, and reinitialized it.

**Comment by tahsinkose** [comment]
As I just diagnosed, FC treats initialized _but not started_ missions as IN_PROGRESS. Started missions do have preemption logic; but solely initialized (i.e. uploaded) missions do not. That's why, one needs to restart SDK to preempt buffers.

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
