### ISSUE TITLE
Support for m200 Series

### ISSUE THREAD

**Issue by a2hill** [dji-sdk/Onboard-SDK#180]
Is there an approximate date for when we will be seeing OSDK support for the m200 series?

**Comment by rohitsantdji** [comment]
We're looking at an OSDK release with M210/M210 RTK support by early October - around the second week. Hopefully it might go out even earlier!

**Comment by rohitsantdji** [comment]
Update - We're putting the firmware and DJI Assistant 2's M210 simulation visualizer through testing, and we're holding the release of OSDK for M210/RTK until those go out. ETA is now first week of November.

**Comment by AurelienBallier** [comment]
Hello,
Still any news from M210 support?
Regards,

**Comment by botaohu** [comment]
Any update?

**Comment by amenonDJI** [comment]
@AurelienBallier @botaohu Apologize for the delay. We are now shooting tentatively for November 22nd.

**Comment by AurelienBallier** [comment]
Thanks for the update.

**Comment by plant99** [comment]
Hey @amenonDJI  updates?
Thank you.

**Comment by rohitsantdji** [comment]
@plant99 We released OSDK 3.4 on Nov 22 with full support for M210/RTK, as well as some great new features. Get the[ latest 3.4.2 release](https://github.com/dji-sdk/Onboard-SDK/releases/tag/3.4.2) for some post-release bugfixes as well!
