### ISSUE TITLE
Monitoring waypoint mission status in 3.3.1

### ISSUE THREAD

**Issue by brentalanmiller** [dji-sdk/Onboard-SDK#181]
We're currently upgrading the version of the Onboard SDK that we're using from 3.2 to 3.3 and we're noticing that the WaypointMission callback doesn't seem to get called when the target waypoint changes.

Our use case is that our M100 is commanded by a mobile application, but we have an onboard computer that's monitoring the progress of a waypoint mission. In 3.2 were able to register a callback to monitor the status of the mission by doing something like:
```C++
auto api = new CoreAPI(serial_device);
...
api->setMisssionCallback(missionCallback, this);
```
Which was perfect for us as this would return Current Mission Status Push Information (cmd_set == 0x02 && cmd_id == 0x03) and tell us everything we need to know.

But with 3.3 we're trying something like:
```C++
auto vehicle = new Vehicle(serial_port, baud_rate, true);
...
vehicle->missionManager->init(DJI_MISSION_TYPE::WAYPOINT, 10)
vehicle->missionManager->wpMission->setWaypointCallback(missionCallback, this);
```

But the callback never gets called. If we use the `setWaypointEventCallback` method, our callback gets called, but it seems to only return Mission Event Push Information (cmd_set == 0x02 && cmd_id == 0x04), and we only get waypoint reached incidents on the first and last waypoints of a mission.

Is there a good way to have a callback called each time we reach a waypoint in 3.3.1? Alternatively, is there a way to register a callback on arbitrary Open Protocol messages so that we can just read in all the  Mission Status (0x02, 0x03) messages?

**Comment by brentalanmiller** [comment]
Looks like the variable `wayPointData` is never set. https://github.com/dji-sdk/Onboard-SDK/blob/2295710a83600a44e481995b726de6fa5e9c0f7d/osdk-core/api/src/dji_vehicle.cpp#L1365

What's the intended way to set this variable?

**Comment by brentalanmiller** [comment]
Created pull request https://github.com/dji-sdk/Onboard-SDK/pull/184

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
