### ISSUE TITLE
Onboard Missions (Qt)

### ISSUE THREAD

**Issue by Valkaryne** [dji-sdk/Onboard-SDK#186]
I work with OSDK Qt Sample Application (OSDK 3.3) and I have faced with one bug (or maybe feature): I can run Waypoint Mission no more than 3 times. After third running in the console displays: "SendInterface ... ERROR,there is not enough memory".
When I worked with OSDK Qt Application (OSDK 3.2), there weren't any problems with number of launches.
Is there some way to fix it?

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
