### ISSUE TITLE
How to get  timestamp on the Flight Controller? 

### ISSUE THREAD

**Issue by botaohu** [dji-sdk/Onboard-SDK#187]
In all recorded video by DJI drones, it has a timestamp (UTC datetime) for creation time.

But from OSDK, how can I get the current time in UTC of the flight controller?

The timestamp from broadcast data only contains "time: uint32, times_ns: uint32"
But in this structure, the time is the duration after last time the flight controller power cycled.  
We cannot get the absolute time of the current flight controller.

**Comment by sergio303** [comment]
You could try getting time from the Telemetry::GPSInfo structure (not supported on Matrice 100).

**Comment by zliDJI** [comment]
Sergio is right.

**Comment by sdo91** [comment]
@sergio303 @zliDJI can you expand on getting time from this Telemetry::GPSInfo structure? Is there a topic I can subscribe to to get this data?

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
