### ISSUE TITLE
Failed to activate OSDK on M100

### ISSUE THREAD

**Issue by chocksmith** [dji-sdk/Onboard-SDK#189]
I am trying to run the djiosdk-flightcontrol-sample on a M100 drone but I am getting the following output/error:

    
    pi@drone:~/drone/Onboard-SDK-3.3/build/bin $ ./djiosdk-flightcontrol-sample ../../sample/linux/common/UserConfig.txt 
    Read App ID
    User Configuration read successfully. 

    STATUS/1 @ init, L37: Attempting to open device /dev/ttyUSB0 with baudrate 230400...

    STATUS/1 @ init, L47: ...Serial started successfully.

    STATUS/1 @ parseDroneVersionInfo, L568: Device Serial No. = 041DE52780

    STATUS/1 @ parseDroneVersionInfo, L570: Hardware = M100

    STATUS/1 @ parseDroneVersionInfo, L571: Firmware = 3.1.10.0

    STATUS/1 @ parseDroneVersionInfo, L574: Version CRC = 0xA6453AAC

    STATUS/1 @ functionalSetUp, L126: Subscriber not supported!

    STATUS/1 @ functionalSetUp, L164: MFIO not supported!

    ERROR/1 @ functionalSetUp, L182: Hardware Sync not supported!

    STATUS/1 @ activate, L951: version 0x3010A00

    STATUS/1 @ getErrorCodeMessage, L590: activate
    STATUS/1 @ getCMDSetActivationMSG, L638: NEW_DEVICE_ERROR

    ERROR/1 @ activate, L971: Failed to activate please retry SET 0x0 ID 0x1 code 0x3

    STATUS/1 @ getErrorCodeMessage, L590: setupOSDK
    STATUS/1 @ getCMDSetActivationMSG, L638: NEW_DEVICE_ERROR
    Vehicle not initialized, exiting.
    pi@drone:~/drone/Onboard-SDK-3.3/build/bin $ 

As you can see, the computer can reach the M100 via USB:

* The M100 is connected to the CPU via the UART_CAN2 cable and a TTL-USB converter. 
* The OSDK can read/write from/to the M100: (it gets the device serial No, etc)
* The App ID and Key are set in the configuration file.
* The Assistant is running on another CPU (a Mac)
* All transmission rates are different than zero and less than 100Hz at the DJI OSDK configuration page 

Everything looks right, but it does not work and gives the obscure message:

> Failed to activate please retry SET 0x0 ID 0x1 code 0x3

Any ideas? Please help.

**Comment by rohitsantdji** [comment]
From the [docs](http://developer.dji.com/onboard-sdk/documentation/quick-start/quick-start.html):
>
>Q. The sample says Activation failed! and does not proceed.
>
>A. Please make sure you have DJI Go open and your mobile device connected to the internet, and the correct App ID and Key in your config.json file. Try a couple of times, if it doesn't work, raise a Github issue.

The NEW_DEVICE_ERROR indicates that the activation was unable to verify your app ID and key with the activation server. This could be because the ID and Key do not match, but it is usually because DJI Go is not open or does not have connection to the Internet.

**Comment by chocksmith** [comment]
Thank you!
