### ISSUE TITLE
Bug at flight_control_sample.cpp

### ISSUE THREAD

**Issue by chocksmith** [dji-sdk/Onboard-SDK#191]
Hello,

This is the code that checks if the motor has started:

                while ((vehicle->broadcast->getStatus().flight
				!= DJI::OSDK::VehicleStatus::M100FlightStatus::TAKEOFF)
				&& motorsNotStarted < timeoutCycles) {
			motorsNotStarted++;
			usleep(100000);
		}

		if (motorsNotStarted == timeoutCycles) {
			std::cout << "Successful TakeOff!" << std::endl;
		}

The code above works, but it is not correct. The correct would be something like:

               while ((vehicle->broadcast->getStatus().flight
				< DJI::OSDK::VehicleStatus::M100FlightStatus::TAKEOFF)
				&& motorsNotStarted < timeoutCycles) {
			motorsNotStarted++;
			usleep(100000);
		}

		if (motorsNotStarted < timeoutCycles) {
			std::cout << "Successful TakeOff!" << std::endl;
		}

Same mistake happens on others subsequent checks.

**Comment by rohitsantdji** [comment]
Good catch! Can you submit a PR?

**Comment by chocksmith** [comment]
I will!
Tks!
