### ISSUE TITLE
Connecting UltraWideBand to DJI Matrice 100 N1 Flight controller

### ISSUE THREAD

**Issue by trgiman** [dji-sdk/Onboard-SDK#193]
We would like to know if we can disconnect the GPS module of Matrice 100 (keep compas connected) and use Ultra Wide Band tag, that is providing NMEA 0183 format out of the box

https://marvelmind.com/shop/starter-set-hw-v4-9-plastic-housing/

1.What is the update frequency that we should setup for MarvelMind UWB, so it can update N1 flight Controller?
2.What is the UART speed for GPS/MarvelMind?

Eventually should we use other UWB modules such as https://www.pozyx.io/. But they are not providing data in NMEA 0183 format out of the box.

Or should we connect it to Matrice rather via Manifold. But than how we can command Matrice to move to correct point in coordinates system?

Thank you.

**Comment by rohitsantdji** [comment]
Continue the disucssion on dji-sdk/Onboard-SDK-ROS#148.
