### ISSUE TITLE
Possibly wrong hw_serial_num[] element being set to '\0', and array index out of bounds

### ISSUE THREAD

**Issue by rpici** [dji-sdk/Onboard-SDK#200]
In line 1074, it says:
`droneVersionACK.data.hw_serial_num[sizeof(this->versionData.hwVersion)] = `

but shouldn't it instead say:
`droneVersionACK.data.hw_serial_num[sizeof(this->versionData.hw_serial_num)] =   //isn't this out of bounds?`

?

https://github.com/dji-sdk/Onboard-SDK/blob/0b080dd0c2ee09d4330cf0d1becb12699d5b97c3/osdk-core/api/src/dji_vehicle.cpp#L1068-L1075

Also, line 1070 is giving me a compiler warning:
`warning: array subscript is above array bounds [-Warray-bounds]`

...because the subscript is one past the end of the array.

If the fix to line 1074 above is in fact the correct thing to do, then it will also trigger the same out-of-bounds warning.

I'm not sure how big those arrays need to be, but however many bytes of data they need to hold, shouldn't they have one extra byte for the terminating`'\0'` character to get rid of the warning?  The array subscripts should then be `array[sizeof(array) - 1]`, should they not?

**Comment by rohitsantdji** [comment]
That's a good catch! Yes, L1074 needs the fix. The array sizes have been designed, as you correctly mention, so that the data will at most fill up `sizeof(array) - 1` elements, so the only other fix needs to be `array[sizeof(array) - 1] = '\0'`. If you want to submit a PR, we'll merge it in.

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
