### ISSUE TITLE
index out of bound

### ISSUE THREAD

**Issue by adrianhsm** [dji-sdk/Onboard-SDK#207]
In parseDroneVersionInfo function,
....
uint8_t crc_id[16] = {};
  int     i          = 0;
  while (*ackPtr != '\0')
  {
    crc_id[i] = *ackPtr;
    i++;
    ackPtr++;
    if (ackPtr - startPtr > 18)
    {
      DERROR("Drone version was not obtained. Please restart the program or "
             "call getDroneVersion\n");
      return false;
    }
  }
....
for above code, when it goes to 'return false', variable i would be larger than 16, which means the index of crc_id is out of bound, and we also find that "index out of bound" happens somewhere in code which could lead to heap corruption during flying, and then no heart beat is sent to fc, it leads to unexpected rth. We may update later and hope that you guys could fix this

**Comment by rohitsantdji** [comment]
See #203 .
