### ISSUE TITLE
Negative altitudes?

### ISSUE THREAD

**Issue by rpici** [dji-sdk/Onboard-SDK#216]
Hello,

In OSDK 3.4, I'm running the linux telemetry sample, and I'm getting large negative values for altitude (`TOPIC_ALTITUDE_FUSIONED`).

I modified the example to output altitude directly from the barometer topic (`TOPIC_ALTITUDE_BAROMETER`) and from the fused GPS topic (`TOPIC_GPS_FUSED`).

While indoors, I'm seeing altitudes of around -60 to -70 from any of the above sources.

While outdoors, I haven't tried OSDK 3.4 yet, but I have used OSDK version 3.3.  While flying several feet above the ground, from `TOPIC_GPS_FUSED` in OSDK v3.3 I get altitudes of around -30.

1) ~~Am I interpreting the numbers incorrectly?  Is there some calculation that needs to be done on the value to get a valid altitude?~~ I think I found the answer to this through googling "WGS84".
2) In what units is the altitude value?  Is it in meters?

**Comment by jswoboda** [comment]
I've seen this as well.

**Comment by amenonDJI** [comment]
@rpici 
1.) You're reading WGS84 Altitude. 
2.) Unit is in meters.

**Comment by rpici** [comment]
@amenonDJI 
What about altitude retrieved from `TOPIC_ALTITUDE_FUSIONED`?  This doesn't always return WGS84 height, does it?  The "FUSIONED" in the name suggests that it could return a WGS84 height, or it could return a height from other sources, e.g. barometer.  Can you clarify this?

**Comment by eeroniemi** [comment]
See my comment here, could help someone: https://github.com/dji-sdk/Onboard-SDK-ROS/issues/155#issuecomment-348539107

**Comment by amenonDJI** [comment]
@rpici @jswoboda Please reference [this](https://github.com/dji-sdk/Onboard-SDK/wiki/Altitude-Reference-for-different-topics) wiki page for more information regarding Altitude reference
