### ISSUE TITLE
api_vel_data_t is corrupting the data that follows it.

### ISSUE THREAD

**Issue by geetesh** [dji-sdk/Onboard-SDK#22]
```
typedef struct
{
    fp32 x;
    fp32 y;
    fp32 z;
//    unsigned char health_flag         :1;
//    unsigned char feedback_sensor_id  :4;
//    unsigned char reserve             :3;
}api_vel_data_t;
```
Flight Controller version: 2.2.7
I had to comment out the last three values to fix this issue. I think N1 controller is not outputting this format leading to corruption of all the data that follows it like the global/local position, RC etc.

**Comment by lanyusea** [comment]
Hi, did you install Guidance?

**Comment by geetesh** [comment]
Yes, I did.

**Comment by geetesh** [comment]
Hi, is this issue fixed? I see you have made a new commits but this data structure is till the same. What firmware for N1 controller does this support?

**Comment by lanyusea** [comment]
hi @geetesh ,we are still checking if there is something working incorrect in N1 part or in Guidance part.

may I ask the version of your N1 and Guidance firmwares?

**Comment by geetesh** [comment]
I think the public firmware for N1 is 2.2.7 and thats why the issue persists. My Guidance sensor is using 1.3.7. When do youplan to release 2.3?

**Comment by lanyusea** [comment]
hi @geetech, we have already release 2.3. Please download the new N1
assistant and use it to update your firmware.

https://developer.dji.com/onboard-sdk/downloads/

**Comment by geetesh** [comment]
great, will try it and get back to you if the issue persists

**Comment by lanyusea** [comment]
just tell me if this issue still resist ;)

**Comment by lanyusea** [comment]
Hi @geetesh , does the problem persist? 
if not, I will close this issue.

**Comment by geetesh** [comment]
hi sorry for the delay. i'll get back with the results within 24hrs

**Comment by geetesh** [comment]
I have been trying to update the FW via N1-Assistant but the dji server seems to be down. I am not able to login or update the firmware. Are you also facing such issues? Im in Pittsburgh, USA

**Comment by geetesh** [comment]
Hey, so finally i was able to update to 2.3.2 and the issue is resolved. Thanks :D

**Comment by lanyusea** [comment]
glad to hear that it is solved :)
