### ISSUE TITLE
gimbal control and subscription problems

### ISSUE THREAD

**Issue by greg-draganfly** [dji-sdk/Onboard-SDK#222]
I am working with an M600 pro and am having some intermittent difficulty.  I am using an STM32 with OSDK 3.3.1

Sometimes (usually on initial power up) the gimbal fails to initialize, Vehicle::initGimbal returns false.  It fails via this code path:

`  else if (this->getFwVersion() != Version::M100_31)
  {
    ACK::ErrorCode ack = this->subscribe->verify(wait_timeout);
    if (ACK::getError(ack))
    {
      DERROR("Failed to verify subscription!\n");
      return false;
    }
`

subscribe->verify returns the ack code ILLEGAL_INPUT.  Repeating the call over and over seems to have no effect.  I noticed that vehicle::waitForAck calls protocolLayer->getThreadHandle()->wait(timeout);, which on STM32 defaults to this: 

```
void
STM32F4DataGuard::wait(int timeoutInSeconds)
{
}
```

I added a call to STM32F4::delay_nms here, but this had no effect.  What might be the problem here?

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
