### ISSUE TITLE
waypoint damping

### ISSUE THREAD

**Issue by greg-draganfly** [dji-sdk/Onboard-SDK#223]
Can someone please explain the usage of WaypointSettings.damping?  The comment in the source reads:

float32_t damping; /*!< Bend length (effective coordinated turn mode only) *

What are the units on this?  I want to fly a mission where each waypoint is NOT stopped at, but I don't really care about the smoothness of the curve.  I have had some cases where waypoints return 0xE7.  Can someone explain what this error means and how the waypoints must be configured to avoid it?

**Comment by jarednm** [comment]
Did you ever find out?  Wondering the same thing.

**Comment by lanyusea** [comment]
the coordinated turn mode means the drone will not fly from point to point directly like polyline but do curve when passing a waypoint.

the bend length is a param to determine how the curve looks like.

**Comment by jarednm** [comment]
Sure, but what are the units on damping?  Is it dimensionless 0-1, 0-100%, or is it meters of the radius of curvature, etc?

**Comment by lanyusea** [comment]
Forget about the details since I have been away from SDK project for years. I suggest to try it in the simulator and see how it influences the curve.

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
