### ISSUE TITLE
Flight Control Sample Bug

### ISSUE THREAD

**Issue by amenonDJI** [dji-sdk/Onboard-SDK#225]
A bug was seen in Flight control sample where the aircraft loses altitude even when positive Z offset commands were given. See issue #201 for reference. We are investigating the issue and we are looking to have a fix for the next release. Until then, please do not use Flight Control sample in the Linux Onboard SDK and ROS versions.

**Comment by justwillim** [comment]
Fixed in 3.6

**Comment by path9263** [comment]
Is this fixed for the Raspberry Pi branch too?

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
