### ISSUE TITLE
extractOnePackage error

### ISSUE THREAD

**Issue by kezhengtao** [dji-sdk/Onboard-SDK#227]
我有两个package在QT 3.5程序退出的时候没有stop
下次启动之后就一直报这个错：
ERRORLOG/1 @ DJI::OSDK::DataSubscription::extractOnePackage, L382: Package does not have a valid DataBuffer

**Comment by zliDJI** [comment]
you need to reboot the drone/flight controller

**Comment by kezhengtao** [comment]
`if (p->getDataBuffer()==0)
  {
      DERROR("Package %d does not have a valid DataBuffer,removing...",pkgID);
      subscriptionHandle->removePackage(pkgID);
      return;
  }`
I just add this. Have fun.

**Comment by kezhengtao** [comment]
`void
SubscriptionPackage::packageRemoveSuccessHandler()
{
    if(packageDataSize==0)
        return;`
And don't forget this.

**Comment by justwillim** [comment]
Could you make a PR? that would help a lot

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
