### ISSUE TITLE
What is "Function Call:moniteredTakeOff"

### ISSUE THREAD

**Issue by kezhengtao** [dji-sdk/Onboard-SDK#228]
![image](https://user-images.githubusercontent.com/11263749/34762757-e1fead5a-f623-11e7-8351-1e2b9d580e74.png)
I have seen this flow chart:https://developer.dji.com/onboard-sdk/documentation/sample-doc/flight-control.html
I don't known where to call this function.  Some button  on QT  UI?
And of course my aircraft can not fly now. Anybody help me to let it fly?Fly in the simulator.

**Comment by rohitsantdji** [comment]
Hi @kezhengtao , this sample is only available on Linux through the native linux APIs, and through ROS APIs.

On Qt, we do not have individual samples, instead you can select takeoff in the drop-down box (see the image below), and then move the sliders in the FlightControl panel in the GUI to send movement control commands. 
![qt sample](https://user-images.githubusercontent.com/20171499/34787965-f590b600-f5ed-11e7-9b3f-e51fa760c0b8.png)
