### ISSUE TITLE
Controlling the velocity of M100 

### ISSUE THREAD

**Issue by QRI-nashw** [dji-sdk/Onboard-SDK#238]
Hey DJI Team,
I'm using the moveByPositionOffset sample function provided in the SDK, however I noticed that using this function, the drone will max out at about 3m/s. Is there any way to change the velocity of the drone in this function? And if I am unable to change the speed of this function, how does one change the velocity of the M100? Thanks!

**Comment by rohitsantdji** [comment]
You can change the value of [speedFactor](https://github.com/dji-sdk/Onboard-SDK/blob/3.6/sample/linux/flight-control/flight_control_sample.cpp#L425).

The logic is that if the distance to the goal is greater than the `speedFactor`, keep going at a steady velocity of `speedFactor`, if the distance is less, then pass this lower value as the velocity command.
