### ISSUE TITLE
Combining waypoints and hotpoints into a single mission?

### ISSUE THREAD

**Issue by QRI-nashw** [dji-sdk/Onboard-SDK#239]
Is it possible to link waypoints and hotpoints in a single mission? I noticed the samples are split up into WP and HP missions, and after looking at the code it seems that indeed HPs and WPs are split up in dji_mission_manager.cpp as well. Does this mean that you cannot interrupt a waypoint mission with a hotpoint? For example, I have 3 locations: A, B, and C. I would like the drone to navigate to A, pause for a few seconds, continue to B where it executes a hotpoint, after which continuing to point C.

**Comment by rohitsantdji** [comment]
That is true - you cannot interrupt a WP mission with a hotpoint, however you could split up this sort of mission into a WP mission, then an HP mission, and finally a second WP mission *if* in each WP mission you have more than a single waypoint. 

As always  - if the current design doesn't satisfy any specific needs, keep the requests coming on #233 !
