### ISSUE TITLE
can't communicate with M210 using the USB-TTL cable.

### ISSUE THREAD

**Issue by Alikhajehei94** [dji-sdk/Onboard-SDK#242]
I have followed the DJI guide in running a sample app from their library and this when I get when I run the sample. "Drone version not obtained"
![img_20180205_152216](https://user-images.githubusercontent.com/36179107/35838640-5566969a-0aba-11e8-9215-3bd1f8f30939.jpg)

Any idea why this is happening?
how can I make sure to see if the linux is able to communicate with the M210?
Thanks,
Ali

**Comment by rohitsantdji** [comment]
Did you try all the suggestions the error message is giving you?

**Comment by Alikhajehei94** [comment]
Yes I tried all the massages displayed. Still thesame error.

**Comment by rohitsantdji** [comment]
Could you share screenshot of your Assistant 2 SDK Page and a picture of your serial connections?

**Comment by Alikhajehei94** [comment]
I figured what it was wrong. I had a faulty cable.
