### ISSUE TITLE
DJI A3 problems with SDK > 3.3

### ISSUE THREAD

**Issue by OShapovalov** [dji-sdk/Onboard-SDK#246]
When we use e6c293341fb5461e8b364a584ca2bae8855cb5d5 (3.3) revision for onboard-sdk and ffc2f08a7f5da0f7d590fcba281d80706dd975cd for onboard-sdk-ros, it works.

If we update both sdk to 3.4 or 3.5 we have NaN instead A3 voltage.

When we update to 3.6 - we get error "Vehicle initialization failed" during dji-sdk ros node start.

We hope that this problem will be fixed.

**Comment by rohitsantdji** [comment]
Do you still see the 3.6 "Vehicle initialization failed" error with the latest 3.6.1 release?

For the voltage, we'll look into it and if there is a fix to be made, we will roll it into our next release.

**Comment by OShapovalov** [comment]
Now we have NaN instead A3 voltage (with latest 3.6.1 release).

**Comment by OShapovalov** [comment]
Can we expect fix for this problem?

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
