### ISSUE TITLE
Qt Sample does not build on Ubuntu 16.04

### ISSUE THREAD

**Issue by MasonMoreland** [dji-sdk/Onboard-SDK#255]
Hello,

I am currently unable to get past all of the build errors in your build files. I have met all of the requirements, even rolling back g++ to 4.8. In the latest version, the file sample/Qt/djiosdk-qt-sample/djiosdk-qt-sample.pro is missing a \ character after the CMakeLists.txt line, for example. The directions at https://developer.dji.com/onboard-sdk/documentation/sample-doc/qt-sample.html do not work. Please test building the Qt sample to check if it works for you.

Thank you,
Mason

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
