### ISSUE TITLE
Ping2020i ADS-B Sensor Integration

### ISSUE THREAD

**Issue by wesleyd7** [dji-sdk/Onboard-SDK#261]
I am trying to integrate the uAvionix Ping2020i ADS-B Transceiver onto my M600 Pro Using the STM32 OSDK. When I look in the Onboard-SDK repository, there is only the example app in branch 3.1 and 3.2 and not in the most recent versions, When I open that sample project in uVision5, It tells me that it is a read only file and when I try to do anything in uVision, it says that path is incorrect for that file.

Please help with integrating this sensor.

Thanks

**Comment by rohitsantdji** [comment]
Hi @wesleyd7 the sample is no longer available for the newer SDK versions. For the older ones, we have had users use it without any issues before. Maybe you could try using the regular STM32 sample app from the 3.6(current) branch and tell us if you see the same issues? That will help us debug any problems there may be in your setup.

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
