### ISSUE TITLE
About gimbal control of ZenmuseXT

### ISSUE THREAD

**Issue by kabosulemon** [dji-sdk/Onboard-SDK#263]
We want to point the ZenmuseXT camera lens directly below.

<pre>
[HW] 
Drone: M600 
FC: A3 Pro 
Camera: ZenmuseXT 
Other: Lightbridge 2

[SW] 
OSDK 3.3.2 
</pre>

But,there is a problem. 
we set the following gimbalAngle parameter for setAngle().
We confirmed that this parameter works as expected with ZenmuseZ3.

<pre>
DJI::OSDK::Gimbal::AngleData gimbalAngle; 
gimbalAngle.roll = 0; 
gimbalAngle.pitch = -900; 
gimbalAngle.yaw = 0; 
gimbalAngle.duration = 20; 
gimbalAngle.mode |= 0; 
gimbalAngle.mode |= gimbal->isAbsolute; 
gimbalAngle.mode |= gimbal->yaw_cmd_ignore << 1; 
gimbalAngle.mode |= gimbal->roll_cmd_ignore << 2; 
gimbalAngle.mode |= gimbal->pitch_cmd_ignore << 3; 
</pre>

But,It did not work with the above param settings. 
Could you tell me the parameters of setAngle () which should be set to point the ZenmuseXT camera lens directly below?

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
