### ISSUE TITLE
Break line sporadically, M210 communicates with NVidia TX2 through serial port @ baud rate of 921600 with usb-serial adapter

### ISSUE THREAD

**Issue by wt70707** [dji-sdk/Onboard-SDK#264]
M210 drone communicates with NVidia TX2 through serial port @ baud rate 921600 using usb-serial adapter. We got about 200 ms freezing of the system sometime, it seems that the FCU resets the UART due to some timeout or bad data. And I also observed this when DJI Assistant 2 is used, as disconnection happens sporadically. I wonder how is the UART on the FCU deal with lost data and timeout.

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
