### ISSUE TITLE
AdvancedSensing, L57: Please make sure the connected drone is a M210 and firmware version is supported.

### ISSUE THREAD

**Issue by jonathan7** [dji-sdk/Onboard-SDK#265]
Advanced sensing isn't working for me with an M210, even in samples. 
Here is the error:
```
jj@jj-ThinkPad-T460:~/Downloads/Onboard-SDK/build/bin$ ./camera-stream-poll-sample ../../sample/linux/common/UserConfig.txt 
Please enter the type of camera stream you want to view
m: Main Camera
f: FPV  Camera
b: both Cameras
f
Read App ID
User Configuration read successfully. 


STATUS/1 @ init, L55: Attempting to open device /dev/ttyUSB0 with baudrate 230400...

STATUS/1 @ init, L65: ...Serial started successfully.

STATUS/1 @ parseDroneVersionInfo, L687: Device Serial No. = 095XE8X00201AV

STATUS/1 @ parseDroneVersionInfo, L689: Hardware = PM410

STATUS/1 @ parseDroneVersionInfo, L690: Firmware = 3.2.44.11

ERRORLOG/1 @ initVirtualRC, L1029: Virtual RC is not supported on this platform!

ERRORLOG/1 @ AdvancedSensing, L57: Please make sure the connected drone is a M210 and firmware version is supported.

ERRORLOG/1 @ activate, L1228: Unable to initialize some vehicle components!
STATUS/1 @ getErrorCodeMessage, L644: initVehicle
STATUS/1 @ getCommonErrorCodeMessage, L710: ACK_NO_RESPONSE_ERROR

STATUS/1 @ getErrorCodeMessage, L644: reset
STATUS/1 @ getCMDSetSubscribeMSG, L727: SUBSCRIBER_ILLEGAL_DATA_LENGTH
Vehicle not initialized, exiting.
```

Steps I took:
Setup:
On an Ubuntu 16.04 machine: 
1. cloned Onboard-SDK into a folder
2. Built with -DADVANCED_SENSING=ON (cd Onboard-SDK; mkdir build; cd build; cmake .. -DADVANCED_SENSING=ON; make)

Hardware:
1. Updated M210 to latest firmware version using DJI Assistant 2
2. Connected M210's serial Tx,Rx,Ground to Uart->USB, ttyUSB0. This setup works without advanced sensing, and appears to work with advanced sensing as well. 
3. Connected M210's USB port to my usb port. My laptop shows 'Wired Connection 2' as connected. 
	Interface: Ethernet (enp0s20f0u1), Hardware Address: EE:7E:EA:DF:17:AA, Driver: rndis_host, IP Address: 192.168.42.3, Broadcast Address: 192.168.42.255

Then, I run the sample as shown in the error log above. 
If advanced-sensing is not included, the same exact setup works fine, both for the samples and in ROS.

**Comment by SamuelWangDJI** [comment]
The advanced sensing binaries has been updated. Please delete the **advanced-sensing-x.x.x** folder inside osdk-core and recompile again. Thanks.
