### ISSUE TITLE
WAYPOINT_MISSION_DATA_NOT_ENOUGH running Mission Waypoint sample with RC off

### ISSUE THREAD

**Issue by adam3039** [dji-sdk/Onboard-SDK#266]
Curious if anyone has any insight into how I can avoid these errors when running sample scripts with the remote controller off. I had read in the documentation that with the onboard SDK, the remote controller wasn't necessary. My manifold has internet connection and can run scripts fine without DJI GO app running, but I still need the remote controller to be on.

Any insight is greatly appreciated.

**Comment by QRI-nashw** [comment]
This is something I'm curious about as well.

**Comment by jarednm** [comment]
Any update on this issue?

**Comment by prairieapps** [comment]
I haven't heard a peep, unfortunately.

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
