### ISSUE TITLE
can OSDK 3.6 run on Raspberry PI 3?

### ISSUE THREAD

**Issue by chesteryeum** [dji-sdk/Onboard-SDK#268]
Has anyone had any success running the latest OSDK on a Raspberry PI 3? I'm currently running 3.2 on a Raspberry PI 3 to communicate (Transparent Transmission) with a custom sensor mounted to an M600. I'd like to upgrade to the latest OSDK but unsure if this latest version will have issues.

**Comment by QRI-nashw** [comment]
Yes, it works fine.

**Comment by wesleyd7** [comment]
Can someone provide a step by step guide to build the OSDK on Raspberry Pi? I am kind of new to this. The system will run on a M600 Pro.

Thanks in advance.

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
