### ISSUE TITLE
Potential Code hangup when calling obtainCtrlAuthority(int timeout)

### ISSUE THREAD

**Issue by sharvashish** [dji-sdk/Onboard-SDK#271]
https://github.com/dji-sdk/Onboard-SDK/blob/3.6/osdk-core/api/src/dji_vehicle.cpp#L1836-L1840

ACK::ErrorCode
Vehicle::obtainCtrlAuthority(int timeout)
{
  ACK::ErrorCode ack;
  uint8_t        data = 1;

  protocolLayer->send(2, this->encrypt,
                      OpenProtocolCMD::CMDSet::Control::setControl, &data, 1,
                      500, 2, false, 0);

  ack = *(ACK::ErrorCode*)waitForACK(
    OpenProtocolCMD::CMDSet::Control::setControl, timeout);

  if (ack.data == OpenProtocolCMD::ErrorCode::ControlACK::SetControl::
  OBTAIN_CONTROL_IN_PROGRESS)
  {
    ack = this->obtainCtrlAuthority(timeout);
  }

  return ack;
}

In this function, 
 if (ack.data == OpenProtocolCMD::ErrorCode::ControlACK::SetControl::
  OBTAIN_CONTROL_IN_PROGRESS)
  {
    ack = this->obtainCtrlAuthority(timeout);
  }
might result into a potential code hangup. It might be possible that the condition remains always 'True'.
I am being able to replicate this scenario, when I am executing a mission via DJI GO app, and then I call this API. It simply does not respond till waypoint mission gets over.

Is it possible to limit the number of times this recursive loop gets called!

**Comment by rohitsantdji** [comment]
That's good feedback, we will fix this in the next release. However there is currently no short-term plan for a release so you might have to wait for about a month, perhaps a little more.

**Comment by ol-bones** [comment]
Is this fixed in 3.7?

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
