### ISSUE TITLE
SDK Failsafe missing in DJI Assistant 2 with M100

### ISSUE THREAD

**Issue by rocklinsuv** [dji-sdk/Onboard-SDK#274]
Hi there,

I've been playing with my M100 recently, and managed to use DJI Assistant 2 (both v1.1.6 and v1.2.0) with M100 firmware version 1.3.1.00 to tune the telemetry frequency. However, it seems that the "Enable SDK Failsafe" box is missing here:
![image](https://user-images.githubusercontent.com/7424627/37205416-afd2f726-23cf-11e8-8adc-8d5d6f82c28a.png)
No matter how I selected the action, it reset to nothing all the time. Is there anything I can do to fix this? Any help would be very much appreciated!

Cheers,

**Comment by rohitsantdji** [comment]
Unfortunately, SDK Failsafe action is not supported on M100.

**Comment by rocklinsuv** [comment]
I believe that flicking the switch from "F" to either "A" or "P" on the RC will terminate the SDK and re-enable manual control. Can this be considered as some sort of "Failsafe"? Correct me if I'm wrong, thanks!

**Comment by rohitsantdji** [comment]
The term "SDK Failsafe" is a little misleading - it actually means that when the RC is lost, and the drone enters failsafe mode, the SDK can take over. So what you mentioned is true, but it is a little different from the meaning of SDK Failsafe on our other aircraft.

**Comment by rocklinsuv** [comment]
Sure. At least there is a way to take back control when things go south for M100. That's all what I need. Thanks again for your help!

**Comment by QRI-nashw** [comment]
@rohitsantdji So using the M100, if you want to execute a pre-programmed mission with the SDK, you must have a connection to the RC? What would losing that connection mid-mission look like?
