### ISSUE TITLE
Shutdown notification

### ISSUE THREAD

**Issue by AutisticNinja** [dji-sdk/Onboard-SDK#277]
Is there any way to tell when the vehicle I'm communicating with via the onboard SDK is in the process of shutting down?  I would like to detect a shutdown condition so I can properly close any log files I might have running.

**Comment by rohitsantdji** [comment]
Currently there is no way to do this. That's good feedback, we will look into the feasibility but this will not be a short-term effort.

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
