### ISSUE TITLE
DJI Drone configuration for getting onboard video stream

### ISSUE THREAD

**Issue by rcabg** [dji-sdk/Onboard-SDK#280]
Hello,

I come from issue #260 . I'm trying to understand how getting video onboard works in order to apply computer vision algorithms. DJI Developer website looks confusing or contradictory sometimes as SDK is continualy updated. 

Correct me if I'm wrong, but as far as I know, these are the only possible configurations in order to get so:

- **M210 + Linux OnBoard Computer (TX2, Manifold upgraded to 16.04....)** -> "Advanced sensing (osdk 3.5+)" could be used. Resolution from main camera can be 1080p or 720p on video mode at 30 fps. Just Zenmuse x4s and Zenmuse x5s cameras work with this feature.

- **M100 + Manifold (no possible other linux pc)** -> Onboard-SDK-ROS 3.2 could be used. Resolution from main camera is 640x480 always. Just X3 camera works.

- **Rest of DJI drones (M600, ...):** so far no possible to get onboard video stream.

Am I right? Is there any other possibility for doing so? It would be great if you could throw some light on this topic in order to buy the correct configuration.

Thanks in advance.

**Comment by AutisticNinja** [comment]
Beware the M100 + Manifold combination is not well supported.

https://github.com/dji-sdk/Manifold-Cam

No meaningful commits in over 2 years.  Questions go unanswered.

I have never tried the M210 route, but it's probably you best option as I can say the other two don't work.

**Comment by rohitsantdji** [comment]
@rcabg that summary is correct, only exception being that the M100 + Manifold combination has a resolution of 1280x720. I apologize if the docs aren't clear on the overall camera support state.

**Comment by rcabg** [comment]
Thanks both for your fast reply. I think then M210 + TX2 is the most compatible option right now. 

I really encourage you to bring this feature to all your products. Apply vision algorithms onboard will make them really useful and reliable solutions, specially with A3/N3.

**Comment by CWOA** [comment]
Has anyone managed to get the M100 + X3 + JetsonTX2 to interface (i.e. receiving imagery onboard the TX2 in opencv or otherwise)? Is this impossible? If so, why?

**Comment by rcabg** [comment]
@CWOA As far as I know, M100 autopilot seems to have a specific port in order to transmit the video stream. Manifold includes this port (in fact there are two ports, a cam-in and cam-out). In contrast, M210 transmits the video stream through an USB port.  That's why I mentioned on my first post that M100 just works with Manifold in order to analyze video. 

No idea if there is any other way to make that works.

**Comment by CWOA** [comment]
@rcabg understood, thanks. Looks like I'm stuck as you can't purchase the Manifold anymore.. I will look into buying a third-party camera/gimbal setup.
Thanks for replying!

**Comment by rcabg** [comment]
@CWOA you're welcome. Actually I think Manifold is being discontinued since it can't be purchased on the official DJI website (at least in Spain), just in local providers that have them in store. Furthermore, it carries a TX1 module inside, less powerful than the current TX2.

So, if would have to integrate a M100 with a camera gimbal, I definitely would look into a third-party solution.

**Comment by mithunvarma** [comment]
@rcabg  manifold is actually nvidia tk1 way too past gen stuff 

does dji provide pin out for the camera gimbal cables from fc to manifold ?

**Comment by rcabg** [comment]
@mithunvarma no sure whether dji provides an "open protocol" in order to connect a third-party gimbal or vice-versa. So far, I haven't found a pin out or something similar. It would be interesting feature though.

**Comment by CWOA** [comment]
@mithunvarma I found this forum thread with pin details. Implementation details for obtaining/decoding the live camera feed are somewhat unclear - https://www.rcgroups.com/forums/showthread.php?2439038-Hacking-Inspire-camera-and-gimbal

**Comment by pavankumarbn** [comment]
Has any tried to control Matrice 100 Zen X3 camera gimbal using any HMD devices?

**Comment by azrimahanif** [comment]
Hi,

i just want to ask will M210 + Zenmuse Z30 work for Onboard SDK?

i tried to run the camera stream sample, the FPV camera work fine.
but when i run the main camera nothing happen. 

![main camera](https://user-images.githubusercontent.com/30805989/42741866-92f90b94-88e8-11e8-8045-97b045535874.PNG)


do you guys have any idea?
Thank you in advance

**Comment by rohitsantdji** [comment]
Z30 is not supported by OSDK at the moment. Currently, the only compatible cameras are the X4S, X5S and the XT2 thermal camera.

**Comment by arif-makhdzir** [comment]
Will Z30 be supported by OSDK soon? Because I really need this configuration. How abt m210 with X5S on gimbal I and Z30 gimbal II then both cameras take photo at the same time, or OSDK communicate with MSDK to innitiate trigger of Z30 on gimbal II? Thanks

**Comment by Asylbeck** [comment]
Hello,
I am confused about the ARM support for the Advanced SDK - on one of the [issues](https://github.com/dji-sdk/Onboard-SDK/issues/234) you mention that advanced SDK library doesn't have prebuilt ARM version and is not compatible with Raspberry pi.  On the other hand, on the OSDK website it says that Advanced Sensing works with TX2 - which is also ARM based system.  How does that work?  I have an odroid-xu4 and not able to compile the osdk with advanced sensing on it.

**Comment by Asylbeck** [comment]
Also I built the fpmmeg library from source on my Odroid and isntalled it.

**Comment by alejodosr** [comment]
Hi, 

I have tested the OSDK 3.8 with Ubuntu  16.04, and the only result  I get  when I run the `camera-stream-callback-sample ` with the `main_camera` (Zenmuse X4S) is:

![1](https://user-images.githubusercontent.com/3659632/58865468-e2dfd300-86b6-11e9-8f23-9c05afd32844.png)
![2](https://user-images.githubusercontent.com/3659632/58865474-e5422d00-86b6-11e9-8eea-96a035d0c5a7.png)

I don't know what else to do, since it is official OSDK with supported M210RTK V2 and Zenmuse X4S. I have tested the FPV and it works successfully.

Can anybody provide some help? Thank you in advance.

**Comment by pavankumarbn** [comment]
Alternative way,

I have tried to get Zenmuse X3 video feed (Mounted Matrice 100) on Windows computer using RTMP protocol and OBS (Also works on Linux). It worked perfectly fine for me. It broadcasts the video feed to a specific channel. You can get that access to use it for further applications using OpenCV.

**Comment by JavascriptAddict** [comment]
> Alternative way,
> 
> I have tried to get Zenmuse X3 video feed (Mounted Matrice 100) on Windows computer using RTMP protocol and OBS (Also works on Linux). It worked perfectly fine for me. It broadcasts the video feed to a specific channel. You can get that access to use it for further applications using OpenCV.

Hi, did you use the DJI Go app to create a custom stream to your computer?

**Comment by pavankumarbn** [comment]
> > Alternative way,
> > I have tried to get Zenmuse X3 video feed (Mounted Matrice 100) on Windows computer using RTMP protocol and OBS (Also works on Linux). It worked perfectly fine for me. It broadcasts the video feed to a specific channel. You can get that access to use it for further applications using OpenCV.
> 
> Hi, did you use the DJI Go app to create a custom stream to your computer?

@JavascriptAddict Yes, I used DJI Go app.

**Comment by huangzuliang** [comment]
> Hi,
> 
> I have tested the OSDK 3.8 with Ubuntu 16.04, and the only result I get when I run the `camera-stream-callback-sample ` with the `main_camera` (Zenmuse X4S) is:
> 
> ![1](https://user-images.githubusercontent.com/3659632/58865468-e2dfd300-86b6-11e9-8f23-9c05afd32844.png)
> ![2](https://user-images.githubusercontent.com/3659632/58865474-e5422d00-86b6-11e9-8eea-96a035d0c5a7.png)
> 
> I don't know what else to do, since it is official OSDK with supported M210RTK V2 and Zenmuse X4S. I have tested the FPV and it works successfully.
> 
> Can anybody provide some help? Thank you in advance.

@alejodosr You can run the sample with the following command. /dev/ttyACM0 is the USB device connected to aircraft, maybe different with this, you can use command ls /dev/ttyACM to check it.

bin/camera-stream-poll-sample UserConfig.txt /dev/ttyACM0
