### ISSUE TITLE
Precision Missions Issue in Compiling the SDK

### ISSUE THREAD

**Issue by afasc** [dji-sdk/Onboard-SDK#281]
I have a M600 Pro and I mounted a Velodyne Puck Lite on it.
I would like to perform LiDAR mapping as suggested on the guide given with the software: https://developer.dji.com/onboard-sdk/documentation/modules/lidarmapping/lidar-mapping.html
I downloaded the LOAM and Velodyne Packages, built them (with catkin_make) and sourced the setup.bash files.
I installed the djiosdk-core packages.
I then downloaded the DJI-OSDK-ROS package and compiled it with catkin_make -DUSE_POINTCLOUD2LAS=ON
It looks like the pointcloud2las option is not there. There is no difference in compiling the package with and without the option, and there is no "dji-ros-pointcloud2las" folder where the guide says it should be.
A similar problem also happens when compiling the Linux version of the SDK.
Anyone has had any luck performing Aerial Mapping with Velodyne products via the Onboard SDK?

PS: I'm working with Onboard SDK version 3.6.

**Comment by rohitsantdji** [comment]
Hi @afasc , the Pointcloud2las module is deprecated since OSDK 3.2, more than a year ago. We currently have no plans to support it for new versions of the OSDK.
