### ISSUE TITLE
Try to control flight of the M600 using Dji sdk, it stops at hovering

### ISSUE THREAD

**Issue by F-Ohashi** [dji-sdk/Onboard-SDK#283]
I installed RaspberryPi3 on Matrice600Pro and installed a software using Dji SDK and built a system to control flight.
I communicate with PC and RaspberryPi with wifi and we send operation information of game controller connected to PC to RaspberryPi.
Based on its operation information, RaspberryPi is designed to make it fly by giving speed to the Matrice600Pro via OSDK.
ROS is used for these systems.

After successfully executing TakeOff, operations from the game controller may not be abruptly accepted after a few seconds of flight.
In that case, DisplayMode was "P-GPS" from "joy stick".
In this state, it can be operated only with Remote Controller.
From the PC, the operation information of the game controller has reached RaspberryPi 3, and it is confirmed that using the API giving the speed with OSDK.
In addition, when OSDK 3.6 is used, this phenomenon occurs while not using the Dji Go application, and currently does not occur while using Dji Go.
(This phenomenon occurred even when using Dji Go before OSDK 3.5)
This phenomenon does not occur when this system is applied to M100.

Please tell me the cause of this phenomenon.

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
