### ISSUE TITLE
Drone version not obtained with M100 ubuntu 16.04

### ISSUE THREAD

**Issue by Gerjen100** [dji-sdk/Onboard-SDK#284]
I have been trying to get any of the sample programs to work with the Matrice M100 but whenever i try to to run the sample program it runs into a communication error where the drone version cannot be obtained. It worked the first time and after that the output is always the same error.

<img width="400" alt="serial communication failed crop" src="https://user-images.githubusercontent.com/6671867/38094183-673e7b9a-336d-11e8-9a17-da6e9a6a7bd9.png">

I am using a usb to TTL cable so in combination with an intel NUC. The firmware on the matrice is up to date. I have tried all of the suggestions the program makes to solve this issue but it does not seem to work. Can anyone tell me a possible source for this problem.

Kind Regards Gerjen

**Comment by rohitsantdji** [comment]
Can you post a screenshot of the DJI Assistant 2 SDK page, as well as a picture of your UART connections?

**Comment by Gerjen100** [comment]
Here are my DJI assistant settings  : 

<img width="813" alt="dji assistant" src="https://user-images.githubusercontent.com/6671867/38235403-5fa34f34-3721-11e8-80d7-f85dc629b353.PNG">

And here is a picture of my UART connections
![image](https://user-images.githubusercontent.com/6671867/38235879-e199d91c-3722-11e8-9df5-7d94e1464890.png)

And here is my Userconfig.txt
<img width="346" alt="userconfig settings" src="https://user-images.githubusercontent.com/6671867/38236391-4a6e1592-3724-11e8-8763-a59a022e3985.png">

**Comment by rohitsantdji** [comment]
Do you happen to know the model of the USB-Serial converter chip inside your cable? Also, just to confirm, did you try inverting the Rx/Tx pins?

**Comment by Gerjen100** [comment]
The issue randomly disappeared over night. We're not sure why but it is working now.
