### ISSUE TITLE
Load all Waypoints with DJI N3 failed : WAYPOINT_MISSION_DATA_NOT_ENOUGH

### ISSUE THREAD

**Issue by cynapoleon** [dji-sdk/Onboard-SDK#285]
After setting Waypoints , I want to upload all points to DJI N3, but it failed. There is a note that WAYPOINT_MISSION_DATA_NOT_ENOUGH , as the picture shows.
![2018-04-02_16-44-46](https://user-images.githubusercontent.com/37980060/38190122-6edd170a-3695-11e8-8541-bc7e5a67468b.jpg)

Please tell me how to upload  waypoints to DJI N3 , and which parameter I should add.
Thanks a lot.

**Comment by rohitsantdji** [comment]
Can you take us through the steps you did to get to this point?

**Comment by jarednm** [comment]
Any update on this?  I'm having the same issue

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
