### ISSUE TITLE
Ubuntu - Getting Camera Stream on M210 using OSDK

### ISSUE THREAD

**Issue by trungnmh90** [dji-sdk/Onboard-SDK#289]
I went through your example for live camera stream and advance sensing, and I faced a problem like below image
![image](https://user-images.githubusercontent.com/11627415/38456645-1b82eb64-3ab1-11e8-8c4d-87f1c1988d0b.png)
have gone through the `checklist` here: https://developer.dji.com/onboard-sdk/documentation/M210-Docs/oes-checklist.html. And confirm every step is completed.
![image](https://user-images.githubusercontent.com/11627415/38456661-3e2f7dee-3ab1-11e8-9abb-b91f4d988ffd.png)
The USB cable I am using is the one came with my Matrice 210 purchasing package, and my Linux box recognized the USB cable as below:
![image](https://user-images.githubusercontent.com/11627415/38456668-4e92968a-3ab1-11e8-9db1-1b7b1e119529.png)
Both camera: FPV and Main Camera are confirmed working fine on DJI GO application on my tablet. I can see both streaming video on the DJI GO.

Still, the sample of the SDK is failed to run. Can you help me to point out where have been wrong, any more steps to check the hardware, and how can make SDK’s sample works?

**Comment by zliDJI** [comment]
When you connect the M210 to your linux computer through usb cable, do you get a notification on linux saying a new network interface was established?

**Comment by trungnmh90** [comment]
Yes, there is a new network interface in my box when I plugged in the cable
![image](https://user-images.githubusercontent.com/11627415/38532571-a6536fa8-3c9f-11e8-8d63-2d24c09e14cf.png)

Will try to reboot to see it will help

**Comment by rohitsantdji** [comment]
From your screenshot it appears that your computer is not getting assigned an IP address on the USB ethernet connection. You should be receiving a 192.168.42.3 IP on your `enp0s20u1` interface. Can you try the sample after manually assigning this IP to your interface through Ubuntu's network settings? Set the subnet mask to 255.255.255.0 and the default gateway to 192.168.42.1.

**Comment by azrimahanif** [comment]
Hi, i also having the same issue. i run the camera-gimbal sample and it's been working fine. 
thus this mean i should not have any USB issue right??

![camera failed](https://user-images.githubusercontent.com/30805989/42621025-2dbfc2fa-85ef-11e8-85cf-65bff333fc48.PNG)

do you guys have any idea?
thank you in advance.

**Comment by changmsdn** [comment]
Thanks a lot! that works for me.

> From your screenshot it appears that your computer is not getting assigned an IP address on the USB ethernet connection. You should be receiving a 192.168.42.3 IP on your `enp0s20u1` interface. Can you try the sample after manually assigning this IP to your interface through Ubuntu's network settings? Set the subnet mask to 255.255.255.0 and the default gateway to 192.168.42.1.

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
