### ISSUE TITLE
OSDK - Matrice 210 - Waypoint Mission weird behavior 

### ISSUE THREAD

**Issue by trungnmh90** [dji-sdk/Onboard-SDK#291]
I am using simulator on DJI Assisstant 2 to work with waypoints-mission on the drone. And experienced strange behaviors related to `STOP` command:
`vehicle->missionManager->wpMission->stop(responseTimeout)`

1. Call `STOP` before mission initiating will cause Segment Fault.
2. Once the drone **has finished** a mission, and the it is hovering in the mid air, then I call `STOP`, it prints out this error:
`STATUS/1 @ getCMDSetMissionMSG, L871: MISSION_IN_PROGRESS`
After that, I will no longer can init new mission again, but have to land the drone/ RTH and do mission initiating on the ground.
However, this error will not occurs if the drone is **currently on a mission**, then calling `STOP` will not show previous error string, and the drone will discard current mission, and I can start new mission in the mid air.
Why is that? 

Also, it would be nice if there is a way to see the general status of missions on the drone.

**Comment by trungnmh90** [comment]
1. I did call STOP before initializing  because the SDK has no interface for reading whether the drone is on current any mission or not; but since it will cause problem for calling 'blinding stop', so I have to keep track the sequence call myself.

 2. Update the scenario: when the drone finished the previous mission, calling `STOP` and it will print `MISSION_IN_PROGRESS`. But I actually **can** init new mission, it was my error in my sequence call earlier.

So I figure out a work around by having a separated thread for checking the speed and drone position to update myself the current status of  the drone on missions, by that I can determine whether should I call `STOP` or not. Still, if the SDK have a way to read that status, it will be better.

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
