### ISSUE TITLE
Reading flight controller IO

### ISSUE THREAD

**Issue by AutisticNinja** [dji-sdk/Onboard-SDK#294]
I would like to be able to read the values coming out of the flight controller F1-F8 pins on an M600 without using a microcontroller to time the PWM.  Initially I thought that MFIO would support this, but this seems to only be useful for setting a PWM output value, reading/writing GPIO value, and reading ADC values.  Initially I hoped that I could use MODE_PWM_IN and jump one a channel assigned to SDKX to another channel but it seems that PWM_IN is not yet supported.  

I have the M600 channel expander and want to make the values of some (not all) of the buttons/switches known to the device communicating with the onboard sdk.  Is there a way to do this?

Also, I want to know when the shutter button on the controller is pressed.  Is there a way to do this?

Side note:  I setup the F3 pin to be "shutter".  It operates when the shutter button is RELEASED, not when it is pressed.

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
