### ISSUE TITLE
TOPIC_GPS_TIME is not accurate

### ISSUE THREAD

**Issue by sdo91** [dji-sdk/Onboard-SDK#295]
I am interested in getting the GPS time from an m600 aircraft, however the TOPIC_GPS_TIME does not appear to be accurate. 

The following log file shows the issue. I subscribed to TOPIC_GPS_TIME and log out when the published value changes (which I expect to be when the GPS clock changes from one second to the next). `numSinceNew` counts the number of times the previous value was published.

```
[ INFO] [1523898896.712924981]: new TOPIC_GPS_TIME value: 171457 (numSinceNew=39)
[ INFO] [1523898897.705634518]: new TOPIC_GPS_TIME value: 171458 (numSinceNew=48)
[ INFO] [1523898898.705400022]: new TOPIC_GPS_TIME value: 171459 (numSinceNew=50)
[ INFO] [1523898899.706173072]: new TOPIC_GPS_TIME value: 171500 (numSinceNew=50)
[ INFO] [1523898900.705953665]: new TOPIC_GPS_TIME value: 171501 (numSinceNew=50)
[ INFO] [1523898901.705688093]: new TOPIC_GPS_TIME value: 171502 (numSinceNew=50)
[ INFO] [1523898902.906256644]: new TOPIC_GPS_TIME value: 171503 (numSinceNew=60)
[ INFO] [1523898903.905959197]: new TOPIC_GPS_TIME value: 171504 (numSinceNew=50)
[ INFO] [1523898904.707398511]: new TOPIC_GPS_TIME value: 171505 (numSinceNew=40)
[ INFO] [1523898905.906288757]: new TOPIC_GPS_TIME value: 171506 (numSinceNew=60)
[ INFO] [1523898906.706344426]: new TOPIC_GPS_TIME value: 171507 (numSinceNew=40)
[ INFO] [1523898907.906793548]: new TOPIC_GPS_TIME value: 171508 (numSinceNew=60)
[ INFO] [1523898908.906517651]: new TOPIC_GPS_TIME value: 171509 (numSinceNew=50)
[ INFO] [1523898909.726592312]: new TOPIC_GPS_TIME value: 171510 (numSinceNew=41)
[ INFO] [1523898910.707561653]: new TOPIC_GPS_TIME value: 171511 (numSinceNew=49)
[ INFO] [1523898911.906758746]: new TOPIC_GPS_TIME value: 171512 (numSinceNew=60)
[ INFO] [1523898912.706752188]: new TOPIC_GPS_TIME value: 171513 (numSinceNew=40)
[ INFO] [1523898913.707484749]: new TOPIC_GPS_TIME value: 171514 (numSinceNew=50)
[ INFO] [1523898914.906847011]: new TOPIC_GPS_TIME value: 171515 (numSinceNew=60)
[ INFO] [1523898915.707474536]: new TOPIC_GPS_TIME value: 171516 (numSinceNew=40)
[ INFO] [1523898916.907297013]: new TOPIC_GPS_TIME value: 171517 (numSinceNew=60)
[ INFO] [1523898917.908104351]: new TOPIC_GPS_TIME value: 171518 (numSinceNew=50)
[ INFO] [1523898918.907704538]: new TOPIC_GPS_TIME value: 171519 (numSinceNew=50)
[ INFO] [1523898919.907384490]: new TOPIC_GPS_TIME value: 171520 (numSinceNew=50)
[ INFO] [1523898920.708278911]: new TOPIC_GPS_TIME value: 171521 (numSinceNew=40)
[ INFO] [1523898921.708056179]: new TOPIC_GPS_TIME value: 171522 (numSinceNew=50)
[ INFO] [1523898922.707815546]: new TOPIC_GPS_TIME value: 171523 (numSinceNew=50)
[ INFO] [1523898923.708469629]: new TOPIC_GPS_TIME value: 171524 (numSinceNew=50)
[ INFO] [1523898924.908053010]: new TOPIC_GPS_TIME value: 171525 (numSinceNew=60)
[ INFO] [1523898925.907817503]: new TOPIC_GPS_TIME value: 171526 (numSinceNew=50)
[ INFO] [1523898926.707873422]: new TOPIC_GPS_TIME value: 171527 (numSinceNew=40)
[ INFO] [1523898927.708642059]: new TOPIC_GPS_TIME value: 171528 (numSinceNew=50)
```

Note how the log statements are not spaced evenly apart. The topic publishes at 50 hz, so I expect `numSinceNew` to always be close to 50. However, it seems to bounce around between 40, 50 and 60 (give or take a few). The TOPIC_GPS_TIME value seems to change either at the .7 or .9 second mark. And neither time value seems to be an accurate representation of actual GPS time.

I have tried this on multiple m600 aircraft, and have seen similar results on each one. The time of the log statements always seems to bounce between 2 values about 0.2 seconds apart.

**Comment by mithunvarma** [comment]
Idk how dji filtered gps fused gps works but a regular Gps works at 1 hz signal, even if you listen to all gnss like gps Galileo glonass, the max update rate is 5 hz.

So dji fuses compass/magnetometer with Gps and publishes fused signal at 50 hz which is mainly atttitude data at 50 hz and gnss data is filtered and published at same rate. 

I think That’s the reason why you might get time stamp at either 5hz (0.2 s) or near to 1 hz

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
