### ISSUE TITLE
Modify wayppoint in flight

### ISSUE THREAD

**Issue by estsantre** [dji-sdk/Onboard-SDK#297]
Hi, 

I am working with a Matrice 600 Pro, using the Onboard-SDK v3.2.

The drone has to go to a given location and once it arrives, measure the height it is at (using a LiDAR sensor) and according to this value, go down to exactly 10m. This can not be predefined, because the destination changes constantly and independent of the elevation of the terrain, the drone must go down to 10m. 

Can I modify the waypoint according to the measured data?

Thank you.

**Comment by rohitsantdji** [comment]
This is not possible right now. Please submit is as a feature request in #233!
