### ISSUE TITLE
Create a custom action on waypoint

### ISSUE THREAD

**Issue by estsantre** [dji-sdk/Onboard-SDK#298]
Hi, 

Is it possible to create a new action? or modify any of the existing ones? I am using the Onboard-SDK v3.2

![screenshot from 2018-04-16 20-54-37](https://user-images.githubusercontent.com/24708136/38846281-dfb866ea-41b8-11e8-83ea-3038bfe3db2f.png)

**Comment by rohitsantdji** [comment]
For now, this is not possible. Please submit this as a feature request on #233 !
