### ISSUE TITLE
problem at startup rosrun dji_sdk_demo demo_flight_control. Obtain control failed

### ISSUE THREAD

**Issue by TheDimosha** [dji-sdk/Onboard-SDK#305]
Hello! I have a problem at startup rosrun dji_sdk_demo demo_flight_control. Code error :

[ERROR] [1524150661.255580389]: obtain control failed!
[ INFO] [1524150661.280840800]: M100 taking off!
[ERROR] [1524150661.315048332]: takeoff_land fail

Thanks for any comments!

**Comment by rohitsantdji** [comment]
What is the position of your mode switch (P--A--F, top left corner of the RC)? Are you activated successfully?

**Comment by TheDimosha** [comment]
A - mode
http://imglink.ru/show-image.php?id=55f6b10f12a8af6d847dbc1b33fabded

**Comment by rohitsantdji** [comment]
You need to be in F mode to obtain control for M100.
