### ISSUE TITLE
What's TOPIC_STATUS_MOTOR_START_ERROR?

### ISSUE THREAD

**Issue by maciekd** [dji-sdk/Onboard-SDK#306]
Hi,

Can't find any documentation as to what TOPIC_STATUS_MOTOR_START_ERROR is?

**Comment by rohitsantdji** [comment]
These are documented elsewhere since they are part of acknowledgements as well - find some docs [here](https://developer.dji.com/onboard-api-reference/classDJI_1_1OSDK_1_1ErrorCode_1_1CommonACK.html).
