### ISSUE TITLE
Write exif data into the image 

### ISSUE THREAD

**Issue by imkhairulikhwan** [dji-sdk/Onboard-SDK#307]
Hi and good day, 

I am using M210 to access OnBoard SDK using Qt sample.

I tried to look around the forum and the documentation, and it seems not raised yet. I would like to use OnBoard SDK to write exif data e.g. distance from the object into the image. 

Hence, I need to access the image from SD card and write the exif data into the image. Or maybe override taking photo function? 

However, from this link: https://developer.dji.com/onboard-sdk/documentation/guides/component-guide-camera-and-gimbal.html

it seems I am not able to access Media Manager through the sdk. Is there any way? Besides using Mobile SDK. 

Thank you!

**Comment by rohitsantdji** [comment]
Unfortunately at this time we don't support managing/manipulating images through the Onboard SDK.

**Comment by imkhairulikhwan** [comment]
Noted on that, thank you for the confirmation.

**Comment by OlegJakushkin** [comment]
It is now 2025, is this feature supported?
