### ISSUE TITLE
Possible bug in vehicle->control->land(timeout)

### ISSUE THREAD

**Issue by libo456** [dji-sdk/Onboard-SDK#310]
Dear all,
I am using OSDK 3.6. My situation is as follows:
1. I run `vehicle->obtainCtrlAuthority(functionTimeout)` and no error is gotten.
2. I `call vehicle->control->land(timeout)`. In the first try it works, but the next time I run the algorithm, land() produces the following error:
```
STATUS/1 @ getErrorCodeMessage, L644: monitoredLanding
STATUS/1 @ getCMDIDSetControlMSG, L788: OBTAIN_CONTROL_SUCCESS
```
I assume that L644 is telling me the name of the function from which I called land(), but I don't understand L788, I have tried to trace back the files from the API to see what it means but I got nothing. Could you please tell me what that error means?
3. In order to actually land when the above error is obtained, I have to re-call `vehicle->control->land(timeout)`, which then does work.

Number 2 and 3 are implemented as follows:

```
ACK::ErrorCode landingStatus = vehicle->control->land(timeout);
if (ACK::getError(landingStatus) != ACK::SUCCESS)
{
   std::cout << "\033[1;31m Error after vechicle->control->land() request.\033[0m\n";
   ACK::getErrorCodeMessage(landingStatus, __func__);
   
   std::cout << "Re-trying\n";
   landingStatus = vehicle->control->land(timeout);
    
   if (ACK::getError(landingStatus) != ACK::SUCCESS)
  {
     std::cout << "\033[1;31m Error after vechicle->control->land() request AGAIN!.\033[0m\n";
     ACK::getErrorCodeMessage(landingStatus, __func__);
     return false;
  }
}
```

This cycle keeps repeating, in other words: it works, it does not, it works, it does not, and so on...
It would be nice if you could please help me out with this issue. I consider my solution not to be the best.

**Comment by rohitsantdji** [comment]
Are you using M100?

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
