### ISSUE TITLE
Issue with setup

### ISSUE THREAD

**Issue by johnnyapplesed** [dji-sdk/Onboard-SDK#312]
I'm getting this error trying to follow the instructions in the SDK guide:

CMake Error: The source directory "C:/Users/john/Downloads/Onboard-SDK-3.6" does not appear to contain CMakeLists.txt.

**Comment by imkhairulikhwan** [comment]
You need to create another directory named 'build' inside the SDK folder, as stated in the instructions:

https://developer.dji.com/onboard-sdk/documentation/sample-doc/sample-setup.html

mkdir build
cd build
cmake ..
make

**Comment by johnnyapplesed** [comment]
Sorry, I should have included the line directly above:

C:\Users\john\Downloads\Onboard-SDK-3.6\build>cmake ..
CMake Error: The source directory "C:/Users/john/Downloads/Onboard-SDK-3.6" does not appear to contain CMakeLists.txt.

**Comment by imkhairulikhwan** [comment]
I see, you have already created the build folder. But it seems you are using Windows OS? The cmake parameters might differ from Linux I guess, as it seems can't recognise the folder to when executing cmake.

**Comment by johnnyapplesed** [comment]
Right, I'm using Windows. What steps should I take instead of the ones I've been trying?

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
