### ISSUE TITLE
L1190: Unable to initialize some vehicle components

### ISSUE THREAD

**Issue by giueppo** [dji-sdk/Onboard-SDK#313]
Just started, i'm a very beginner.
I connected STM32 to M600 and I want to start playing with it.
The code is running (I get succesfull inizialization of STM32. I connected the hardware and i get something written on USART3 (I checked with a TTL-USB cable).
However, no response from the drone I get error L1190.
In the same script from docklight (for writing on the serial) i tried to send to command: FA FB 00 FE for getting the version. No response at all.
What can I do to check if I'm doing things in a good way?
Thanks.

**Comment by rohitsantdji** [comment]
Can you post the output of the initialization?

**Comment by giueppo** [comment]
Just yesterday evening I solved and I was able to launch one example.
There were some mistakes in changing from Nucleo STM32 board (instead of the STM32Discovery!). So I am using now USART6 rather than USART3.
Thank you! I will continue working and come back with other issues if there are!
