### ISSUE TITLE
Serial UART communication lagging sometimes

### ISSUE THREAD

**Issue by maciekd** [dji-sdk/Onboard-SDK#315]
Hi,

We're having an issue with the serial communication. Our system is very precise and we need a very stable, very fast connection to the A3.

We measure the number of new data-frames we get from the A3. Sometimes things work perfectly, in that case the data frame-rate from the A3 is a solid 60fps:
https://www.dropbox.com/s/mc8swy9hq6nxrl1/Screen%20Shot%202018-04-27%20at%2016.52.28.png?dl=0

But other times the communication is lagging and we get results like this:
https://www.dropbox.com/s/77gk78gl8xhux0l/IMAGE%202018-05-02%2010%3A43%3A21.jpg?dl=0

or like this:
https://www.dropbox.com/s/0wfgu9mrni8ru4w/IMAGE%202018-05-07%2022%3A51%3A58.jpg?dl=0

Both are very bad for us and the high precision control system becomes unstable.

We're running on an Intel NUC using the serial cable recommended in the DJI docs.

Is this a known problem? Do you maybe have any tips on what we could try to fix it?

**Comment by rohitsantdji** [comment]
This can happen when there is a lot of throughput on the line - is your program doing a large amount of Tx/Rx on the serial line with respect to the baud rate configured? Also, are you using broadcast or subscription telemetry? If subscription, can you confirm that your broadcast frequencies are tuned to very low values?

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
