### ISSUE TITLE
Failing to run flight-control-sample 

### ISSUE THREAD

**Issue by SkullPirateTK** [dji-sdk/Onboard-SDK#318]
After selecting 'a' or 'b', I get the following errors and nothing happens in the simulator.

For option 'a':
`STATUS/1 @ activate, L1252: Activation successful`
`| Available commands:                                            |`
`| [a] Monitored Takeoff + Landing                                |`
`| [b] Monitored Takeoff + Position Control + Landing             |`
`$a`
` `
`STATUS/1 @ getErrorCodeMessage, L644: P-�`
`STATUS/1 @ getCMDIDTaskMSG, L824: CONTROLLER_FAIL`
` `
`STATUS/1 @ getErrorCodeMessage, L644: P-�`
`STATUS/1 @ getCMDIDTaskMSG, L824: CONTROLLER_FAIL`

For option 'b':
`STATUS/1 @ activate, L1252: Activation successful`
`| Available commands:                                            |`
`| [a] Monitored Takeoff + Landing                                |`
`| [b] Monitored Takeoff + Position Control + Landing             |`
`$b`
` `
`STATUS/1 @ getErrorCodeMessage, L644: ����`
`STATUS/1 @ getCMDIDTaskMSG, L824: CONTROLLER_FAIL`
`Task timeout!`
`Task timeout!`
`Task timeout!`
` `
`STATUS/1 @ getErrorCodeMessage, L644: ����`
`STATUS/1 @ getCMDIDTaskMSG, L824: CONTROLLER_FAIL`

Any clue?

**Comment by Meowster808** [comment]
is your controller mode set to F?

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
