### ISSUE TITLE
Matrice 100 will not activate

### ISSUE THREAD

**Issue by tkocik92** [dji-sdk/Onboard-SDK#321]
Hello

I am experiencing the issue described here: https://github.com/dji-sdk/Onboard-SDK-ROS/issues/109. However, I am not using ROS.

I am using a Linux laptop to act as the "onboard" computer. I am following the tutorial outlined here: https://developer.dji.com/onboard-sdk/documentation/quick-start/quick-start.html

When I originally ran the command `./djiosdk-flightcontrol-sample ../../sample/linux/common/UserConfig.txt`, the Matrice was not activated. I opened up the DJI Go app on an iPhone and successfully activated the Matrice. However, the output has not changed. I power cycled the Matrice and its controller to no effect. I restarted the DJI Go app as well, but no new activation prompt appears.

I verified that I am using the latest version of DJI Go. Firmware is up-to-date for the Matrice and controller.

Any help would be appreciated.

**Comment by ZeeshanShabbir** [comment]
Did you resolve this issue? I am also facing the same issue

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
