### ISSUE TITLE
Flying indoor with no GPS signal

### ISSUE THREAD

**Issue by rcabg** [dji-sdk/Onboard-SDK#322]
Hello,

we are interested in flying our M210 indoor using a VICON system that gives us the drone position with high precision. Reading the documentation we see that is no way to feed that position back since the autopilot just tries to read GPS. Is there any way to do that? 

Also, another possibility we have been thinking is faking somehow the GPS signal the autopilot reads. Probably connecting a PC via pins-in where the external M210 GPS module is connected. Is that pin connection and GPS data sending protocol available? Is it that even possible?

Thanks in advance!

**Comment by MI-LA01** [comment]
I'm interested about this topic. Did You finally found an answer ?

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.

**Comment by Alessandro111111** [comment]
Hello,

We have developed a third party software that is able to provide informations about position, attitude and velocities of the system where it is installed on, without use of GPS data provided. For flying in GPS-denied environments we want to provide position data from this other source to the flight controller via DJI Onboard SDK, and make the flight controller know its current position (we can provide also attitude, velocities and angular velocities). In summary, we want to replace the informations provided from GPS when this is not available. Is there any way to do this?
