### ISSUE TITLE
TX1——M100——Onboard-SDK 3.6: "Drone version not obtained"

### ISSUE THREAD

**Issue by menzehua** [dji-sdk/Onboard-SDK#326]
I met a problem similar to the question #317 
I use jetson tx1 to run onboardsdk to communicate between TX1 and M100,I use a USB to TTL device: "FT232".but it I've encountered multiple times with an error that says "Drone version not obtained! Please do not proceed."
                     os of  TX1: 32bit ubuntu 14.04(also have tried on pc)
M100 firmware version:  1.3.1.00
I  can monitor the serial port and saw data coming in through a serial software installed onTX1.when I enable the SDK API on the DJI Assistant 2 software,so I think the hardware connection is correct.
I kept the connection between the M100 with remote,the  remote with djigo all the time, the remote is in "F"mode.
the baud rate in the  DJI Assistant 2 software and the UserConfig.txt are the same,I have constructed a new sdk app on dji sdk web and app ID and app key are correctly wrote into the UserConfig.txt file.

any help or suggestion will be appreciate!!!

![webwxgetmsgimg](https://user-images.githubusercontent.com/15624410/40832695-7999131c-65be-11e8-894f-3ef8c0379ec6.jpg)

**Comment by rohitsantdji** [comment]
Can you try to connect the Jetson TX1 to the M100 through a native serial port? That can help isolate any problems the OSDK's serial driver might have with the FT232 chip.
