### ISSUE TITLE
How to install Veloview and set up PCL environment on Manifold 

### ISSUE THREAD

**Issue by pavankumarbn** [dji-sdk/Onboard-SDK#327]
I am trying to set-up similar https://developer.dji.com/onboard-sdk/documentation/sensor-integration-guides/velodyne/readme.html (https://developer.dji.com/onboard-sdk/documentation/sensor-integration-guides/velodyne/readme.html) model. But, using Manifold, But I have been facing problems in setting PCL environment and also in installing VeloView software. I wanted to know is this recommended to install or set up PCL n Manifold or not? can I install Ubuntu 14.04 LTS on Manifold?

Can you please suggest how to fix this issue

**Comment by rohitsantdji** [comment]
This guide is not supported anymore. Ubuntu 14.04 LTS is already installed on Manifold.
