### ISSUE TITLE
Could you provide an RC lost indicator?

### ISSUE THREAD

**Issue by dunk-emesent** [dji-sdk/Onboard-SDK#328]
Could you provide an 'RC signal lost' indicator? Currently, there is no explicit mechanism to determine when the RC signal has been lost, so we resort to some heuristics; this has the potential to be a fragile approach.

From previous discussions, I believe this is on your radar, so I'm just raising it here so we can track it.

**Comment by rohitsantdji** [comment]
This feature will be available in OSDK 3.7. M600 will need a firmware update to enable these data streams, which will come at a later date.

**Comment by dunk-emesent** [comment]
Thanks Rohit

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
