### ISSUE TITLE
display_mode flag to indicate controller in OSDK failsafe mode

### ISSUE THREAD

**Issue by dunk-emesent** [dji-sdk/Onboard-SDK#329]
Currently, there is no way of knowing when the controller has entered OSDK failsafe mode. Could you provide a mechanism to indicate when this has happend? This would be a very useful feature to assist in failure recovery.

More specifically, if we have a fault on our end which results in us not sending a control command for a long period, the controller will enter OSDK failsafe mode. In this case, display_mode stays at MODE_NAVI_SDK_CTRL, so we have no idea what has happened. Because we fly autonomously, we have fairly extensive fault handling, and would like to recover in this situation.

 A possible solution would be to add a new display_mode flag.

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
