### ISSUE TITLE
Could you provide controller throttle values in telemetry?

### ISSUE THREAD

**Issue by dunk-emesent** [dji-sdk/Onboard-SDK#330]
We would like to have access to the throttle values being used by the controller (in all DJI modes) so that when we switch to API mode during flight, we can correctly initialise the values we are applying.

Currently, we use a nominal throttle setting initially, however the correct value for this will vary depending on air pressure, payload weight, etc. So, the drone is likely to climb/descend when switching to API mode. This is a problem for us, as we often fly in tight indoor spaces.

**Comment by rohitsantdji** [comment]
Onboard SDK 3.7 will have this data telemetry available.

**Comment by dunk-emesent** [comment]
Great, thanks Rohit

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
