### ISSUE TITLE
Simulator changes to facilitate testing in GPS denied environments 

### ISSUE THREAD

**Issue by dunk-emesent** [dji-sdk/Onboard-SDK#332]
Would it be possible to have the HIL simulator modified to facilitate testing in GPS denied environments?

The type of changes I'm thinking would include running a simulation session with no GPS signal present, or running simulation sessions where the GPS signal can be manually enabled / disabled (more fine-grained adjustment would be handier so we could vary the quality of the solution).

I know you guys aren't directly responsible for the simulator, but AFAIK this is the only avenue open for us to submit such requests.

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
