### ISSUE TITLE
Issues related to controller taking control at/near GeoFence boundaries

### ISSUE THREAD

**Issue by dunk-emesent** [dji-sdk/Onboard-SDK#333]
We're trying to avoid situations where a pilot may be flying our system near a GeoFence, and control is unexpectedly taken back by the A3 controller.

We've found that when we're flying under SDK control, the controller will take back control when it hits a GeoFence. This raises a few questions;
- How near do we have to be to the GeoFence before the controller takes back control? 
    - We've noticed that there seems to be some hysterisis in this - i.e. the controller takes control when we get close to a fence, but we have to move back further from it before our control commands take effect again. The distances also seem a little bit inconsistent.
- Could a mechanism be added to indicate that the controller has taken back control because of proximity to a GeoFence?

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
