### ISSUE TITLE
Configuration mechanism for OSDK failsafe can be dangerous

### ISSUE THREAD

**Issue by dunk-emesent** [dji-sdk/Onboard-SDK#334]
We've noticed that if a the OSDK failsafe mechanism is enabled, the OSDK failsafe action will be used even when the drone is not running under SDK control. 

E.g.
- OSDK failsafe is enabled, and set to 'hover' (configured using the DJI Assistant)
- DJI Go failsafe is set to 'return to home'
- Even without our payload connected (so the drone is not under SDK control at any stage after power-on), the failsafe behaviour of the drone will be 'hover'

This behaviour can result in dangerous situations, especially as DJI Go is the interface a pilot is likely to be using.

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
