### ISSUE TITLE
RC loss + recovery can leave the drone stuck in OSDK failsafe

### ISSUE THREAD

**Issue by dunk-emesent** [dji-sdk/Onboard-SDK#335]
After the following sequence of events, the controller ends up stuck in OSDK failsafe mode;
1. RC switch in F position
2. We have control authority
3. RC loss
4. Pilot flicks switch to A position
5. RC recovery

After this sequence of events, display_mode == MODE_NAVI_SDK_CTRL, however the controller isn't accepting control commands. So, the drone is NOT in attitude mode, it behaves according to the OSDK failsafe setting (presumably it's in OSDK failsafe mode).

Subsequent control authority requests at this time fail (can't remember if we switched back to F mode for these - presumably we did), even if we explicitly release control authority beforehand.

All of this means that in a GPS denied environment (where the OSDK failsafe is most likely to result in a crash), RC loss followed by a valid pilot action (e.g. safety pilot switching to A mode to take manual control) can result in losing control of the drone.

**Comment by greg-draganfly** [comment]
After 5 have you tried toggling the flight mode switch further?  I believe DJI makes state changes only on transitions of this switch.

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
