### ISSUE TITLE
Gimbal Not  Mounted  with  ZENMUSE X5

### ISSUE THREAD

**Issue by cynapoleon** [dji-sdk/Onboard-SDK#338]
A3 + ZENMUSE X5 + Onboard-SDK(3.6)+DJI Lightbridge 2:
After successful connection, the remote control can control  Gimbal and take photos.The onboardsdk can switch mode by clicking [Take Photo] and [Start Video], but the Gimbal  cannot be controlled, as shown in the figure below. Please help confirm the reason.

![2](https://user-images.githubusercontent.com/37980060/41571758-4e347d00-73a7-11e8-8910-6f6a74b974d7.PNG)

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
