### ISSUE TITLE
Failed when make djiosdk-core, undefined reference to cuda

### ISSUE THREAD

**Issue by imkhairulikhwan** [dji-sdk/Onboard-SDK#339]
Hi guys, just wondering if anyone could help to look at below issue? It's pending without any response for almost 1 month. 

https://github.com/dji-sdk/Onboard-SDK-ROS/issues/202

Thank you in advance!

**Comment by rohitsantdji** [comment]
Closing this issue since it is being handled on the OSDK-ROS thread.
