### ISSUE TITLE
Examples of responding to Waypoint Events /w Linux SDK

### ISSUE THREAD

**Issue by adam3039** [dji-sdk/Onboard-SDK#346]
I've been fiddling with this for a good while and was hoping someone might be able to enlighten me. 

So far in the linux samples for mission or flight control, I've only seen two things:
1) Non blocking, the waypoint mission starts and then the program exits.
2) Blocking, but using sleeps. This to me seems hacky because I'm not certain how long certain actions will take.

I implemented a waypoint event callback, here's the code and I'm getting this kind of data back throughout the mission:

```
waypointCallback(Vehicle* vehicle, RecvContainer recvFrame, UserData userData) {
  std::cout << "Waypoint Event Callback Triggered" << std::endl;
  std::cout << "Longitude: " << vehicle->broadcast->getGlobalPosition().longitude << std::endl;
  std::cout << "Latitude: " << vehicle->broadcast->getGlobalPosition().latitude << std::endl;
  std::cout << "Callback ID: " << recvFrame.dispatchInfo.callbackID << std::endl;
  std::cout << "Ack: " << recvFrame.recvData.ack << std::endl;
  std::cout << "Mission Ack: "<<  +recvFrame.recvData.missionACK << std::endl;
  std::cout << "Command Ack: "<<  +recvFrame.recvData.commandACK << std::endl;

  u_int currentWaypoint = +recvFrame.recvData.wayPointReachedData.waypoint_index;

  std::cout << "Current waypoint: " << +currentWaypoint << std::endl;

  if(currentWaypoint == 1 && !paused) {
      paused=true;
      vehicle->missionManager->wpMission->pause();
      sleep(5);
      vehicle->missionManager->wpMission->resume();
  }
  std::cout << std::endl;
}
```

Output:
> Waypoint Event Callback Triggered
Longitude: 1.98896
Latitude: 0.393446
Callback ID:  
Ack: 514
Mission Ack: 2
Command Ack: 2
Current waypoint: 2

> Waypoint Event Callback Triggered
Longitude: 1.98896
Latitude: 0.393445
Callback ID:  
Ack: 770
Mission Ack: 2
Command Ack: 2
Current waypoint: 3

> Waypoint Event Callback Triggered
Longitude: 1.98896
Latitude: 0.393445
Callback ID:  
Ack: 770
Mission Ack: 2
Command Ack: 2
Current waypoint: 3

This seems helpful, but I'm having difficulty matching up the Ack codes I get with the ground station protocol document.

Is there any way to block until you've hit a particular mission status? My ideal scenario looks like:

1) Run Waypoint Mission
2) Wait for ACK that have arrived at next waypoint
3) Pause mission, do some things
4) Resume mission
5) Repeat 2-4
6) Once ACK that mission has ended, land

**Comment by tahsinkose** [comment]
Hi @adam3039. Have you found a solution to your scenario? Most specifically, did you find out a proper way of updating waypoint missions without sleeps but each wp is acked sequentially?
