### ISSUE TITLE
L347: ERROR,there is not enough memory

### ISSUE THREAD

**Issue by Gerjen100** [dji-sdk/Onboard-SDK#347]
Hi,

I am running the demo_mission sample on my computer, after trying the sample out a couple times the error L347: ERROR,there is not enough memory pops up. The dji_sdk node stops sending data from this point on. After attempting to restart the node i am left with another error:  L1339: Drone version not obtained! Please do not proceed. This randomly dissapears after an hour or two. 

Does anyone have a clue on how to resolve these errors?

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
