### ISSUE TITLE
Failed to get drone version (M210 Onboard sdk)

### ISSUE THREAD

**Issue by azrimahanif** [dji-sdk/Onboard-SDK#349]
Hi

We're having issues with the drone version when running the samples, the serial communication pass with no issues, but then error come in. 

![capture](https://user-images.githubusercontent.com/30805989/42485253-704e65ee-8429-11e8-8ed5-f53a5a4b4475.PNG)

there are also an issue with the dji assistant 2, where we couldn't get the drone latest firmware information. 

![capture1](https://user-images.githubusercontent.com/30805989/42485346-dbb7136c-8429-11e8-9397-7f74a350cabc.PNG)

we have followed the instructions [DJI Onboard Software setup](https://developer.dji.com/onboard-sdk/documentation/development-workflow/environment-setup.html) here.

we have update the drone latest firmware using mobile phone. 
Is there any possible error during the hardware or software setup? 

Thank you in advance.

**Comment by giueppo** [comment]
I had the same problem at the beginning. After checking thousand, I had some pin in wrong way.
You can check:
- if you inserted Activation code of your firmware
- if you activated the firmware by running it while the DJIGo App is opened and the device connected to internet
- during my trials, I also connect DJI go with the same account I registered the firmware.
- check again if the serial port are sending messages that make sense (look in exadecimal and look for packets)

**Comment by rohitsantdji** [comment]
An additional check - after you updated your firmware using a mobile phone, can you go into Assistant's SDK page and make sure the Enable API Control box is still checked? Additionally, make sure that at least one broadcast data is set to a non-zero value on the same page.

**Comment by azrimahanif** [comment]
Thank you @giueppo , @rohitsantdji ,

the activation is working, we re-install the dji assistant 2 and connect the controller with mobille phone during the activation.

Thank you so much for your help.
