### ISSUE TITLE
M600 A3 Takeoff failed. Motors failed to start!

### ISSUE THREAD

**Issue by giueppo** [dji-sdk/Onboard-SDK#350]
Good morning everybody,
i'm testing everything in simulation, however all the times in the example 1 (position control sample) with stm32, printf report that motots are not activated while in the simulation the drone is correctly takeoff and doing the mission, even in a very slow way.

The same happens also if I try to do monitoredtakeoff(). Everythins happens in a very slow way and "Takeoff failed. Motors failed to start!" always appear.

What should I check?

During the simulation, fllight status goes to 2 value and display mode goes to 6 value.

Thank you. Below the info received on the pc.

Starting executing position control sample:<CR><LF>
<LF>
STATUS/1 @ addPackageCallback, L291: Start package 0 result: 0.<LF>
STATUS/1 @ addPackageCallback, L293: Package 0 info: freq=10, nTopics=2.Takeoff failed. Motors failed to start!<LF>
<LF>
STATUS/1 @ removePackageCallback, L433: Remove package 0 successful.<LF>
STATUS/1 @ addPackageCallback, L291: Start package 0 result: 0.<LF>
STATUS/1 @ addPackageCallback, L293: Package 0 info: freq=50, nTopics=2.<LF>
STATUS/1 @ getErrorCodeMessage, L644: setFrequencyCallback<LF>
STATUS/1 @ getCMDSetActivationMSG, L693: ACTIVATE_SUCCESS<LF>
<LF>
STATUS/1 @ removePackageCallback, L433: Remove package 0 successful.<LF>
STATUS/1 @ addPackageCallback, L291: Start package 0 result: 0.<LF>
STATUS/1 @ addPackageCallback, L293: Package 0 info: freq=50, nTopics=2.<LF>
STATUS/1 @ getErrorCodeMessage, L644: setFrequencyCallback<LF>
STATUS/1 @ getCMDSetActivationMSG, L693: ACTIVATE_SUCCESS<LF>
<LF>
STATUS/1 @ removePackageCallback, L433: Remove package 0 successful.<LF>
STATUS/1 @ addPackageCallback, L291: Start package 0 result: 0.<LF>
STATUS/1 @ addPackageCallback, L293: Package 0 info: freq=50, nTopics=2.<LF>
STATUS/1 @ getErrorCodeMessage, L644: setFrequencyCallback<LF>
STATUS/1 @ getCMDSetActivationMSG, L693: ACTIVATE_SUCCESS<LF>
<LF>
STATUS/1 @ removePackageCallback, L433: Remove package 0 successful.<LF>
STATUS/1 @ addPackageCallback, L291: Start package 0 result: 0.<LF>
STATUS/1 @ addPackageCallback, L293: Package 0 info: freq=10, nTopics=2.Vehicle landing...<LF>
Successful landing!<LF>

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
