### ISSUE TITLE
Log message partially printed (only header part)

### ISSUE THREAD

**Issue by jonathanmichel** [dji-sdk/Onboard-SDK#351]
It happens that log displays only the header part and not the user custom message, as shown below :
![logbug](https://user-images.githubusercontent.com/24658882/42803276-d23dcaf2-89a5-11e8-96eb-fdc8bf9540ca.PNG)

After a debugging session, I noticed the following :

With macro implementations in dji_log.h, when user call 
`DSTATUS("Monitored takeoff launched");`
Precompiler will replace this line by the following (step by step) :
`DLOG(STATUS)("Monitored takeoff launched");`
`DLOG(DJI::OSDK::Log::instance().getStatusLogState())("Monitored takeoff launched");`
`DJI::OSDK::Log::instance().title((DJI::OSDK::Log::instance().getStatusLogState()), #DJI::OSDK::Log::instance().getStatusLogState(), __func__, __LINE__).print("Monitored takeoff launched");`

If status logs are enabled (level = DJI::OSDK::Log::instance().getStatusLogState() = true), title() method will [set global `valid` variable to true](https://github.com/dji-sdk/Onboard-SDK/blob/b68c9ae5b71809edf16c62e149e189d16bbb422d/osdk-core/hal/src/dji_log.cpp#L64) and [print status log header](https://github.com/dji-sdk/Onboard-SDK/blob/b68c9ae5b71809edf16c62e149e189d16bbb422d/osdk-core/hal/src/dji_log.cpp#L67). 

When using multi-thread, if a call is made to another kind of log that is disabled while the `print()` method of the DSTATUS has not been called yet, for [example](https://github.com/dji-sdk/Onboard-SDK/blob/b68c9ae5b71809edf16c62e149e189d16bbb422d/osdk-core/api/src/dji_vehicle.cpp#L1746).
`DDEBUG("Received Unknown PushData\n"); ` :
After precompiler: 
`DJI::OSDK::Log::instance().title((DJI::OSDK::Log::instance().getStatusLogState()), #DJI::OSDK::Log::instance().getStatusLogState(), "PushDataHandler", 1746).print("Received Unknown PushData\n");`

the global variable `Valid` will be [reset to false](https://github.com/dji-sdk/Onboard-SDK/blob/b68c9ae5b71809edf16c62e149e189d16bbb422d/osdk-core/hal/src/dji_log.cpp#L89) (level = DJI::OSDK::Log::instance().getDebugLogState() = false) and debug log header will not be printed, as the user cutom debug message on [print() call](https://github.com/dji-sdk/Onboard-SDK/blob/b68c9ae5b71809edf16c62e149e189d16bbb422d/osdk-core/hal/src/dji_log.cpp#L103). This is the desired behavior for this kind of log.

However, `print()` call for initial DSTATUS call will not print user message "Monitored takeoff launched" as expected. The global variable `valid` having being reset.

To solve this issue, I see three solutions :

1. Ensure that `print()` method is called directly after `title()` method, to guarantee `valid` state is corresponding to current log print. It is possible with a mutex (lock in `title()`  and unlock in `print()`). But it is not a clean way to fix this and mutexes are not availables on all supported platforms . Furthermore `title()`  calls `print()` once, which require a counter to unlock mutex. 
2.  Add to `print()` method a parameter that indicates if current message has to be print or not. I don't find a way to replace
`DSTATUS("Monitored takeoff launched");`
with 
`DJI::OSDK::Log::instance().title((DJI::OSDK::Log::instance().getStatusLogState()), #DJI::OSDK::Log::instance().getStatusLogState(), __func__, __LINE__).print(DJI::OSDK::Log::instance().getStatusLogState(), "Monitored takeoff launched");`
with #define and macro.
3. Add a static instance of Log usable as a non-printable instance. `title()` method will return either Singleton instance of Log or non-printable instance depending of log type is enabled or not :

```
Log&
Log::title(int level, const char* prefix, const char* func, int line)
{
  if (level)
  {
    const char str[] = "\n%s/%d @ %s, L%d: ";
    print(str, prefix, level, func, line);
    return *this;
  }
  else
  {
    // Return notPrintableInstance to indicate to print() method
    // that this log type is disable
    return notPrintableInstance;
  }
}
```
`print()` method can now know if it has to print message or not by checking caller object 

```
Log&
Log::print(const char* fmt, ...)
{
  // If print() method was called from notPrintableInstance
  // it means that this log type is disabled
  if (this != &notPrintableInstance)
  {
    va_list args;
    va_start(args, fmt);
    mutex->lock();
    vprintf(fmt, args);
    fflush(stdout);
    mutex->unlock();
    va_end(args);
 }
  return *this;
}
```

This solution works and ensures printing all log messages. However it doesn't guarantee that all messages are printed in correct order, as shown below :

![bugfix](https://user-images.githubusercontent.com/24658882/42804750-250335c0-89aa-11e8-898e-c98cde3edee9.PNG)

It is the only way I found to fix this issue, [Pull request 352](https://github.com/dji-sdk/Onboard-SDK/pull/352)

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
