### ISSUE TITLE
Advanced Sensing - Single Thread Stereo Sample Issue

### ISSUE THREAD

**Issue by mkmarineboy** [dji-sdk/Onboard-SDK#355]
Hello,
Onboard SDK is built on **Jetson TX2** with Advanced Sensing.
Drone model: **DJI M210**
OSDK: 3.6 / Advanced-Sensing: 2.0.1 armv8
VTK library is installed so OpenCV Viz3d and XImgProc is also installed with Contrib lib.

Problem is about : **void stereoImg240pCallback** (stereo_vision_single_thread_sample.cpp)

under main I changed line: 107   sleep(5); to sleep(5555555555); to observe sample for a long time. It stops in random time. It can be 30 seconds, it can be after minutes.

Whenever I changed line 151     cv::waitKey(1); to cv::waitKey(10) it doesn't crash and works

It's easier to observe the problem with imwrite instead of imshow. It runs max ~30 seconds with imwrite (also waitKey is disabled)

It is possible there can be a thread issue.

Thank you :)

**Comment by hummelslei** [comment]
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.
