### ISSUE TITLE
error getDroneVersion with M600 pro and SDK 3.6

### ISSUE THREAD

**Issue by ulbrichr** [dji-sdk/Onboard-SDK#358]
I set up the DJI SDK 3.6 on a raspberry pi 3 and connected it with our M100 (direct GPIO to UART). It worked and gave me the output I wanted. When I tried the same with our M600 pro, I am getting the same error over and over again:

    Read App ID
    User Configuration read successfully.
    STATUS/1 @ init, L55: Attempting to open device /dev/ttyS0 with baudrate 230400...
    STATUS/1 @ init, L65: ...Serial started successfully.
    ERRORLOG/1 @ getDroneVersion, L1339: Drone version not obtained! Please do not proceed.
    Possible reasons:
    Serial port connection:
    * SDK is not enabled, please check DJI Assistant2  -> SDK - [v] Enable API Control.
    * Baudrate is not correct, please double-check from DJI Assistant2 -> SDK -> baudrate.
    * TX and RX pins are inverted.
    * Serial port is occupied by another program.
    * Permission required. Please do 'sudo usermod -a -G dialout $USER' (you do not need to replace $USER with your username). Then logout and login again
    ERRORLOG/1 @ activate, L1228: Unable to initialize some vehicle components!
    STATUS/1 @ getErrorCodeMessage, L644: initVehicle
    STATUS/1 @ getCommonErrorCodeMessage, L710: ACK_NO_RESPONSE_ERROR
    Vehicle not initialized, exiting.

I tried different set ups and SDK versions for the M600 from 3.4 to 3.6, different wire set ups, changing TX and RX, changing it to a USB-ttl cord, changing the baudrate, permission for dialout is set as well - no success. The &quot;Enable API control&quot; box is checked in DJI Assistant 2 v1.2.4, cords are plugged into the API port of the A3 flight controller.
The firmware on the M600 pro has the latest update 1.00.01.66 (the older version had no success either)
I am wondering, if I am missing anything or how I can get around this error message.
Thanks in advance.

**Comment by Jai-GAY** [comment]
i have the [same issue with auto startup and command line](https://github.com/dji-sdk/Onboard-SDK/issues/374#issue-359809692).

**Comment by ulbrichr** [comment]
I updated the SDK to 3.7 and connected another RPi to the drone. Finally got it running and suspect that the serial port of the old RPi is fried. Maybe the message

``
STATUS/1 @ init, L65: ...Serial started successfully.
``

was misleading for me because I assumed that a serial connection was established.

Closing this issue now.
