### ISSUE TITLE
Why cannot accept a mission without initial controller connection?

### ISSUE THREAD

**Issue by trungnmh90** [dji-sdk/Onboard-SDK#359]
I am having M210 and trying to program an un-attended mission manager using OSDK where there is no RC connection or mobile DJI GO.

But without the DJI GO application and remote control, the SDK will not allowed to upload mission. I got error "WAYPOINT_MISSION_POINTS_TOO_FAR". And the only way to fix it is to turn on RC and the mobile application **once** every time the drone is power-cycled. Then, the application will inform by audio: "The home point is updated..." and I will be good to upload mission.

Interesting point is, after the Home Point's initialized, I can turn off the RC, and the OSDK allow me to upload mission as normal.

Is there a way to designed the program using OSDK to allow flight without the controller?

**Comment by dji-kyle** [comment]
There will be a restricted flight area with a radius of 50m and a height of 30m. And without the RC connections, if the waypoint mission beyond the area, it will not be uploaded and start.
