### ISSUE TITLE
Onboard-SDK_v3.7.0 [DJI_DEPRECATED]

### ISSUE THREAD

**Issue by Jai-GAY** [dji-sdk/Onboard-SDK#362]
a lot of DJI_DEPRECATED messages.

../dji-sdk/Onboard-SDK-3.7.0/osdk-core/api/inc/dji_vehicle.hpp:117:39: warning: ‘MobileCommunication’ is deprecated [-Wdeprecated-declarations]
   DJI_DEPRECATED MobileCommunication* moc;

-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: ../dji-sdk/Onboard-SDK-3.7.0/build

**Comment by zliDJI** [comment]
Yes. We are deprecating some APIs and replaced them with new interfaces. Those old APIs are still usable so your old code can still run, but we put notifications that they will be deprecated in the future. Please in your new development use the new APIs.
