### ISSUE TITLE
ACK_NO_RESPONSE_ERROR in V1.7.6.0

### ISSUE THREAD

**Issue by jarednm** [dji-sdk/Onboard-SDK#363]
After upgrading to v1.7.6.0, my OSDK v3.7 application fails to activate the vehicle and I receive a ACK_NO_RESPONSE_ERROR.  This is on an A3 flight controller.

Here is the code in question.  This always succeeds on V1.7.5.0 (I have tried a roll-back) and always fails on V1.7.6.0.

        activateData.ID = MY_ID;
        activateData.encKey = MY_KEY;
        activateData.version = vehicle->getFwVersion();
        ACK::ErrorCode ack   = vehicle->activate(&activateData, 1);

        if (ACK::getError(ack)) {
            ACK::getErrorCodeMessage(ack, __func__);
            delete(vehicle);
            vehicle     = nullptr;
            std::cout << "error in activation\n";
        }

**Comment by dwang0927** [comment]
I used to have this problem before and it turns out the serial pins are being occupied by the console. You can try to disable that.
