### ISSUE TITLE
Camera Stream sample suddenly stoppped

### ISSUE THREAD

**Issue by imkhairulikhwan** [dji-sdk/Onboard-SDK#364]
Hi and good day, 

I tried to run the camera-stream-poll-sample Ubuntu 16.04, while turning on both RC and M210. The sample was running fine and showing the image from fpv camera but after few while (5-10 seconds), it suddenly stopped, with below message: 

STATUS/1 **** FPV_CAMERA reading thread stopped

STATUS/1 @ reset, L560: Reset Subscription Successful.

Just to confirm, is the behavior expected to be that way? (Perhaps in the sample was designed to just show few seconds)

Thank you.

![image](https://user-images.githubusercontent.com/4214164/44245182-1f1a7380-a20a-11e8-9e26-4b81f124d7bb.png)

**Comment by zliDJI** [comment]
The code was written this way. Display the image for 10 seconds and stop. You can increase the number of iterations by yourself.
