### ISSUE TITLE
DJI Onboard SDK Samples on other IDE

### ISSUE THREAD

**Issue by mpxtony** [dji-sdk/Onboard-SDK#372]
Hello,

I want to run the DJI Onboard STM32 samples on Atollic and not Keil.

Unfortunately, I'm having great trouble to compile it.
Has somebody sucessfully ran the dji examples on some other IDE than KEIL?

**Comment by dji-kyle** [comment]
The following forum Community is recommanded for you, if the problem persists, or new questions about the DJI SDK,
https://djisdksupport.zendesk.com/hc/en-us/community/topics
