### ISSUE TITLE
How am i getting Waypoint Mission Status

### ISSUE THREAD

**Issue by mouszi** [dji-sdk/Onboard-SDK#373]
Hello, how am i getting any informations about the current mission that the drone is flying? I dont get any informations when i call WayPointReachedData.

**Comment by imkhairulikhwan** [comment]
Hello @mouszi , have you resolved this issue? I would like to know the same information as well.

**Comment by dji-kyle** [comment]
The following forum Community is recommanded for you, if the problem persists, or new questions about the DJI SDK,
https://djisdksupport.zendesk.com/hc/en-us/community/topics
