### ISSUE TITLE
Received data sent from MSDK on the OSDK, How to run bat file on certain command?

### ISSUE THREAD

**Issue by ZeeshanShabbir** [dji-sdk/Onboard-SDK#375]
Hello all,

I am able to receive data msdk on osdk, now i want to run a bat file which is located on the Raspberry pi (onboard computer running Raspbian) I want to have two certain commands A and B. When App sends A command batch file should run and when B is send then batch file should terminate. How can i do that?
I am not a C++ coder. I will be able to do that just push me into right directions. Thanks

**Comment by Jai-GAY** [comment]
?? i think is a Linux question not OSDK question.

shouldn't you should transfer the bat code operation into the OSDK Linux Application ?
bat file usually run from [Linux Terminal](https://askubuntu.com/questions/38661/how-do-i-run-sh-files).

you seem trying to repeat Linux Terminal's capability. i am not sure as i may not be deep into Linux yet.

**Comment by dji-kyle** [comment]
The following forum community is recommanded for you, if the problem persists, or new questions about the DJI SDK,
https://djisdksupport.zendesk.com/hc/en-us/community/topics
