### ISSUE TITLE
Supported Firmware

### ISSUE THREAD

**Issue by naba89** [dji-sdk/Onboard-SDK#376]
Hi,
The new features in the latest OSDK release are stated to be supported on the A3/A3 Pro controllers, but not on the M600 Pro drone. I am wondering why that is so, since the M600 Pro uses the A3 Pro controller. Is it possible to upgrade the firmware of the controller in M600 pro to fully utilize the advanced telemetry features on the M600 Pro?

Regards
Nabarun

**Comment by rohitsantdji** [comment]
Unfortunately that is not possible at this time, since even though the flight controller hardware is the same, M600 Pro firmware is quite different from the A3's.

**Comment by naba89** [comment]
Ah I see. One more quick question if you don't mind. When is the updated firmware (with the new features) release scheduled for the M600 Pro?
