### ISSUE TITLE
advanced-sensing cmake.. ERROR

### ISSUE THREAD

**Issue by 1838094824** [dji-sdk/Onboard-SDK#377]
Hi!
When I cmake.. about advanced-sensing, it reports this error:

CMake Error at CMakeLists.txt:32 (find_package):
  By not providing "FindLibUSB.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "LibUSB", but
  CMake did not find one.

  Could not find a package configuration file provided by "LibUSB" with any
  of the following names:

    LibUSBConfig.cmake
    libusb-config.cmake

  Add the installation prefix of "LibUSB" to CMAKE_PREFIX_PATH or set
  "LibUSB_DIR" to a directory containing one of the above files.  If "LibUSB"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/home/wxz/Onboard-SDK-3.7/sample/linux/advanced-sensing/build/CMakeFiles/CMakeOutput.log".

I had already installed libusb-1.0.22 with ./configure and make and make install , but there are not such files LibUSBConfig.cmake and libusb-config.cmake. So,what should I do?
thanks advaced

**Comment by TorMFinn** [comment]
I'm also having this issue, did you find a solution?

**Comment by dji-kyle** [comment]
The following forum community is recommanded for you, if the problem persists, or new questions about the DJI SDK,
https://djisdksupport.zendesk.com/hc/en-us/community/topics
