### ISSUE TITLE
Lat, Lon are 0.0 in getGlobalPosition()

### ISSUE THREAD

**Issue by jarednm** [dji-sdk/Onboard-SDK#378]
I am using DJI OSDK 3.7 on an M210 running latest firmware at time of writing (3.3.10.4) and have encountered an issue with the getGlobalPosition() function in broadcast.  

Though I am able to read a value for altitude, both the latitude and longitude are always reported as 0.0, even when latitude and longitude are nonzero in the getGPSInfo() message.  The reason I cannot simply use getGPSInfo() is because my application may be run on an M100, which does not support that getter.

I have verified that I have at least 4 satellites, and I gave the M210 up to 30 minutes to report latitude, longitude.

Attached are screenshots from my application, printing latitude and longitude from getGlobalPosition(), and getGPSInfo().  

<img width="141" alt="getglobalposition" src="https://user-images.githubusercontent.com/11839541/46041417-98d63480-c0c7-11e8-86d8-286347f6b42f.png">
<img width="214" alt="getgpsinfo" src="https://user-images.githubusercontent.com/11839541/46041418-98d63480-c0c7-11e8-9c4c-87cb11f5a2ce.png">

**Comment by huangyinpei** [comment]
hi. I want to know how does DJI Assistant2(simulation) CALCULATE worldlatitude, worldlongitude values? How did you calculate lata nd  lon .Please help me.thanks.

**Comment by SChalice** [comment]
I am seeing the same thing on my M600. This is definitely a bug because the unpack routine has the data there, in the gps area, it was just not put into the gp area.

```
  unpackOne(FLAG_POSITION    ,&gp        ,pdata,sizeof(gp        ));
  unpackOne(FLAG_POSITION    ,&rp        ,pdata,sizeof(rp        ));
  unpackOne(FLAG_GPSINFO     ,&gps       ,pdata,sizeof(gps       ));
```

**Comment by dji-kyle** [comment]
The following forum community is recommanded for you, if the problem persists, or new questions about the DJI SDK,
https://djisdksupport.zendesk.com/hc/en-us/community/topics
