### ISSUE TITLE
XT2 Thermal streaming

### ISSUE THREAD

**Issue by maranik** [dji-sdk/Onboard-SDK#381]
Hello,
we would like to use the new Zenmuse XT2 module with a M210.
It is not clear if the Onboard-SDK, through AdvancedSensing, provides the support to retrieve Thermal and RGB images.
Can you please clarify this topic and eventually provide also some details regarding FPS and resolutions?

Thanks

**Comment by alexandrevasques** [comment]
I have the some doubt!

**Comment by guicolares** [comment]
Me to.

**Comment by rodbelisario** [comment]
Hi guys,
Any news about this topic? I also want to know if is possible to get the thermal frames from Zenmuse XT2 using OSDK on Matrice-M210. Anyone had lucky with that?
Thanks in advance!

**Comment by dji-kyle** [comment]
The following forum community is recommanded for you, if the problem persists, or new questions about the DJI SDK,
https://djisdksupport.zendesk.com/hc/en-us/community/topics
