### ISSUE TITLE
SDK串口协议

### ISSUE THREAD

**Issue by WangShanpeng** [dji-sdk/Onboard-SDK#383]
我想快速了解到怎么解析飞控发送过来的姿态速度位置等信息，请问相关的串口协议哪里有具体的定义和描述？或者说我应该看哪个文件？

**Comment by xelmirage** [comment]
dji_telemetry_doc.hpp

**Comment by WangShanpeng** [comment]
感谢！

**Comment by xelmirage** [comment]
但是这个文件好像好久没有更新过了，与api的实际情况严重不符，他们开发组也没个说法

**Comment by dji-kyle** [comment]
考虑到使用版本有更新，此问题将暂时关闭。为便于更好的提供维护和技术支持，如果问题依旧存在，或继续有关于SDK的问题咨询，可以前往DJI SDK社区发帖咨询，感谢理解和支持。
https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
