### ISSUE TITLE
Read Remote Control Extension Kit values

### ISSUE THREAD

**Issue by nikonikolov** [dji-sdk/Onboard-SDK#388]
Hi, is there currently a way to read the values of the switches on the extension kit, because I cannot find one. It's extremely hard to read the extension kit values due to the additional hardware required and especially with systems such as raspberry pi which are not particularly good at reading PWM.

**Comment by dji-kyle** [comment]
The following forum community is recommanded for you, if the problem persists, or new questions about the DJI SDK,
https://djisdksupport.zendesk.com/hc/en-us/community/topics
