### ISSUE TITLE
Get world.x,world.y, world.z value  

### ISSUE THREAD

**Issue by meixianpiao** [dji-sdk/Onboard-SDK#389]
I want to get M600 current world.x, world.y, world.z value, but it seems like they don't provide relative telemetry.  
At first, I thought world.z is equal to TOPIC_ALTITUDE_FUSIONED, but they are different. 
Does anyone have any idea?  
I want to know how does DJI Assistant2 CALCULATE world.x, world.y, world.z values?  Please help me.

**Comment by dji-kyle** [comment]
The following forum community is recommanded for you, if the problem persists, or new questions about the DJI SDK,
https://djisdksupport.zendesk.com/hc/en-us/community/topics
