### ISSUE TITLE
The API documents about the DJI Onboard SDK API Library?

### ISSUE THREAD

**Issue by lbdhr** [dji-sdk/Onboard-SDK#39]
Hello, DJI. Fantastic work!
But I am wondering whether there are any API documents about the DJI Onboard SDK API Library?
I couldn't find any now.
Thanks very much!

**Comment by lanyusea** [comment]
Hi, if you mean the usage of library, i.e. the interactive layer (reading data from drone and send command to it), just refer to the `DJI_APP.cpp`
