### ISSUE TITLE
NEW_DEVICE_ERROR

### ISSUE THREAD

**Issue by IchMarcel** [dji-sdk/Onboard-SDK#390]
用的是N3飞控，调试总是报NEW_DEVICE_ERROR，确认激活了，也确认用了对的APP KEY和APP ID，还是报这个错误。。。
有没有人遇到同样错误的？
希望可以分享下经验！
十分感谢！

**Comment by zhudaoruyi** [comment]
你这个问题，不会有人回答你的，因为你提供的信息量不够，你需要将报错的提示贴上来，截图也行。

**Comment by dji-kyle** [comment]
考虑到使用版本有更新，此问题将暂时关闭。为便于更好的提供维护和技术支持，如果问题依旧存在，或继续有关于SDK的问题咨询，可以前往DJI SDK社区发帖咨询，感谢理解和支持。
https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
