### ISSUE TITLE
About WaypointMission

### ISSUE THREAD

**Issue by IchMarcel** [dji-sdk/Onboard-SDK#391]
I want to know how to add actions in WaypointMission.

typedef struct WayPointSettings
{
  uint8_t   index;     /*!< Index to be uploaded */
  float64_t latitude;  /*!< Latitude (radian) */
  float64_t longitude; /*!< Longitude (radian) */
  float32_t altitude;  /*!< Altitude (relative altitude from takeoff point) */
  float32_t damping; /*!< Bend length (effective coordinated turn mode only) */
  int16_t   yaw;     /*!< Yaw (degree) */
  int16_t   gimbalPitch; /*!< Gimbal pitch */
  uint8_t   turnMode;    /*!< Turn mode <br> */
  /*!< 0: clockwise <br>*/
  /*!< 1: counter-clockwise <br>*/
  uint8_t reserved[8]; /*!< Reserved */
  uint8_t hasAction;   /*!< Action flag <br>*/
  /*!< 0: no action <br>*/
  /*!< 1: has action <br>*/
  uint16_t actionTimeLimit;      /*!< Action time limit */
  uint8_t  actionNumber : 4;     /*!< Total number of actions */
  uint8_t  actionRepeat : 4;     /*!< Total running times */
  uint8_t  commandList[16];      /*!< Command list */
  uint16_t commandParameter[16]; /*!< Command parameters */
} WayPointSettings;    

this struct is about to initialize the point in WaypointMission.
 uint8_t hasAction; means has action or not.
but i don't know add an action.
for example, there 5 points in WaypointMission, i want to let the drone land and takeoff at each point.
Does anyone know???   Thx!!

**Comment by dji-kyle** [comment]
eg:
void
setWaypointDefaults(WayPointSettings* wp)
{
  wp->damping         = 0;           //与turn mode对应，turnMode设置为1时，最小值为0.2
  wp->yaw             = 0;           
  wp->gimbalPitch     = 0; 
  wp->turnMode        = 0;      
  wp->hasAction       = 1;           //有上传action时，任务时需要设置为1
  wp->actionTimeLimit = 100;         //航点执行任务的时间，任务较多时间设置太短，任务可能执行不完
  wp->actionNumber    = 5;
  wp->actionRepeat    = 1;           //任务执行次数，设置为0不执行。
  //for (int i = 0; i < 2; ++i)
  {
    wp->commandList[0]      = WP_ACTION_GIMBAL_PITCH;
    wp->commandParameter[0] = 0;
    wp->commandList[1]      = WP_ACTION_GIMBAL_PITCH;
    wp->commandParameter[0] = -90;
   }
}

**Comment by dji-kyle** [comment]
The following forum community is recommanded for you, if the problem persists, or new questions about the DJI SDK,
https://djisdksupport.zendesk.com/hc/en-us/community/topics
