### ISSUE TITLE
Negative speed values in ESC telemetry for Matrice 210

### ISSUE THREAD

**Issue by naba89** [dji-sdk/Onboard-SDK#393]
Hi,

I noticed that the ESC speed values are reported as negative after the craft has landed. Initially before take off they are all zeros. Is this expected behavior? If yes, then how to interpret the negative values?

I have the latest OSDK and firmware for the Matrice 210.

Thanks
Nabarun

**Comment by dji-kyle** [comment]
The following forum community is recommanded for you, if the problem persists, or new questions about the DJI SDK,
https://djisdksupport.zendesk.com/hc/en-us/community/topics
