### ISSUE TITLE
Advanced Sensing unable to retrieve stereo images with stereo-vision-single-thread-sample

### ISSUE THREAD

**Issue by terminator-ger** [dji-sdk/Onboard-SDK#395]
Tested with following configurations:
OSDK: 3.7
FlightControler: 3.3.10.7
Firmware: 1.2
Ubuntu 16.04 x86_64 in a VM

and
OSDK: 3.4
FlighControler: 3.2.39+
Firmware: 1.01.410
RaspberryPi 3 with Raspian
with Advanced Sensing 1.0

Using a Matrice 210 RTK

We tested with both listed configurations and haven't been able to retrieve a full stream of images. At best we received one to six images, but never the expected number for a 30 sec run with 20 Hz. Some of those received images where shifted to the left, like the second half is taken from the next image. In addition after one or two received images the timestamps and frame counter had huge jumps. 
From what we can grasp it seems like the callback is not called often enough (or like in the screenshot just once). 
To exclude issues with the writing speed of the SD-Card we even stripped the called method from every operation except for a counter that increases with each call, that just confirmed our suspicion of the function not being called often enough.
The multi threading version yield the same behavior.
![screenshot_2018-12-12_18-06-43](https://user-images.githubusercontent.com/15146070/49885920-c1eda200-fe38-11e8-8594-34a25499bf6d.png)

**Comment by terminator-ger** [comment]
Have been double checking everything:
RC switched on first, then drone, with DJI Pilot on RC active
Using djiosdk-telemetry-sample -> Subscription to sensors yield data

Using either the stereo now fails completely or 
Using the camera-stream-callback-sample fails at some point for either FPV or main camera(x4) with an error where no connection is possible

> parallels@parallels-vm:~/Onboard-SDK/build/bin$ ./camera-stream-callback-sample 
> Please enter the type of camera stream you want to view
> m: Main Camera
> f: FPV  Camera
> m
> Read App ID
> User Configuration read successfully. 
> STATUS/1 @ init, L55: Attempting to open device /dev/ttyUSB0 with baudrate 230400...
> STATUS/1 @ init, L65: ...Serial started successfully.
> STATUS/1 @ parseDroneVersionInfo, L706: 
> STATUS/1 @ parseDroneVersionInfo, L708: Hardware = PM410
> STATUS/1 @ parseDroneVersionInfo, L709: Firmware = 3.3.10.7
> ERRORLOG/1 @ initVirtualRC, L1067: Virtual RC is not supported on this platform!
> STATUS/1 @ init, L49: Looking for USB device...
> STATUS/1 @ init, L65: Found 5 USB devices, identifying DJI device...
> STATUS/1 @ init, L83: Found a DJI device...
> STATUS/1 @ init, L96: Attempting to open DJI USB device...
> STATUS/1 @ init, L134: ...DJI USB device started successfully.
> STATUS/1 @ activate, L1277: version 0x3030A07
> STATUS/1 @ activate, L1290: Activation successful
> STATUS/1 @ verify, L244: Verify subscription successful.
> STATUS/1 @ initGimbal, L869: Checking if gimbal is connected ...
> STATUS/1 @ startPackage, L350: Start package 0 result: 0.
> STATUS/1 @ startPackage, L352: Package 0 info: freq=50, nTopics=1.
> STATUS/1 @ removePackage, L468: Remove package 0 successful.
> ERRORLOG/1 Connect to MAIN_CAMERA failed, Error: Connection setup failure: connection time out.
> ERRORLOG/1 Initialize MAIN_CAMERA failed
> Double check USB connection or re-plug in USB cable.
> Failed to open selected camera
> STATUS/1 @ reset, L567: Reset Subscription Successful.

or it fails after receiving some frames and then loosing its connection:

> parallels@parallels-vm:~/Onboard-SDK/build/bin$ ./camera-stream-callback-sample 
> Please enter the type of camera stream you want to view
> m: Main Camera
> f: FPV  Camera
> f
> Read App ID
> User Configuration read successfully. 
> STATUS/1 @ init, L55: Attempting to open device /dev/ttyUSB0 with baudrate 230400...
> STATUS/1 @ init, L65: ...Serial started successfully.
> STATUS/1 @ parseDroneVersionInfo, L706: Device Serial No. = 095XF2600202F8
> STATUS/1 @ parseDroneVersionInfo, L708: 
> STATUS/1 @ parseDroneVersionInfo, L709: Firmware = 3.3.10.7
> ERRORLOG/1 @ initVirtualRC, L1067: Virtual RC is not supported on this platform!
> STATUS/1 @ init, L49: Looking for USB device...
> STATUS/1 @ init, L65: Found 5 USB devices, identifying DJI device...
> STATUS/1 @ init, L83: Found a DJI device...
> STATUS/1 @ init, L96: Attempting to open DJI USB device...
> STATUS/1 @ init, L134: ...DJI USB device started successfully.
> STATUS/1 @ activate, L1277: version 0x3030A07
> STATUS/1 @ activate, L1290: Activation successful
> STATUS/1 @ verify, L244: Verify subscription successful.
> STATUS/1 @ initGimbal, L869: Checking if gimbal is connected ...
> STATUS/1 @ startPackage, L350: Start package 0 result: 0.
> STATUS/1 @ startPackage, L352: Package 0 info: freq=50, nTopics=1.
> STATUS/1 @ removePackage, L468: Remove package 0 successful.
> STATUS/1 Connect to FPV_CAMERA successful
> STATUS/1 All components for decoding initialized ...
> STATUS/1 User callback thread created successfully!
> STATUS/1 **** FPV_CAMERA data reading thread start! ****
> STATUS/1 ****** Decoder Callback Thread Start ******
> [h264 @ 0x23e7720] non-existing PPS 63 referenced
> [h264 @ 0x23a75c0] non-existing PPS 63 referenced
> [h264 @ 0x23a75c0] decode_slice_header error
> [h264 @ 0x23a75c0] non-existing PPS 63 referenced
> [h264 @ 0x23a75c0] decode_slice_header error
> [h264 @ 0x23a75c0] non-existing PPS 63 referenced
> [h264 @ 0x23a75c0] decode_slice_header error
> [h264 @ 0x23a75c0] non-existing PPS 63 referenced
> [h264 @ 0x23a75c0] decode_slice_header error
> [h264 @ 0x23a75c0] no frame!
> [h264 @ 0x23e7720] non-existing PPS 63 referenced
> [h264 @ 0x24a85e0] non-existing PPS 63 referenced
> [h264 @ 0x24a85e0] decode_slice_header error
> [h264 @ 0x24a85e0] non-existing PPS 63 referenced
> [h264 @ 0x24a85e0] decode_slice_header error
> [h264 @ 0x24a85e0] non-existing PPS 63 referenced
> [h264 @ 0x24a85e0] decode_slice_header error
> [h264 @ 0x24a85e0] non-existing PPS 63 referenced
> [h264 @ 0x24a85e0] decode_slice_header error
> [h264 @ 0x24a85e0] no frame!
> [h264 @ 0x23e7720] non-existing PPS 63 referenced
> [h264 @ 0x24bc660] non-existing PPS 63 referenced
> [h264 @ 0x24bc660] decode_slice_header error
> [h264 @ 0x24bc660] non-existing PPS 63 referenced
> [h264 @ 0x24bc660] decode_slice_header error
> [h264 @ 0x24bc660] non-existing PPS 63 referenced
> [h264 @ 0x24bc660] decode_slice_header error
> [h264 @ 0x24bc660] non-existing PPS 63 referenced
> [h264 @ 0x24bc660] decode_slice_header error
> [h264 @ 0x24bc660] no frame!
> [h264 @ 0x23e7720] non-existing PPS 63 referenced
> [h264 @ 0x24d09c0] non-existing PPS 63 referenced
> [h264 @ 0x24d09c0] decode_slice_header error
> [h264 @ 0x24d09c0] non-existing PPS 63 referenced
> [h264 @ 0x24d09c0] decode_slice_header error
> [h264 @ 0x24d09c0] non-existing PPS 63 referenced
> [h264 @ 0x24d09c0] decode_slice_header error
> [h264 @ 0x24d09c0] non-existing PPS 63 referenced
> [h264 @ 0x24d09c0] decode_slice_header error
> [h264 @ 0x24d09c0] no frame!
> [h264 @ 0x23e7720] non-existing PPS 63 referenced
> [h264 @ 0x23a75c0] non-existing PPS 63 referenced
> [h264 @ 0x23a75c0] decode_slice_header error
> [h264 @ 0x23a75c0] non-existing PPS 63 referenced
> [h264 @ 0x23a75c0] decode_slice_header error
> [h264 @ 0x23a75c0] non-existing PPS 63 referenced
> [h264 @ 0x23a75c0] decode_slice_header error
> [h264 @ 0x23a75c0] non-existing PPS 63 referenced
> [h264 @ 0x23a75c0] decode_slice_header error
> [h264 @ 0x23a75c0] no frame!
> [h264 @ 0x23e7720] non-existing PPS 63 referenced
> [h264 @ 0x24a85e0] non-existing PPS 63 referenced
> [h264 @ 0x24a85e0] decode_slice_header error
> [h264 @ 0x24a85e0] non-existing PPS 63 referenced
> [h264 @ 0x24a85e0] decode_slice_header error
> [h264 @ 0x24a85e0] non-existing PPS 63 referenced
> [h264 @ 0x24a85e0] decode_slice_header error
> [h264 @ 0x24a85e0] non-existing PPS 63 referenced
> [h264 @ 0x24a85e0] decode_slice_header error
> [h264 @ 0x24a85e0] no frame!
> [h264 @ 0x23e7720] non-existing PPS 63 referenced
> [h264 @ 0x24bc660] non-existing PPS 63 referenced
> [h264 @ 0x24bc660] decode_slice_header error
> [h264 @ 0x24bc660] non-existing PPS 63 referenced
> [h264 @ 0x24bc660] decode_slice_header error
> [h264 @ 0x24bc660] non-existing PPS 63 referenced
> [h264 @ 0x24bc660] decode_slice_header error
> [h264 @ 0x24bc660] non-existing PPS 63 referenced
> [h264 @ 0x24bc660] decode_slice_header error
> [h264 @ 0x24bc660] no frame!
> [h264 @ 0x23e7720] non-existing PPS 63 referenced
> [h264 @ 0x24d09c0] non-existing PPS 63 referenced
> [h264 @ 0x24d09c0] decode_slice_header error
> [h264 @ 0x24d09c0] non-existing PPS 63 referenced
> [h264 @ 0x24d09c0] decode_slice_header error
> [h264 @ 0x24d09c0] non-existing PPS 63 referenced
> [h264 @ 0x24d09c0] decode_slice_header error
> [h264 @ 0x24d09c0] non-existing PPS 63 referenced
> [h264 @ 0x24d09c0] decode_slice_header error
> [h264 @ 0x24d09c0] no frame!
> [h264 @ 0x23e7720] non-existing PPS 63 referenced
> [h264 @ 0x23a75c0] non-existing PPS 63 referenced
> [h264 @ 0x23a75c0] decode_slice_header error
> [h264 @ 0x23a75c0] non-existing PPS 63 referenced
> [h264 @ 0x23a75c0] decode_slice_header error
> [h264 @ 0x23a75c0] non-existing PPS 63 referenced
> [h264 @ 0x23a75c0] decode_slice_header error
> [h264 @ 0x23a75c0] non-existing PPS 63 referenced
> [h264 @ 0x23a75c0] decode_slice_header error
> [h264 @ 0x23a75c0] no frame!
> STATUS/1 Unable to read from FPV_CAMERA lost, retry connecting ...
> ERRORLOG/1 Connect to FPV_CAMERA failed, Error: Connection setup failure: connection time out.
> ERRORLOG/1 Connect to FPV_CAMERA failed, Error: Connection setup failure: connection time out.
> ERRORLOG/1 Connect to FPV_CAMERA failed, Error: Connection setup failure: connection time out.
> ERRORLOG/1 Connect to FPV_CAMERA failed, Error: Connection setup failure: connection time out.
> ERRORLOG/1 Connect to FPV_CAMERA failed, Error: Connection setup failure: connection time out.
> ERRORLOG/1 Connect to FPV_CAMERA failed, Error: Connection setup failure: connection time out.
> ERRORLOG/1 Connect to FPV_CAMERA failed, Error: Connection setup failure: connection time out.
> ERRORLOG/1 Connect to FPV_CAMERA failed, Error: Connection setup failure: connection time out.
> ERRORLOG/1 Connect to FPV_CAMERA failed, Error: Connection setup failure: connection time out.
> ERRORLOG/1 Connect to FPV_CAMERA failed, Error: Connection setup failure: connection time out.
> ERRORLOG/1 Connect to FPV_CAMERA failed, Error: Connection setup failure: connection time out.
> ERRORLOG/1 Unable to reconnect to FPV_CAMERA ..., quit reading thread

Setting the IP manually like in https://github.com/dji-sdk/Onboard-SDK/issues/289#issuecomment-380291233 suggested does not seem to have an influence on this behavior.
Setting the baud rate from 115200 to 230400 had also no influence.
Any help on this would be appreciated.

**Comment by dji-kyle** [comment]
The following forum community is recommanded for you, if the problem persists, or new questions about the DJI SDK,
https://djisdksupport.zendesk.com/hc/en-us/community/topics
