### ISSUE TITLE
Vehicle(bool) doesn't initialize some fields

### ISSUE THREAD

**Issue by m-sasha** [dji-sdk/Onboard-SDK#396]
On branch 3.7, In dji_vehicle.cpp:
The Vehicle(bool) constructor doesn't initialize USBReadThread and advancedSensing, so they are left with garbage values, but the destructor tries to delete them.

**Comment by SChalice** [comment]
You should be a contributor to this repo.

**Comment by dji-kyle** [comment]
The following forum community is recommanded for you, if the problem persists, or new questions about the DJI SDK,
https://djisdksupport.zendesk.com/hc/en-us/community/topics
