### ISSUE TITLE
const static declarations

### ISSUE THREAD

**Issue by m-sasha** [dji-sdk/Onboard-SDK#397]
In many places, the SDK has ```const static <type>``` declarations. Although many compilers allow it, this is obsolete in C. The order should be ```static const <type>```.

For me, this is not just a theoretical issue, because I'm using the SDK through SWIG, which fails on such declarations: https://github.com/swig/swig/issues/241

**Comment by dji-kyle** [comment]
The following forum community is recommanded for you, if the problem persists, or new questions about the DJI SDK,
https://djisdksupport.zendesk.com/hc/en-us/community/topics
