### ISSUE TITLE
Bad memory access in Vehicle::getDroneVersion

### ISSUE THREAD

**Issue by m-sasha** [dji-sdk/Onboard-SDK#398]
In osdk 3.7, dji_vehicle.cpp, Vehicle::getDroneVersion, has this code:

```
droneVersionACK.data.version_name[sizeof(this->versionData.version_name)] = '\0';
```
This accesses memory one byte past version_name's end.

**Comment by SChalice** [comment]
version_name is never referenced so I suggest it would be safe to remove that line of code and deal with it whenever it get used. I am going to make the change to avoid any potential crashing.

**Comment by Jai-GAY** [comment]
Not sure the future going to resolve this issue as well.
[planned patch](https://github.com/dji-sdk/Onboard-SDK/issues/447)
