### ISSUE TITLE
HORIZONTAL_ANGLE flag doesn't work in the real world

### ISSUE THREAD

**Issue by koyahatataku** [dji-sdk/Onboard-SDK#400]
Hi I'm developing osdk3.6 software with Matrice600pro and having issue.

I'm trying to set UAV pitch to 10 with this code but it doesn't work in the real world.
It works in simulator.

Accoding to https://github.com/dji-sdk/Onboard-SDK-ROS/issues/43,
I seem to have to check certain configuration but couldn't figure out.

Does someone have any advice?
Any help will appreciate.

elapsedTimeInMs = 0;
timeoutInMilSec = 700;
controlFreqInHz = 50; // Hz
while (elapsedTimeInMs < timeoutInMilSec)
{
	ctrl_flag = ( Control::VERTICAL_VELOCITY | Control::HORIZONTAL_ANGLE | Control::YAW_RATE | Control::HORIZONTAL_BODY | Control::STABLE_ENABLE);
	
	Control::CtrlData data(ctrl_flag, 0, 10, 0, 0); 
       gVehicle->control->flightCtrl(data);
	
	usleep(cycleTimeInMs * 1000); 
	
	elapsedTimeInMs += cycleTimeInMs;
}

**Comment by koyahatataku** [comment]
![sdk_settings](https://user-images.githubusercontent.com/46317717/51225796-9b6adb80-198f-11e9-8121-fb0dac106ea9.png)
This is my sdk settings.

**Comment by dji-kyle** [comment]
The following forum community is recommanded for you, if the problem persists, or new questions about the DJI SDK,
https://djisdksupport.zendesk.com/hc/en-us/community/topics
