### ISSUE TITLE
Unknown Depth images

### ISSUE THREAD

**Issue by CTTCGeoLab** [dji-sdk/Onboard-SDK#408]
Hi,
I am subscribing via ROS to the following topic /dji_sdk/stereo_240p_front_depth_images corresponding to the stereo disparity map from the front-facing camera of M210 in 240x320 resolution.

The images acquired are in MONO8 format and it can be seen how the intensity values changes in function of the distance. The problem is that there is no information associated about how to interpret the pixel values in order to estimate distances to objects. There is no evident correlation between the values and the distances. In addition the SDK does not provide a camera_info topic associated so it is not possible to generate pointclouds coming from this information.

**Comment by dji-kyle** [comment]
The following forum community is recommanded for you, if the problem persists, or new questions about the DJI SDK,
https://djisdksupport.zendesk.com/hc/en-us/community/topics
