### ISSUE TITLE
proper implementation for aSyncCallback with subscribe

### ISSUE THREAD

**Issue by mclarkwhiteout** [dji-sdk/Onboard-SDK#409]
Hi,

I am working on implementing callbacks for subscribe topics. I have searched for a while and cannot find any real detailed instruction on implementing the call backs and decoding the call back.  I am easily able to run the telemetry sample, however it does not implement callbacks as it just loops after setting up the topics for a duration doing a manual pull on the topic data. This approach docent work well in production as each topic will be coming in at a different rate, hence the need for the call back. 

I have been able to get what I think is correct to trigger the callback, but I can't find any documentation on how to decode the callback. I am looking for (1) confirmation that my approach is correct, and for (2) any information on how to properly decode the data in the call back to get the values I need, specifically for TOPIC_QUATERNION. a summary of my implementation is below. Thanks in advance for any direction on this.

1) create package
2) start package
3) register callback using: registerUserPackageUnpackCallback - is this correct?????
4) decode the callback - how do I do this???

```

//**********************create package  1st*****************
 // Package 3: Subscribe to Quaternion at freq 200 Hz.
    pkgIndex                   = 3;
    freq                       = 200;
    TopicName topicList200Hz[] = { TOPIC_QUATERNION, TOPIC_HARD_SYNC };
    numTopic        = sizeof(topicList200Hz) / sizeof(topicList200Hz[0]);
    enableTimestamp = false;

    pkgStatus = vehicle->subscribe->initPackageFromTopicList(
            pkgIndex, numTopic, topicList200Hz, enableTimestamp, freq);
    if (!(pkgStatus))
    {
        return pkgStatus;
    }

//**********************START PACKAGE*****************  
  subscribeStatus = vehicle->subscribe->startPackage(pkgIndex, responseTimeout);
    if (ACK::getError(subscribeStatus) != ACK::SUCCESS)
    {
        ACK::getErrorCodeMessage(subscribeStatus, __func__);
        // Cleanup before return
        vehicle->subscribe->removePackage(pkgIndex, responseTimeout);
        return false;
    }else {
       //********************************* I assign the callback with the proper index**********
        vehicle->subscribe->registerUserPackageUnpackCallback(pkgIndex, package3Callback);
        //vehicle->subscribe.
    }



void package3Callback(Vehicle *vehiclePtr, RecvContainer recvFrame, UserData userData){
    std::cout << "package3Callback called.\n";
  

 ***********************   HOW DO I DECODE THIS???????????****************


}
```

**Comment by manuoso** [comment]
Hello, 
Any update from this topic? Im interested
Thanks

**Comment by dji-kyle** [comment]
The following forum community is recommanded for you, if the problem persists, or new questions about the DJI SDK,
https://djisdksupport.zendesk.com/hc/en-us/community/topics
