### ISSUE TITLE
How do the positionAndYawCtrl () and flightCtrl () commands in OSDK affect travel speed?

### ISSUE THREAD

**Issue by SMP33** [dji-sdk/Onboard-SDK#412]
We use STM32,A3 and OSDK. In what range we can set float32_t DJI :: OSDK :: Control :: CtrlData :: x in the command flightCtrl () and x in the command positionAndYawCtrl (), and how this values affect the speed of movement? How to use them correctly?Can I use these commands and velocityAndYawRateCtrl() when flying without GPS?

**Comment by lanyusea** [comment]
> In what range we can set float32_t DJI :: OSDK :: Control :: CtrlData :: x in the command flightCtrl () 

It depends on the `ctrl_flag` you set, you can check the document here: https://developer.dji.com/onboard-api-reference/classDJI_1_1OSDK_1_1Control.html#a1f2c5a277f091fb5fb5b39baf6f6fa0f

> and x in the command positionAndYawCtrl (), 

same as previous question, but the `ctrl_flag` has already been set to `VERTICAL_POSITION | HORIZONTAL_POSITION | YAW_ANGLE | HORIZONTAL_GROUND | STABLE_ENABLE`, which means the `x` you put in is the distance away from drone's current position. The drone will generate the speed by itself while you keep sending the updated remaining distance value.

> how this values affect the speed of movement? 

also depends on the `ctrl_flag` means, as the first question says

> How to use them correctly?

It depends on your program. If you have your own feedback control loop, you can use the speed control; if you wanna use our built-in feedback control, you can choose the position control; also, you can use the advanced angle control, i.e. adjust the roll/pitch directly. But be careful of the coordinate, my friend.

> Can I use these commands and velocityAndYawRateCtrl() when flying without GPS?

unfortunately no. The drone needs the GPS measurement as a feedback to make sure velocity value works as what you set. It cannot work when there is no feedback.
