### ISSUE TITLE
SetAngle () does not work in DJI Onboard SDK

### ISSUE THREAD

**Issue by SMP33** [dji-sdk/Onboard-SDK#413]
When running SetAngle (), the program hangs and nothing happens. Gimbal is installed, the example from CameraGimbalSample works through time

**Comment by xueliang2007** [comment]
I met the same problem, too. I ran it on STM32 F407, and when run "setAngle", the code get into hard interrupt, stop in "HardFault",. I think problem may be in "pipeline", butI don't how to solver it

**Comment by dji-kyle** [comment]
The following forum community is recommanded for you, if the problem persists, or new questions about the DJI SDK,
https://djisdksupport.zendesk.com/hc/en-us/community/topics
