### ISSUE TITLE
P4 OR P3 ESC PWM OUTPUT ?

### ISSUE THREAD

**Issue by sakis08** [dji-sdk/Onboard-SDK#414]
I NEED HELP USING P4 OR P3 AS FLIGHT CONTROLLER FULL FUNCTIONS USING BIGGER MOTORS ESC ...
MY PROBLEM IS HOW TO FINE PWM FOR EXTERNAL ESC CONNECTION ?

**Comment by lanyusea** [comment]
not supported, sorry
