### ISSUE TITLE
Cannot creat children for parent that is in a different thread

### ISSUE THREAD

**Issue by zhangwang0537** [dji-sdk/Onboard-SDK#415]
![image](https://user-images.githubusercontent.com/34061213/53299280-ecb19900-3872-11e9-9b92-b6c2d59cd803.png)

M100 QT 例程 线程错误 起飞命令无响应

**Comment by SChalice** [comment]
I have this problem during activation in getDroneVersion(). This function still works. I would ignore the error.

我在getDroneVersion（）中激活期间遇到此问题。此功能仍然有效。我会忽略错误。
