### ISSUE TITLE
OSDK Failsafe vs rc_lost_action

### ISSUE THREAD

**Issue by jarednm** [dji-sdk/Onboard-SDK#416]
Can anyone clarify why the OSDK failsafe is necessary?  The documentation states:
"By default, when the remote controller loses connection to the vehicle, the vehicle executes a return-to-home-and-land (RTL) maneuver. However, there is now an option to override this behavior by allowing the OSDK to continue executing its mission. To do so, users will have to check the Enable SDK Failsafe Action box and set the SDK Failsafe Action to Hover as shown in the picture."

However, when initializing a mission, there is the argument "rc_lost_action", which can be set to 1 to continue with a mission in the event of rc loss.  

Is one of these actions superseded by the other, or are they redundant?

**Comment by lanyusea** [comment]
the `rc_lost_action` is only provided by mission tasks. Mission tasks are not only provided in Onboard SDK.  There are some other conditions you need a failsafe option such as doing simple velocity control but in a poor radio environment.

Good question about their relation. I think it should be an OR action, but I need to check it later.
