### ISSUE TITLE
Obtaining control in DJI Matrice 600 pro without RC

### ISSUE THREAD

**Issue by vAnArhist** [dji-sdk/Onboard-SDK#419]
Hello! Checking the Onboard-SDK API (test sample) with STM32F4Discovery board. In simulator mode seems to be ok, but how can I obtain control on real drone, if Virtual RC has been deprecated and is unavailable for A3 FW > 1.6.0.0.
Now it doesn`t working on latest firmware on A3 (1.7.x.x)
We are using A3 Flight controller and main goal is to control drone without RC. Is it possible to downgrade the FW of A3?

<a href="https://ibb.co/3BPvDMj"><img src="https://i.ibb.co/720QwRZ/Capture.png" alt="Capture" border="0">

**Comment by lanyusea** [comment]
@vAnArhist set the Failsafe option to Hover in DJI Assistant 2

**Comment by vAnArhist** [comment]
@lanyusea It is set. Remote controller is on and in F mode.

**Comment by SChalice** [comment]
I am using the QT OSDK with an onboard nano pc running Windows connected to the A3 with a ttl cable.
I can obtain control without an RC. :)
