### ISSUE TITLE
TOPIC_HEIGHT_FUSION on the DJI M210 reports "-0"

### ISSUE THREAD

**Issue by sissow2** [dji-sdk/Onboard-SDK#421]
To reproduce:
 
I am using the subscription mechanism to retrive this data.  The subscription package creation reports no errors.  I am using the DJI M210.  I verified that this happens on at least two platforms.  
When calling `device->subscribe->getValue<TopicName::TOPIC_HEIGHT_FUSION>()`, `-0` is always reported.

It seems that this might have been broken in a firmware update, because the same code yielded valid data a few weeks ago.

**Comment by dji-kyle** [comment]
valid range < 10m, update the firmvare version and OSDK version to the latest.
