### ISSUE TITLE
uAvionix ADS-B receiver with DJI Onboard SDK

### ISSUE THREAD

**Issue by nazlyteran** [dji-sdk/Onboard-SDK#429]
According to the integration of uAvionix ADS-B receiver with DJI Onboard SDK tutorial(https://developer.dji.com/onboard-sdk/documentation/sensor-integration-guides/ping/README.html), in the step to build the example, we are directed to a link in GIDHUB https://github.com/dji-sdk/Onboard-SDK, where a file is located at the following route: sensor-integration/ADSBExample/Stm32PingExample/ProjectKeil/Stm32PingExample.uvprojx, but the file Stm32PingExample.uvprojx is not found. Please I need your help to get the example code.

**Comment by Jai-GAY** [comment]
2016-08-05 likely stopped updating and compatibility testing from DJI.
You may like to [try your luck here](https://uavionix.com/products/pingrx/)?
