### ISSUE TITLE
3.8版本编译出错（无法找到<chrono> 、<atomic>文件）

### ISSUE THREAD

**Issue by Xuqing134** [dji-sdk/Onboard-SDK#440]
..\Onboard-SDK-3.8\osdk-core\api\incdji_hardware_sync.hpp中的头文件中#include <chrono> , #include <atomic>无法找到。 gz#24236

**Comment by dji-dev** [comment]
> Public comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/24236'>Zendesk ticket #24236</a>:<br><br>尊敬的客户，<br><br>您好！感谢您联系大疆创新。<br><br>如果您使用OSDK的STM32平台，建议使用OSDK 3.7版本而不是3.8。<br><br>感谢您的理解与支持,祝您生活愉快!<br><br>Best Regards，<br>DJI 大疆创新SDK技术支持
