### ISSUE TITLE
Stack Corruption in Vehicle::parseDroneVersionInfo()

### ISSUE THREAD

**Issue by SChalice** [dji-sdk/Onboard-SDK#447]
```<br>  uint8_t crc_id[16] = {};<br>  int     i          = 0;<br>  while (*ackPtr != '\0')<br>  {<br>    crc_id[i] = *ackPtr;<br>    i++;<br>    ackPtr++;<br>    if (ackPtr - startPtr > 18)<br>    {<br>      return false;<br>    }<br>  }<br>```<br><br>  uint8_t crc_id[16] = {};<br><br>needs to be<br><br>  uint8_t crc_id[17] = {}; gz#26094

**Comment by SChalice** [comment]
dji-dev edited crap into my post for some reason, another bug....

**Comment by dji-dev** [comment]
> Public comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/26094'>Zendesk ticket #26094</a>:<br><br>Thank you for your feedback. Our R&D engineers are looking into your questions now!. If there is any feedback I will contact you as soon as possible.

**Comment by dji-dev** [comment]
> Public comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/26094'>Zendesk ticket #26094</a>:<br><br>Thank you for your feedback. We will fix it in later version. Please pay attention to the status of the issue.
In addition, about "edited somthing into your post" issue, it is a bug of the plugin and we have fixed it.
