### ISSUE TITLE
Unable to calibrate DJI N3

### ISSUE THREAD

**Issue by AbhishekGS** [dji-sdk/Onboard-SDK#448]
Hello,<br><br>I am having trouble calibrating the DJI N3 IMU. I get the following error whenever I try to calibrate.<br><br>![image](https://user-images.githubusercontent.com/14905535/61359098-5588c480-a899-11e9-973e-79c422a41b8c.png)<br><br>The software/version details are:<br><br>DJI N3  Firmware = 3.3.8.47 (v1.7.7.0)<br>DJI - Onboard SDK: 3.8<br>DJI Assistant 2 for Autopilot<br><br>How do I proceed?<br><br>Thanks,<br>Abhishek gz#26128

**Comment by dji-dev** [comment]
> Public comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/26128'>Zendesk ticket #26128</a>:<br><br>Hi! I found that your issue is about N3 (not SDK). For product issue, please send an email to support@dji.com. They are better suited to help with your issue. Thank you for your understanding.
