### ISSUE TITLE
Origin of D-RTK

### ISSUE THREAD

**Issue by hyonlim** [dji-sdk/Onboard-SDK#449]
Hi,
We would like to set high precision location of D-RTK (not D-RTK2) in the DJI Assistant 2 App.
However, we do not know antenna specification so we couldn't put exact origin of D-RTK.
Could you please let us know?

**Comment by dji-dev** [comment]
> Public comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/26166'>Zendesk ticket #26166</a>:<br><br>Hi! I found that your issue is about D-RTK (not SDK). Right? For product issue, please send an email to support@dji.com. They are better suited to help with your issue. Thank you for your understanding.
