### ISSUE TITLE
Tagging RTK calculated coordinates in captured image.

### ISSUE THREAD

**Issue by hyonlim** [dji-sdk/Onboard-SDK#450]
Hi,
We are using M210 RTK v1 for experiment. 
We surveyed some article, however, there is no clue that M210 RTK v1 is tagging RTK coordinates to the image or not. Could you please confirm that M210 RTK is tagging RTK information or not?

**Comment by dji-dev** [comment]
> Public comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/26167'>Zendesk ticket #26167</a>:<br><br>Hi! I found that your issue is about M210 RTK v1 (not SDK). Right? For product issue, please send an email to support@dji.com. They are better suited to help with your issue. Thank you for your understanding.
