### ISSUE TITLE
Onboard SDK and GSPro app coexistence.

### ISSUE THREAD

**Issue by hyonlim** [dji-sdk/Onboard-SDK#451]
Hi,
We are going to implement obstacle avoidance while performing pre-defined mission by GS Pro.
How could this be implemented? Can we interrupt control authority while the vehicle is performing mission designed by GS Pro?

**Comment by dji-dev** [comment]
> Public comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/26168'>Zendesk ticket #26168</a>:<br><br>Hi. Is your issue related to the onboard SDK? Or it is only related to the use of GS pro.

**Comment by hyonlim** [comment]
Onboard SDK.

**Comment by dji-dev** [comment]
> Public comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/26168'>Zendesk ticket #26168</a>:<br><br>Onboard SDK can interrupt control authority while the vehicle is performing mission designed by GS Pro. Just call vechile->obtainCtrlAuthority().
