### ISSUE TITLE
Get obstacle avoidance signal?

### ISSUE THREAD

**Issue by hyonlim** [dji-sdk/Onboard-SDK#458]
Hi,
From Onboard-SDK, could we get status of obstacle detection?
For example, we would like to know whether the DJI vehicle detects obstacle or not by Onboard SDK.

**Comment by dji-dev** [comment]
> Public comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/26579'>Zendesk ticket #26579</a>:<br><br>Dear Customer,

Thank you for contacting DJI.

The DJI Onboard SDK provides an API that can be used to obtain the obstacle distance around the aircraft.
However, current this API only supports the M210 series, which can be referred to as: https://developer.dji.com/onboard-api-reference/classDJI_1_1OSDK_1_1DataBroadcast.html#af9099c1e041f4b1bdd2d3c71942b25ef

Thank you for your understanding and support, hope you a delighted life.

Best Regards,
DJI SDK Support Team
