### ISSUE TITLE
Port did not send

### ISSUE THREAD

**Issue by Hitesh-Sagar** [dji-sdk/Onboard-SDK#460]
I am building OSDK on rpi-zero w and getting error 
pi@raspberrypi:~ $ cd Onboard-SDK/build/bin
pi@raspberrypi:~/Onboard-SDK/build/bin $ ./djiosdk-cameragimbal-sample UserConfig.txt
Read App ID
User Configuration read successfully.

STATUS/1 @ init, L55: Attempting to open device /dev/ttyAMA0 with baudrate 230400...

STATUS/1 @ init, L65: ...Serial started successfully.

STATUS/1 @ sendData, L405: Port did not send
ERRORLOG/1 @ sendData, L411: Open Protocol cmd send failed, send_len: 0 packet_len: 19

ERRORLOG/1 @ getDroneVersion, L1418: Drone version not obtained! Please do not proceed.
Possible reasons:
        Serial port connection:
                * SDK is not enabled, please check DJI Assistant2 -> SDK -> [v] Enable API Control.
                * Baudrate is not correct, please double-check from DJI Assistant2 -> SDK -> baudrate.
                * TX and RX pins are inverted.
                * Serial port is occupied by another program.
                * Permission required. Please do 'sudo usermod -a -G dialout $USER' (you do not need to replace $USER with your username). Then logout and login again

ERRORLOG/1 @ activate, L1302: Unable to initialize some vehicle components!
STATUS/1 @ getErrorCodeMessage, L656: initVehicle
STATUS/1 @ getCommonErrorCodeMessage, L722: ACK_NO_RESPONSE_ERROR
Vehicle not initialized, exiting.

kindly help!

**Comment by dji-dev** [comment]
Public comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/26721'>Zendesk ticket #26721</a>:<br><br>Dear Customer,

Thank you for contacting DJI.

Notice the error "Port did not send"
It is recommended that you test  /dev/ttyAMA0 separately, use Linux's serial port assistant tool to verify that the interface can works properly at baud rates of 230400?
It is also recommended that you can use the USB-TTL module to connect the aircraft, such as FT232.

Thank you for your understanding and support, hope you a delighted life.

Best Regards,
DJI SDK Support Team
