### ISSUE TITLE
problems of running QT sample on win7 with N3

### ISSUE THREAD

**Issue by lxiangzi** [dji-sdk/Onboard-SDK#464]
Hello

1. When I run QT sample in Onboard-SDK-3.7 on windows 7 PC connecting with the N3 flight controller，I always met the problem shown as the following figure. But all the required setting and connection are checked without problems. I just re-run the qt sample or unplug and  plug the USB-ttl converter into the PC several times, the qt sample could run and successfully connect with N3. I am not sure, what is reason for such unsatisfied connection building process, is it the usb-ttl converter problem? I tried ch340 and ft232 converter, they all have the above problems.

![problem02](https://user-images.githubusercontent.com/14069079/63251556-8d23cb80-c2a0-11e9-8ad5-e0c45888670d.jpg)

2. sometimes after pressing the "Initialize Vehicle" button, the following information occurs, where no complete information shows on the terminal, for example, hardware version, firmware version and so on, but all the information are correctly shown on the UI.

![problem01](https://user-images.githubusercontent.com/14069079/63251572-944ad980-c2a0-11e9-8173-3f88adfc48d5.jpg)

3. on the broadcast UI, the broadcast data is not updated based on the frequency. sometimes, the data is updating for some time, then it stops without any changing. the problems is some wrong setting or qt software, or....

any help with above problems would be very appreciated.

**Comment by dji-dev** [comment]
Public comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/27228'>Zendesk ticket #27228</a>:<br><br>Dear Customer,

Thank you for contacting DJI.

Sorry to inform you that QT Sample is no longer maintained and updated and provides technical support. It is recommended that you use Linux /ROS /STM32 Sample with OSDK-3.8 version. I am sorry for the inconvenience caused to you.

Best Regards,
DJI SDK Support Team
