### ISSUE TITLE
SUBSCRIBER_ILLEGAL_UID error when subscribing to TOPIC_RC_FULL_RAW_DATA

### ISSUE THREAD

**Issue by fong7x7** [dji-sdk/Onboard-SDK#467]
When attempting to start a vehicle subscription to the TOPIC_RC_FULL_RAW_DATA at 50hz, the subscription does not start and outputs a "SUBSCRIBER_ILLEGAL_UID".  I've tried this on 10hz as well, and it throws the same error.  When removing the topic, it does not output the error.

This is on an M600 Pro running FW 1.00.1.67 and LB2 1.1.70 using OSDK 3.8.  OSDK 3.7 exhibits the same error.

```
STATUS/1 @ startPackage, L350: Start package 1 result: 34.
STATUS/1 @ startPackage, L352: Package 1 info: freq=10, nTopics=4.

STATUS/1 @ getErrorCodeMessage, L656: startPackage
STATUS/1 @ getCMDSetSubscribeMSG, L739: SUBSCRIBER_ILLEGAL_UID
```

**Comment by dji-dev** [comment]
Public comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/27803'>Zendesk ticket #27803</a>:<br><br>Dear Customer,

Thank you for contacting DJI.

Sorry that the TOPIC_RC_FULL_RAW_DATA API does not support M600 Pro at present. You can refer to the API documentation as follows:
 ![](https://djisdksupport.zendesk.com/attachments/token/Q8cPXsxODMLxR6sLfR8tz9rFP/?name=inline-599447183.png)​

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team<br><a href='https://djisdksupport.zendesk.com/attachments/token/Q8cPXsxODMLxR6sLfR8tz9rFP' target='zd_attach'>inline-599447183.png</a>
