### ISSUE TITLE
may I ask one question?

### ISSUE THREAD

**Issue by Gli-ming** [dji-sdk/Onboard-SDK#468]
How can I use the SDK to control the autonomous target tracking and self-navigation of the uav?

**Comment by dji-dev** [comment]
Public comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/28093'>Zendesk ticket #28093</a>:<br><br>Dear Customer,

Thank you for contacting DJI.

[Q1] How can I use the SDK to control the autonomous target tracking and self-navigation of the UAV?
==> About target tracking, suggest you can refer to https://developer.dji.com/cn/onboard-sdk/documentation/sample-doc/advanced-sensing-target-tracking.html
About self-navigation of the UAV, If you are using M210 and can get depth images, you can develop your own auto-navigation algorithms, such as SLAM. https://developer.dji.com/cn/onboard-sdk/documentation/sample-doc/advanced-sensing-stereo-images.html

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
