### ISSUE TITLE
missing an "using namespace" declaration 

### ISSUE THREAD

**Issue by intijk** [dji-sdk/Onboard-SDK#47]
In file 

Onboard-SDK/sample/commandline/Linux/conboardSDK/conboardsdktask.h

missing 

```
using namespace DJI;
```

DJICommontype.h
```
namespace DJI
{

typedef uint64_t time_ms;
typedef uint64_t time_us; // about 0.3 million years

typedef void *UserData;
```

UserData is in DJI namespace, not DJI::onboardAPI space, compiler report UserData not found.

**Comment by lanyusea** [comment]
pr, thanks
