### ISSUE TITLE
怎么知道当前飞到第几个航点?

### ISSUE THREAD

**Issue by addriumruss** [dji-sdk/Onboard-SDK#471]
怎么知道当前飞到第几个航点?

**Comment by dji-dev** [comment]
Public comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/28749'>Zendesk ticket #28749</a>:<br><br>您好，可以通过setWaypointEventCallback 设置回调函数获取到达航点的信息。参考代码如下：
 ![](https://djisdksupport.zendesk.com/attachments/token/AKxjNGu5jtjGUtA3R1eBJMxvl/?name=inline-1616502596.png)​<br><a href='https://djisdksupport.zendesk.com/attachments/token/AKxjNGu5jtjGUtA3R1eBJMxvl' target='zd_attach'>inline-1616502596.png</a>

**Comment by addriumruss** [comment]
非常感谢，一会儿试试~
