### ISSUE TITLE
How can I use the advanced_sensing function in my code.

### ISSUE THREAD

**Issue by jianti** [dji-sdk/Onboard-SDK#478]
I want to get the video stream via X5S on M210 ,then I implement this steps in new folder-build:
cmake .. -DADVANCED_SENSING=ON 
make
sudo make install
are success, but  when I use my code to call the class of advanced_sensing, it said undefined to DJI::OSDK::advanced_sensing, How should I wrote the cmake file? and my cmake file as below:

cmake_minimum_required(VERSION 2.8)
project(ours)

find_package(OpenCV REQUIRED)
if (OpenCV_FOUND)
    message( "\n${PROJECT_NAME}...")
    message( STATUS "Found OpenCV installed in the system, will use it to display image in AdvancedSensing APIs")
    message( STATUS " - Includes: ${OpenCV_INCLUDE_DIRS}")
    message( STATUS " - Libraries: ${OpenCV_LIBRARIES}")
    add_definitions(-DOPEN_CV_INSTALLED)
else()
    message( STATUS "Did not find OpenCV in the system, image data is inside RecvContainer as raw data")
endif ()

if (ADVANCED_SENSING)
  add_definitions(-DADVANCED_SENSING)
endif()
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -pthread -g -O0")

include_directories(${CMAKE_CURRENT_SOURCE_DIR}/../osdk-core/api/inc)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/../osdk-core/utility/inc)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/../osdk-core/hal/inc)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/../osdk-core/protocol/inc)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/../osdk-core/platform/linux/inc)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/../sample/linux/common)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/../osdk-core/advanced-sensing-2.0.3/inc)

include_directories(${OpenCV_INCLUDE_DIRS})
include_directories(/usr/include/libusb-1.0)
include_directories(/usr/local/include)
FILE(GLOB SOURCE_FILES *.hpp *.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/../sample/linux/common/dji_linux_helpers.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/../sample/linux/common/dji_linux_environment.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/code/main.cpp
)

add_executable(${PROJECT_NAME} ${SOURCE_FILES})

target_link_libraries(${PROJECT_NAME}
djiosdk-core)

if(OpenCV_FOUND)
  target_link_libraries(${PROJECT_NAME}
  ${OpenCV_LIBS}
  )
endif()

**Comment by dji-dev** [comment]
Public comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/29370'>Zendesk ticket #29370</a>:<br><br>Dear Customer,

Thank you for contacting DJI.

You can follow these steps:
1. Create a new application folder in the topmost directory of Onboard- SDK-3.9, such as "Bruce_AD_Test", and create your own CPP file and CMakeLists file (as attached).

    Onboard-SDK-3.9
    ├── Bruce_AD_Test
       ├── CMakeLists.txt
     └── main.cpp

2. Add add_subdirectory(Bruce_AD_Test) to TXT in the topmost CMakeLists.txt of Onboard- SDK-3.9, as follows:
 ![](https://djisdksupport.zendesk.com/attachments/token/Jvio8eTLpa5QNvqsDZ7r2ZRcg/?name=inline-2038992634.png)
3. Perform compilation

    $ mkdir build
    $ cd build
    $ cmake .. -DADVANCED_SENSING=ON
    $ make


Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team<br><a href='https://djisdksupport.zendesk.com/attachments/token/nJB6NcqQPsPNamorBZmHt71fB' target='zd_attach'>CMakeLists.txt</a><br><a href='https://djisdksupport.zendesk.com/attachments/token/pL4nlpN0RU2kmCkVxboGHzC7c' target='zd_attach'>main.cpp</a>
