### ISSUE TITLE
N3/A3 + Lightbridge 2 products discontinuation and SDK implications

### ISSUE THREAD

**Issue by rcabg** [dji-sdk/Onboard-SDK#479]
Hello,

I would like to ask about the discontinuity of the N3/A3 autopilots and Lightbridge 2 products and its SDK implications.

In the past days we have been trying to purchase new units of the A3 autopilots as well as some Lightbridges 2 and we have found that they are not available anymore, at least in Spain. In the official DJI web store, Lightbridge 2 is not available and we have been the entire day talking with the officials Spanish DJI dealers (StockRC, RCInnovations and ElectronicaRC) and all of them have told us that theses products have been discontinued.

Also researching a little bit in the Internet, we can find a few threads talking about the same issue:
- https://forum.dji.com/thread-181101-1-1.html
- https://forum.dji.com/thread-200969-1-1.html
- https://forum.dji.com/thread-180920-1-1.html

Our questions are:
- Is it true that these products are being discontinued?
- What implications does this have for the DJI SDK? N3/A3 are the devices with more freedom when developing with the SDK and many people/universities/companies use them for several purposes.
- Will DJI stop manufacturing autopilots and concentrate on full drones (M600, M210, ...) ? or is it planned to market a new autopilot? (A4, Lightbridge 3, ...)

Thanks in advance!

**Comment by dji-dev** [comment]
Public comment from Lisa Fedane in <a href='https://djisdksupport.zendesk.com/agent/tickets/29576'>Zendesk ticket #29576</a>:<br><br>Please reach out to DJI Sales or DJI After Sales for these questions at Sales@DJI.com and Support@DJI.com

Lisa Fedane
DJI Developer Support

**Comment by jicalder** [comment]
Can you tell us about what was the response from the company about this topic?
I work in a University Lab and i have similar questions about.

**Comment by rcabg** [comment]
Hello @jicalder 

The official response from DJI was basically that they don't know what is going on (I suppose that probably at that time employes didn't know anything yet).

The facts are that they are not available anymore, at least in Spain (we have been asking many different local dealers, also some from other countries) and N3/A3 autopilots are being discontinued as well as Lightbridge 2. 

New SDK version (4.0) drops the support for any of these products and I don't see any movement for releasing a N4/A4 and Lightbridge 3 so far.

That is what I know to this moment, but no official announcement has been done so far. I hope DJI could throw some light to this.

**Comment by jicalder** [comment]
Gracias @rcabg por tu rapida respuesta.
Es una lastima que al dia de hoy no hayan noticias de algun nuevo lanzamiento en esta linea de productos por parte de la compañia. De todas formas necesitaba saber respecto a la compatibilidad del sistema Payload SDK con el controlador de vuelo DJI A3, lo cual no he podido encontrar suficiente informacion.
Saludos
