### ISSUE TITLE
M210 v2rtk connection diagram is transferred to USB. The remote control screen is grayed out. Advancedsensing cannot call x5s camera stream. Unable to read from main Camera 。Terminal showed“  Unable to read from main? Camera lost, retry connecting is displayed.”

### ISSUE THREAD

**Issue by Hust-hsg** [dji-sdk/Onboard-SDK#483]
I used manifold 2 for osdk development. Before that, everything was normal. After I ran the rewritten camera stream callback sample, something happened as the title said. It is normal to unplug the USB remote control, but the main camera of the remote control turns gray and still after plugging in, and the SD card space is 0. We have tried to refresh the firmware, use the configtool setting to use USB flight and other methods, but it has not been resolved.
![IMG_20191116_163307(1)](https://user-images.githubusercontent.com/55015639/68990963-6f143a00-0894-11ea-8c7b-6c5523508551.jpg)
![IMG_20191116_163333(1)](https://user-images.githubusercontent.com/55015639/68990964-6f143a00-0894-11ea-8386-211a2ba24646.jpg)

  When I add / dev / ttyacm0 at the end of the command when I run the routine, I find that I can call the image after running for a period of time, and the remote control can display the main camera image during the running of the program. However, once the program is finished, the image of the main camera of the remote controller will be still gray, and the SD card space is insufficient. And the Ubuntu interface prompts unable to mount 64GB volume.

Hope you can give some advances.

**Comment by dji-dev** [comment]
Public comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/29919'>Zendesk ticket #29919</a>:<br><br>Dear Customer,

Thank you for contacting DJI.

[Q] It is normal to unplug the USB remote control, but the main camera of the remote control turns gray and still after plugging in, and the SD card space is 0.
==> This is a normal phenomenon. When connecting the USB, you can call "./camera-stream-poll-sample "and other samples to obtain the camera video stream. At this time, the RC video stream transmission will return to normal.

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
