### ISSUE TITLE
N3 Manifold 2-G : unable to start the motors with osdk command

### ISSUE THREAD

**Issue by omerikko1** [dji-sdk/Onboard-SDK#495]
Hi,
I'm using N3 Flight Controller along with onboard computer Manifold 2-G with UART communication and 1M baud rate. I am trying to make the motors spin but I get error from the call back:
dji@manifold2:~/catkin_ws$ rosservice call /dji_sdk/sdk_control_authority "control_enable: 1"result: True
cmd_set: 1
cmd_id: 0
ack_data: 2
dji@manifold2:~/catkin_ws$ rosservice call /dji_sdk/drone_task_control "task: 4"
result: False
cmd_set: 1
cmd_id: 1
ack_data: 13

would appreciate any kind of help.
Thanks,
Omer

**Comment by dji-dev** [comment]
Public comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/31428'>Zendesk ticket #31428</a>:<br><br>Dear Omer,

Thank you for contacting DJI.

I noticed that you mentioned in another email (Ticket 31429) that the issue has been resolved.
If you have other issues, it is recommended that you click the hyperlink on the right to fill in more detailed problem information (including the necessary log/screenshot/video),  https://formcrafts.com/a/dji-developer-feedback-en

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
