### ISSUE TITLE
Replacing the flight controller of M100

### ISSUE THREAD

**Issue by kanglei1130** [dji-sdk/Onboard-SDK#503]
It seems that M100 is using N3, can I just buy one A3 and replace it?

Thanks.

**Comment by dji-dev** [comment]
Public comment from Lisa Fedane in <a href='https://djisdksupport.zendesk.com/agent/tickets/31886'>Zendesk ticket #31886</a>:<br><br>This is a hardware question that is best answered by DJI's After Sales team at Support@DJI.com.

DJI Developer Support
