### ISSUE TITLE
Get all data at an instant t (after hardware synchronization)

### ISSUE THREAD

**Issue by erenaud3** [dji-sdk/Onboard-SDK#507]
Hi !

Let us say I want to perform [hardware synchronization](https://developer.dji.com/onboard-sdk/documentation/guides/component-guide-hardware-sync.html).

I would have to call the function:
 ```cpp
void setSyncFreq(uint32_t freqInHz, uint16_t tag = 0);
```

Then, the Flight Controller (FC) would reply me with a message like this on topic with name TOPIC_HARD_SYNC:

```cpp
/*!
 * @brief struct for TOPIC_HARD_SYNC
 */
typedef struct HardSyncData
{
  SyncTimestamp ts; /*!< time stamp for the incoming data */
  Quaternion    q;  /*!< quaternion */
  Vector3f      a;  /*!< accelerometer reading unit: g */
  Vector3f      w;  /*!< gyro reading unit: rad/sec */
} HardSyncData;     // pack(1)
```

Okay great. But then, how can I get all other telemetry data that FC measured when this HardSyncData message were populated ?
Would I have to listen to first message of every others topic  received right after this one ? Would it be precise enough ?

Best regards

**Comment by dji-dev** [comment]
Public comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/32367'>Zendesk ticket #32367</a>:<br><br>Dear Customer,

Thank you for contacting DJI.

Sorry that the Hardware Sync supports time-aligned Data only for IMU, so it only includes Quaternion, accelerometer, and gyro data, not other Topic Data.

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
