### ISSUE TITLE
Support for Z30 advanced sensing on M210 V1

### ISSUE THREAD

**Issue by guischmitd** [dji-sdk/Onboard-SDK#511]
Is there support for the Z30 on M210 V1 planned? My application would benefit a lot from being able to access frames from the Z30 in realtime on the onboard computer we're embedding.

**Comment by dji-dev** [comment]
Agent comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/33580'>Zendesk ticket #33580</a>:<br><br>Dear Customer,

Thank you for contacting DJI.

We usually solve SDK-related problems. According to the information you provide, please send your problem information to support@dji.com. We will arrange for someone to contact you as soon as possible.

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team

**Comment by guischmitd** [comment]
Just to leave a public response for OSDK developers facing this issue, there is **no intention** to add camera stream support for the Z30 on the M210 V1 platform since it's discontinued. Bummer. :/
