### ISSUE TITLE
A3 and OSDK 4.x

### ISSUE THREAD

**Issue by Jai-GAY** [dji-sdk/Onboard-SDK#517]
going forward, [OSDK 4.x onwards,](https://github.com/dji-sdk/Onboard-SDK/releases/tag/4.0.0) A3 is not supported?

**Comment by Phillweston** [comment]
看表格上面说没有A3和N3呀，是不是DJI抛弃了这个型号了

**Comment by dji-dev** [comment]
Dear Customer,

Thank you for contacting DJI.

Sorry that the A3/N3 is not supported in DJI OSDK4.0 at present. but suggest that you can use the OSDK-3.9 version.
