### ISSUE TITLE
VERTICAL_THRUST mode ctrl

### ISSUE THREAD

**Issue by AlexandreBorowczyk** [dji-sdk/Onboard-SDK#53]
Hi,

I would like to confirm the behavior os the VERTICAL_THRUST mode. Specifically what is controled, Is it the total thurst (N) or the motor combine rotation speed (rmp)? Also is the control linear from 0% to 100%?

Thanks very much

Alex

**Comment by lanyusea** [comment]
thrust
linear

**Comment by AlexandreBorowczyk** [comment]
Awesome thx!
