### ISSUE TITLE
"Drone version not obtained error" on connecting DJI Matrice 100 to Raspberry Pi 3

### ISSUE THREAD

**Issue by jcutler2018** [dji-sdk/Onboard-SDK#532]
I am trying to connect my raspberry pi 3 to my DJI M100 drone and run the OSDK on the pi. I cannot get the sample to run on the osdk. I am connecting via the pi's GPIO pins to the drone's UART_CAN2 port. I have tried every solution on every forum post:

-  OSDK ROS version 3.8.1 and OSDK version 3.9 (do they have to be the same?)
- the drone is running firmware version 1.3.1.82 (updated)
- I have updated the pi ROS version 
- The baud rate is the same on the dji assistant 2 app and the sdk launch file (230400)
- I am running a cable from the UART_CAN2 port on the drone to the GPIO pins on the pi 
- The TX and RX pins are connected correctly
- The sdk is enabled in the dji assistant
- I have permission to use the serial port
- The serial port is not being used by another program 
- The controller is in F mode and the dji go app is connected
- App ID and App key are entered correctly  

![image0](https://user-images.githubusercontent.com/66737431/84290674-f9163f80-ab11-11ea-97f3-69aae4c1ac00.jpeg)

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/35673'>Zendesk ticket #35673</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

Have you tried to change the baudrate to 921600 both the drone and OSDK config file ?
Maybe you could have a try and then show the result.

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
