### ISSUE TITLE
Jetson TX2 cmake failed: FFMPEG and pthread_create not found

### ISSUE THREAD

**Issue by avashist003** [dji-sdk/Onboard-SDK#543]
Hey,
I am building the OSDK (4.0) on jetson TX2 platform (Ubuntu 18.04, cmake version 3.10.2, gcc version 7.5). I receive error during the cmake process and the terminal shows **pthread_create - not found and checking the cmake error log states: undefined reference to "pthread_create"**.
It looks like it's not able to find the FFMPEG but I have it installed in my system.(added the screenshot)

When I try it on a separate machine (ubuntu 18.04 and same cmake and gcc version) that works. But not on the Jetson platform. Can you advise on what I should be doing to make it work on the jetson ?

![sc-1](https://user-images.githubusercontent.com/13079690/85434395-dd139480-b53a-11ea-9055-95c4eb7692e7.png)

**Comment by avashist003** [comment]
had to manually install some of the ffmpeg libraries and then it compiled

**Comment by avashist003** [comment]
had to manually install some of the ffmpeg libraries and then it worked

**Comment by nZac** [comment]
For those coming later, I found this to work: `cmake -DFFMPEG_INCLUDE_DIR:STRING=/usr/lib/aarch64-linux-gnu ../`

Ubuntu 18.04
