### ISSUE TITLE
Can I compile on a Raspberry PI 3B + or raspberry PI 4 using DJI Osdk3.9 or 4.0 with Advanced Sensing?

### ISSUE THREAD

**Issue by beyond21299** [dji-sdk/Onboard-SDK#544]
Can I compile on a Raspberry PI 3B + or raspberry PI 4 using DJI Osdk3.9 or 4.0 with Advanced Sensing?

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/36166'>Zendesk ticket #36166</a>:<br><br>If you want to use Advanced Sensing, the CPU should be ARMv8 or X86. The hardware that meets the requirements is theoretically available for the Advanced Sensing function
