### ISSUE TITLE
Getting velocity indoor

### ISSUE THREAD

**Issue by sytelus** [dji-sdk/Onboard-SDK#55]
I was looking in the SDK code and FlighData documentation. It appears that linear velocity is in ground frame and is derived from GPS. Is this correct understanding? I'm looking for getting fused velocity data indoor from IMU. Currently FlightData documentation doesn't seem to have anyway to get this. Is it possible to get velocity from onboard IMU for indoor purposes? 

Another quick question: Does quaternion elements q0, q1, q2, q3, q4 correspond to w, x, y, z respectively?

**Comment by lanyusea** [comment]
1. the velocity has various sources, may be from GPS, may be from IMU, may be from Guidance. Also, may be a fused data from all theses resources.
You can read the velocity from broadcast data together with a reliable flag following. You can check the `appendix` for more detail.

2. yes, but no q4

**Comment by sytelus** [comment]
Thanks!
