### ISSUE TITLE
Cannot find -ldjiosdk-core

### ISSUE THREAD

**Issue by ADlead** [dji-sdk/Onboard-SDK#555]
I downloaded the osdk3.9 on my jetson tx2 and was trying to run the Samples. However, when I try to make and build the sample projects (with CMake), I run into the problem:

`/usr/bin/ld: cannot find -ldjiosdk-core`

The CMake file contains these lines:

`add_executable(${PROJECT_NAME} ${SOURCE_FILES})`
`target_link_libraries(${PROJECT_NAME} djiosdk-core)`

I can't find any lib files like the "*djiosdk-core" in my system
My questions are:

    How do I link the djiosdk-core library?

I am developing on M600 with the JETSON TX2, and Ubuntu 16.04

Thank u so much

**Comment by ADlead** [comment]
I hv solved this problem, thank u

**Comment by YardenLevinger** [comment]
> I hv solved this problem, thank u

How?

**Comment by ADlead** [comment]
> 
> 
> > I hv solved this problem, thank u
> 
> How?

Try cmake the cmakelists.txt at the root dir of this project, which is "Onboard-SDK-3.9/CMakeLists.txt". May fix it.
