### ISSUE TITLE
英文单词拼写错误

### ISSUE THREAD

**Issue by Git-Blue** [dji-sdk/Onboard-SDK#56]
![topic](https://cloud.githubusercontent.com/assets/12869439/15741043/53caa99c-28ea-11e6-928d-29cbd2b28d61.png)

**Comment by naffan2014** [comment]
benefit

**Comment by lanyusea** [comment]
closed because we have updated all codes/docs about the onboard SDK to solve any possible problem.

please reopen the issue if you still suffer the same problem
