### ISSUE TITLE
MANIFOLD 2C

### ISSUE THREAD

**Issue by DimaNyumovich** [dji-sdk/Onboard-SDK#564]
Good afternoon.

Half a year ago we acquired MANIFOLD 2C, but did not use it. Now we tried to start the computer, but Linux could not start working. After that, there was an attempt to install Windows on a computer and now none of the operating systems starts. The question is how can I return to the factory settings?

Thanks a lot.

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/36932'>Zendesk ticket #36932</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

About how to return to the factory settings ,  suggest to send an e-mail to support@dji.com, and they will help you.

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
