### ISSUE TITLE
2 ACM Ports, no ttyUSB 

### ISSUE THREAD

**Issue by aygunbaltaci** [dji-sdk/Onboard-SDK#585]
Hello,
I'm using Ubuntu 18.04 and I am trying to get the OSDK 3.8.1 test program to run. I follow the tutorial for linux here:https://developer.dji.com/onboard-sdk/documentation/quickstart/run-the-sample.html

I use the Matrice 600 Pro as a drone. From the tutorial I know that I need one ttyUSB and one ttyACM but I don't get a ttyUSB, but I have two ACM ports for this. 
 
![Bildschirmfoto vom 2020-07-29 11-17-00](https://user-images.githubusercontent.com/35367387/88807807-770dd300-d1b2-11ea-88d2-b1925a2641c0.png)
![Bildschirmfoto vom 2020-07-29 11-16-35](https://user-images.githubusercontent.com/35367387/88807831-7aa15a00-d1b2-11ea-8cab-c679d9d8d6e0.png)

After I enter the command ./djiosdk-flightcontrol-sample UserConfig.txt I get the error code: 
[2595509.413]ERRORLOG/1 @ initVehicle, L215: Failed to initialize Linker channel
Vehicle not initialized, exiting.

Could you guide me with this problem? Thanks! :)

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/37482'>Zendesk ticket #37482</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

Sorry, There are some questions comfirmed with you.
1、Which cable you used for serial communication?
2、Could you please provide the picture about the hardware connections ?
3、And which platfrom used for the ubuntu1804 ?

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team

**Comment by aygunbaltaci** [comment]
HelloDJI Support Team,
so I use a MicroUSB to USB cable. I plug the MicroUSB into the drone, USB into the PC.
Unfortunately, I didn‘t quite understand your last question. I use Ubuntu 18.04. Here is the exact name: 5.4.0-42-generic 
Here is a picture about the hardware connection. 
![2020-07-30 10 27 06](https://user-images.githubusercontent.com/35367387/88903925-b260de00-d254-11ea-91a6-b54ff64f0d7d.jpg)

Thank you!

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/37482'>Zendesk ticket #37482</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

The serial interface for OSDK named as API, you can check the connections as following
 ![](https://djisdksupport.zendesk.com/attachments/token/I6CEnk1AvPUoXcp5DTwIIAj5C/?name=inline725481733.png)​
The micro USB used to connects with the DJI Assistant2(installed on the pc).

and suggest that you visit the developer website and download the OSDK3.9 document, maybe give you some advice about de hardware connections as above. https://developer.dji.com/document/1be2b992-5862-4eb5-819b-dd6036f76133
 ![](https://djisdksupport.zendesk.com/attachments/token/YzD7IKdtgC7lAFIZcm9niIQ3k/?name=inline-54013465.png)​

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team<br><a href='https://djisdksupport.zendesk.com/attachments/token/I6CEnk1AvPUoXcp5DTwIIAj5C' target='zd_attach'>inline725481733.png</a><br><a href='https://djisdksupport.zendesk.com/attachments/token/YzD7IKdtgC7lAFIZcm9niIQ3k' target='zd_attach'>inline-54013465.png</a>
