### ISSUE TITLE
openCV

### ISSUE THREAD

**Issue by DimaNyumovich** [dji-sdk/Onboard-SDK#589]
Hi there.
I used your link for installation OpenCV for onboard and now I can't find it in your documentation. Will you please remind link.

Thanks a lot.
Dmitry.

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/37647'>Zendesk ticket #37647</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

If you find the link for OSDK software development , and links: https://developer.dji.com/document/e34c3fc4-dc0e-4cbf-b7c0-589b6e941a01

but if you want to install opencv , the official website related opencv is recommanded.

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
