### ISSUE TITLE
how can be creat a simulator drone

### ISSUE THREAD

**Issue by zongoalbert** [dji-sdk/Onboard-SDK#591]
hello , i have a drone phantom 4 pro i want to create a simulator drone using Onboard SDK  , please send me schema explain, how can be connect the drone with my Laptop

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/37741'>Zendesk ticket #37741</a>:<br><br>Hi. I am sorry to tell you that phantom 4 pro doesn't support onboard SDK development.
