### ISSUE TITLE
M300 OSDK USB port not recognized by linux kernel

### ISSUE THREAD

**Issue by XiaoR** [dji-sdk/Onboard-SDK#617]
ARM linux系统，插入OSDK的usb和uart后，串口能识别并正常工作。 USB无法识别。
输入dmesg查看系统消息，显示USB设备的错误为：
device not accepting address 4, error -62
是否是linux内核没有对应驱动？ 应该安装何种驱动？

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/38335'>Zendesk ticket #38335</a>:<br><br>尊敬的客户，

您好！感谢您联系DJI大疆创新。

OSDK接入USB设备为ACM设备，若Linux内核为您自行编译，建议确认一下是否有加载USB ACM驱动。若使用ubuntu，系统应该是有安装相关驱动的。
若有加载驱动，可以通过查看dmesg | grep ACM, 看是否有识别设备。

感谢您的理解与支持,祝您生活愉快!

Best Regards，
DJI大疆创新SDK技术支持

**Comment by XiaoR** [comment]
谢谢，加了驱动后能正常识别了、
