### ISSUE TITLE
 activate SDK version did not match

### ISSUE THREAD

**Issue by stedeba** [dji-sdk/Onboard-SDK#62]

**Comment by stedeba** [comment]
Using:
fw v1.3.1
SDK version: 3.1
Latest DJI Assistant2
I get:
ERROR activateCallback,line 302: activate SDK version did not match
STATUS getDroneVersionCallback,line 252: version ack = 65281
STATUS getDroneVersionCallback,line 253: version crc = 0xA6453AAC
STATUS getDroneVersionCallback,line 255: version ID = 041D292424
STATUS getDroneVersionCallback,line 257: version name = SDK-v1.0 BETA M100-03.01.01.00

Using Linux CommandLine examples.
Any suggestion or fix?

**Comment by stedeba** [comment]
I managed to solve the issue, the bug was on commandline/Linux/conboardsdk/main.cpp...the sdk version was not given to the CoreAPI constructor.

**Comment by lanyusea** [comment]
we just updated the code, please use the latest one

**Comment by lanyusea** [comment]
closed because we have updated all codes/docs about the onboard SDK to solve any possible problem.

please reopen the issue if you still suffer the same problem
