### ISSUE TITLE
current point

### ISSUE THREAD

**Issue by DimaNyumovich** [dji-sdk/Onboard-SDK#629]
Hello!
I would like to know - if my mission consists of, for example, 5 points, how can I get information about the current location of my drone? Which point is passed and which is the next one? Of course without using telemetry. Thanks.

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/38908'>Zendesk ticket #38908</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

The waypoint mission features of OSDK provides the callback function to get current status for user, it mabe give you some advices,
for waypoint v1:
reference API :
setWaypointEventCallback
setWaypointCallback

For waypoint V2:
reference API：
RegisterMissionEventCallback
RegisterMissionStateCallback

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
