### ISSUE TITLE
DJI OnboardSDK 3.0 compile error

### ISSUE THREAD

**Issue by lbdhr** [dji-sdk/Onboard-SDK#63]
After modifying "User_Config.h" file. 
  I open up a terminal inside the "sample/commandline/Linux" directory and type "make" at the command prompt. 
  An error occured with error information "../../../lib/src/DJI_App.cpp:95:25: error: ‘dataflag’ was not declared in this scope
   passData(*enableFlag, dataflag, &broadcastData.gimbal, pdata,".

I am wondering why the error came. And how to solve this problem? Thanks!

**Comment by lbdhr** [comment]
Change 'dataflag' to 'DATA_FLAG', everything is fine now. Maybe a writing mistake.

**Comment by rohitsantdji** [comment]
Fixed in latest commit. 3.1.7 Release should now have this fix.
