### ISSUE TITLE
OSDK sample cannot run

### ISSUE THREAD

**Issue by Kongfanyao** [dji-sdk/Onboard-SDK#639]
when I input   ./djiosdk-flightcontrol-sample UserConfig.txt ,error“Failed to initialize Linker channel Vehicle not initialized,exiting" always exits.
what is wrong with it?I don't know how to solve it.
![IMG_20200920_202611](https://user-images.githubusercontent.com/65019891/93712821-be995580-fb8a-11ea-9e0f-1c10ce6de02c.jpg)
Please answer me,thank you!

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/39346'>Zendesk ticket #39346</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

About the error： Failed to initialize Linker channel Vehicle not initialized
It promts the USB communication works abnormally. Please check the dual-A USB cable connections, and suggest that you visit the website for more info :
https://developer.dji.com/document/1bb1b2dc-9694-4d6b-ad43-fa69c5a10400

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
