### ISSUE TITLE
script->run()的作用是什么？想实现飞机的自动获取控制权限与自动起飞应该怎么写呢？

### ISSUE THREAD

**Issue by lbdhr** [dji-sdk/Onboard-SDK#64]
看源码它是跟在script->addTask("addTask");后面的，我想让飞机自动获取控制权限，就把script->addTask("addTask");改成了script->addTask("ctCA",(UserName)1);，然而这样做了之后就会报错“段错误，核心已转储”。
请教一下想实现飞机的自动获取控制权限与自动起飞应该怎么写呢？

**Comment by lbdhr** [comment]
现在发现使用DJI_API里面的函数可以实现上述功能，但是请问DJIscript的具体作用是什么呢？

**Comment by rohitsantdji** [comment]
DJI Script is an example implementation. If you want to build your own implementation, we recommend that you look at the way API calls are implemented in DJI Script and then make API calls similar to that in your own implementation.
