### ISSUE TITLE
Does SDK has bare-metal version

### ISSUE THREAD

**Issue by Mahdi-Hosseinali** [dji-sdk/Onboard-SDK#654]
I'm looking at using OSDK for a project and was wondering if I want to use stm32 do I have to use RTOS or the bare-metal version of the OSDK also exists? Obviously, I don't want to port the OSDK to bare-metal.

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/40494'>Zendesk ticket #40494</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

The OSDK version 4.0 for STM32 the RTOS should be used . The OSDK 3.9 can used for the bare-metal.
For OSDK version compatible drones, please refer to the developer's official website
 ![](https://djisdksupport.zendesk.com/attachments/token/bS3CdIJygh6hvoImfKsMqMVQa/?name=inline-1472604441.png)​

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team<br><a href='https://djisdksupport.zendesk.com/attachments/token/bS3CdIJygh6hvoImfKsMqMVQa' target='zd_attach'>inline-1472604441.png</a>

**Comment by Mahdi-Hosseinali** [comment]
But they are totally different drone support. So if I want to use the OSDK with say M210 V2 then I can only use version 4.0 which is RTOS, right?

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/40494'>Zendesk ticket #40494</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

Yes， OSDK4.0 needs to be used with RTOS/Linux/ROS.

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
