### ISSUE TITLE
M300 cannot get thumbnail

### ISSUE THREAD

**Issue by choiwooseok** [dji-sdk/Onboard-SDK#659]
https://developer.dji.com/mobile-sdk/documentation/ios-tutorials/MediaManagerDemo.html

with same application

m210 can access thumbnail but m300 cannot

Is there any solutions?

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/40895'>Zendesk ticket #40895</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
For the M300RTK, need to use enterPlayback, exitPlayback to replace the setMode to enter download mode.
Please modify it and try again.

Thanks,

Luce Luo
DJI Developer Support

**Comment by choiwooseok** [comment]
thanks It works!
