### ISSUE TITLE
OSDK4.x: Can you use DJI Assistant 2 for Matrice with gimbal/camera actions? 

### ISSUE THREAD

**Issue by NickHAnderson019** [dji-sdk/Onboard-SDK#666]
**Is it possible with OSDK4.x to command payload actions and use the DJI Assistant 2 for Matrice concurrently?**

Previously, we have been using the M210V1 with OSDK3.9. Using the DJI Assistant 2 for Matrice to simulate the drone flight is key to our ability to develop our system.

However, the M210V2 and OSDK4.x require the USB port of the drone to be connected to the Linux device running the OSDK, otherwise any payload (`GimbalManager`, `CameraManager`) actions throw an error - such as `GimbalManager::resetSync`.

This is not ideal for development since we cannot use the simulator (on MacOS) and connect the USB to the Linux device (there is only one USB port on the drone). Are there any workarounds to this problem?

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/41140'>Zendesk ticket #41140</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

For M210 v2, there is only 1 USB interface to connect the DJI  Assistant2 or OSDK device, therefore, it may no longer be possible to test the above functions when using DJI Assistant2 to simulate. M210 provides a M210Tool that can be used to start the simulator. The related programs and commands are as follows:
 ![](https://djisdksupport.zendesk.com/attachments/token/994TohRVUifjKps9bq3eM8kcM/?name=inline147090719.png)​
CMD：
./M210ConfigTool --usb-port /dev/ttyACM0 --config-file UserConfig.txt --simulation on --latitude 37.422083 --longitude -122.137390

Params：
--usb-port :    USBport
--config-file :  OSDK config file
--simulation ：on/off  （turn on/off simulator）
--latitude/--longitude :  Virtual coordinate point

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
