### ISSUE TITLE
Errorcode 4294967295 for M300 drone and H20 camera

### ISSUE THREAD

**Issue by magenious** [dji-sdk/Onboard-SDK#678]
Hi, 
          We used M300 + h20 to take photo, but currently the osdk return the following error code:
`E1203 13:50:01.879518  6962 dy_control_center.cpp:1088] Start continuous zoom fail. Error code : 4294967295
E1203 13:50:03.883105  6962 dy_control_center.cpp:1126] Camera take photo fail. Error code :4294967295
E1203 13:50:03.883260  6962 dy_control_center.cpp:1134] Set shoot-photo mode as SINGLE fail. Error code :4294967295
E1203 13:50:03.883399  6962 dy_control_center.cpp:1142] Take SINGLE photo fail. Error code :4294967295
E1203 13:50:39.218556  6962 dy_control_center.cpp:1088] Start continuous zoom fail. Error code : 4294967295
E1203 13:50:41.218926  6962 dy_control_center.cpp:1126] Camera take photo fail. Error code :4294967295
E1203 13:50:41.219091  6962 dy_control_center.cpp:1134] Set shoot-photo mode as SINGLE fail. Error code :4294967295
E1203 13:50:41.219220  6962 dy_control_center.cpp:1142] Take SINGLE photo fail. Error code :4294967295
E1203 13:51:23.339634  6962 dy_control_center.cpp:1088] Start continuous zoom fail. Error code : 4294967295
E1203 13:51:30.765729  6962 dy_control_center.cpp:1088] Start continuous zoom fail. Error code : 4294967295
E1203 13:51:58.443671  6962 dy_control_center.cpp:1088] Start continuous zoom fail. Error code : 4294967295`

We used 4.0.1 osdk and our code snippet is:

`
void DY::ControlCenter::takePhoto(){
    //拍照
    LOG(INFO) << "set camera work mode as SHOOT_PHOTO";
    ErrorCode::ErrorCodeType retCode = vehicle->cameraManager->setModeSync(PAYLOAD_INDEX_0, CameraModule::WorkMode::SHOOT_PHOTO, 1);
    if (retCode != ErrorCode::SysCommonErr::Success)
    {
        LOG(ERROR) << "Camera take photo fail. Error code :" << retCode;
        ErrorCode::printErrorCodeMsg(retCode);
    }

    LOG(INFO) << "set shoot-photo mode as SINGLE";
    retCode = vehicle->cameraManager->setShootPhotoModeSync(PAYLOAD_INDEX_0, CameraModule::ShootPhotoMode::SINGLE, 1);
    if (retCode != ErrorCode::SysCommonErr::Success)
    {
        LOG(ERROR) << "Set shoot-photo mode as SINGLE fail. Error code :" << retCode;
        ErrorCode::printErrorCodeMsg(retCode);
    }

    LOG(INFO) << "start to shoot SINGLE photo";
    retCode = vehicle->cameraManager->startShootPhotoSync(PAYLOAD_INDEX_0, CameraModule::ShootPhotoMode::SINGLE, 2);
    if (retCode != ErrorCode::SysCommonErr::Success)
    {
        LOG(ERROR) << "Take SINGLE photo fail. Error code :" << retCode;
        ErrorCode::printErrorCodeMsg(retCode);
    }
}
`

When we got the error code, we dound the photo it took was a mess. So what does the errorcode mean? How to fix it? Thanks.

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/41692'>Zendesk ticket #41692</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

Is the dual A-USB cable connected normally?
It is recommended that you directly use the OSDK origin sample: payloads_async_sample to verify whether it is normal. If there is also an abnormality, please provide a complete demo running terminal log.

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
