### ISSUE TITLE
M300的OSDK enable

### ISSUE THREAD

**Issue by github4529** [dji-sdk/Onboard-SDK#689]
M210使用DJI Pilot 版本1.9.0 在飞控参数设置中，最下面有扩展IO选项（OSDK通信串口 enable）
而M300使用DJI Pilot 版本1.9.0R 没有扩展IO选项，正常吗

使用OSDK编程，提示我SDK没有enable，已连接DJI Assistant2使OSDK enable，但是app里M300的版本没有这个选项

**Comment by dji-kyle** [comment]
M300 机型不支持扩展IO功能。
