### ISSUE TITLE
Zoom control of the camera mounted on the matrice600pro using OSDK 3.9

### ISSUE THREAD

**Issue by yoshida072** [dji-sdk/Onboard-SDK#698]
The following sample code does not work for zoom in and zoom out. https://github.com/dji-sdk/Onboard-SDK/blob/3.9/sample/platform/linux/camera-gimbal/camera_ gimbal_sample.cpp#L303

Gimbal control using the following sample code is successful. https://github.com/dji-sdk/Onboard-SDK/blob/3.9/sample/platform/linux/camera-gimbal/camera_gimbal_sample.cpp#L39

Does anyone know how to do zoom in and zoom out with OSDK 3.9? 
Thanks for your help.

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/42512'>Zendesk ticket #42512</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

Regarding the code you provided, L303 and L39, which correspond to different functions.

please refer to the main function notes.
https://github.com/dji-sdk/Onboard-SDK/blob/295915e6da116aa2871760d3478bba7ebab2f5d9/sample/platform/linux/camera-gimbal/main.cpp#L55
 ![](https://djisdksupport.zendesk.com/attachments/token/Y93wb4d8uH59UT0bnFdF8a1eE/?name=inline1167058519.png)​

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team<br><a href='https://djisdksupport.zendesk.com/attachments/token/Y93wb4d8uH59UT0bnFdF8a1eE' target='zd_attach'>inline1167058519.png</a>

**Comment by yoshida072** [comment]
Thank you for your answer.
I could not zoom by typing a or b on the keyboard.
Do the M600PRO and Z30 support zooming via OSDK?
________________________________

**Comment by dji-kyle** [comment]
The following forum community is recommanded for you, if the problem persists, or new questions about the DJI SDK,
https://djisdksupport.zendesk.com/hc/en-us/community/topics
