### ISSUE TITLE
DJI Simulator swarm support - fake GPS data in PyGame Simulator?

### ISSUE THREAD

**Issue by YamacTan** [dji-sdk/Onboard-SDK#700]
I am using N3 flight controller with an onboard computer module by implementation of Onboard SDK.

I want to ask that, does the simulator in DJI Assistant 2 support swarm drone simulation if I will buy and connect second N3 controller in the ground computer? If does not, can I use a different simulator which is written with PyGame library in Python by using a fake GPS data script? 

Any ideas or reccomendations will be very supportive for swarm simulation.
Thanks.
Y.

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/42553'>Zendesk ticket #42553</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

Sorry, currently DJI Assistant2 does not support simultaneous access to multiple drone or flight controllers for simulation, only one can be recognized.

And DJI drones also only support DJI Assistant2 for simulation.

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
