### ISSUE TITLE
What version of FFMPEG does OSDK4.0.1 rely on

### ISSUE THREAD

**Issue by github4529** [dji-sdk/Onboard-SDK#703]
I Use the newest version FFMPEG cannot support. Maybe it depends on a lower version of FFMPEG?

**Comment by github4529** [comment]
MANIFOLD 2G with FFMPEG without NVENC-support.
I'd like compile FFMPEG with code.But the version ...

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/42858'>Zendesk ticket #42858</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

The OSDK demo rely on ffmpeg version 2.8.15，If you use the newest version ffmpeg, you may need to modify the implementation of demo related decoding functions.
 ![](https://djisdksupport.zendesk.com/attachments/token/wyQdDKRDEODt7AaqD6JsgSEbW/?name=inline1411065446.png)​


Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team<br><a href='https://djisdksupport.zendesk.com/attachments/token/wyQdDKRDEODt7AaqD6JsgSEbW' target='zd_attach'>inline1411065446.png</a>

**Comment by github4529** [comment]
nvidia-smi not found 
DJI JETSON TX2 without nvidia driver?
I see it with CUDA9.0

**Comment by dji-kyle** [comment]
Please consult the support@dji.com for more about manifold 2 production info.
