### ISSUE TITLE
M100 + Z30 + Compatible SBC?

### ISSUE THREAD

**Issue by fightforge** [dji-sdk/Onboard-SDK#709]
Hi,
I need to get video feed onboard from an M100 with Z30 but I would to know if I could use other onboard computer instead manifold. My idea is to stream video feed through network cable or HDMI cable.
Could you suggest some cheap SBC to use to get only video feed from Z30?

Thanks to all

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/43011'>Zendesk ticket #43011</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

OSDK advance sensing function (onboard computer to obtain video stream) only supports M210 series and M300 drones.
For M100, the official only supports M100 + X3 to obtain camera video stream through manifoldcam, which is based on manifold.
About Manifold-Cam:
https://github.com/dji-sdk/Manifold-Cam

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
