### ISSUE TITLE
Flight Controller Serial Number

### ISSUE THREAD

**Issue by a2hill** [dji-sdk/Onboard-SDK#71]
Not sure if I'm overlooking it, but is there no way to query the serial number from the Flight Controller?

**Comment by lanyusea** [comment]
1. You want to do it by using Onboard SDK?
2. if 1 is true, do you want a UID to separate different drones or you really want to check the serial number?

**Comment by a2hill** [comment]
1. Yes I want to use the onboard SDK to do it.
2. UID would be fine

**Comment by lanyusea** [comment]
As I remember, there is some bytes describing drone's UID in the ack of (0x00, 0x00): Get Protocal Version. You can printf the ack result to check.
We use it to allow the code separate different drones when swarm.

**Comment by a2hill** [comment]
Ahh got it, thanks

**Comment by lanyusea** [comment]
@a2hill  does it satisfy your requirement?

**Comment by a2hill** [comment]
@lanyusea I've been looking at VersionData returned from getDroneVersion and unfortunately it seems to be empty. Do I need to send a 0x00 0x00 and parse the ACK manually?

**Comment by rohitsantdji** [comment]
@a2hill what flight controller and firmware are you using?

**Comment by a2hill** [comment]
M100 with firmware 1.1.0.10+

**Comment by rohitsantdji** [comment]
We will be releasing a hotfix soon that should take care of this issue. For now, please use the void-return-type getDroneVersion with your own callback as an argument (you can look at getDroneVersionCallback in DJI_API.cpp and implement something very similar, except instead of printing out values using API_LOG you can execute your own logic).

**Comment by a2hill** [comment]
Great thanks this worked as far as getting the data! So can the version ID returned be used as a UID of the aircraft?

**Comment by rohitsantdji** [comment]
Great! yes, it can.
