### ISSUE TITLE
请问osdk是否能让飞机按偏移量飞行？

### ISSUE THREAD

**Issue by addriumruss** [dji-sdk/Onboard-SDK#711]
m300, osdk3.9, 树莓派
希望通过osdk指示飞控向前、后、左右、上下、旋转等一个指定距离，例如向前飞行5米，向左转动30度等。
请问是否有示例程序，谢谢!

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/43053'>Zendesk ticket #43053</a>:<br><br>尊敬的客户，

您好！感谢您联系DJI大疆创新。

支持的，可以参考官方demo：djiosdk-flightcontrol-sample
另M300 仅支持OSDK 4.x 版本推荐使用release版本4.0.1版本，或者使用master分支版本。
关于飞行控制也可以参考开发者论坛相关帖：
https://bbs.dji.com/forum.php?mod=viewthread&tid=258561

感谢您的理解与支持,祝您生活愉快!

Best Regards，
DJI大疆创新SDK技术支持
