### ISSUE TITLE
How to solve No such file or directory?I want to compile C++ on raspberry pi

### ISSUE THREAD

**Issue by tsai-10957111** [dji-sdk/Onboard-SDK#718]
[
![擷取](https://user-images.githubusercontent.com/77483274/105349726-17eebf80-5c25-11eb-9b67-425d00e492fc.PNG)
](url)

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/43264'>Zendesk ticket #43264</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

To use OSDK, you need to include the DJI OSDK library and the corresponding header files. It is recommended to check your application code project environment

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team

**Comment by tsai-10957111** [comment]
May I add the dji osdk library to the .cpp file of time_sync_poll_sample?

**Comment by tsai-10957111** [comment]
How to join the dji osdk library?

**Comment by Hepan02** [comment]
Hi tsai.

Add this line to CMakeList.txt in your sample.

```
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/../../../core/inc)
include_directories(include /home/pi/Onboard-SDK/sample/platform/linux/common)
include_directories(include /home/pi/Onboard-SDK/sample/platform/linux/hal)
include_directories(include /home/pi/Onboard-SDK/sample/platform/linux/osal)
include_directories(include /usr/local/include)
include_directories(include /usr)
```
