### ISSUE TITLE
How to set bitrate

### ISSUE THREAD

**Issue by github4529** [dji-sdk/Onboard-SDK#719]
When Use StartH264Stream or Get image sample，how to set the camera bitrate

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/43280'>Zendesk ticket #43280</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

Sorry, OSDK does not support setting video stream format and parameters.Bitrate and video stream are only related to the camera.

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
