### ISSUE TITLE
How send image data from OSDK to MSDK？

### ISSUE THREAD

**Issue by Jessicahjj** [dji-sdk/Onboard-SDK#727]
m300rtk, osdk4.1, tx2
希望通过osdk发送目标检测的结果图像到msdk。
MobileDevice类的函数sendDataToMSDK (uint8_t *data, uint8_t len)，但是函数实现中要求len小于100。一般图像数据不能可能通过这种方式，请问有其他办法吗？谢谢!

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/43732'>Zendesk ticket #43732</a>:<br><br>尊敬的开发者，

您好！感谢您联系DJI大疆创新。

M300机型和OSDK 4.x版本，可以考虑评估使用MOP（SDK互联互通）功能传输图像数据，相关功能可参考开发者官网相关功能介绍：
https://developer.dji.com/cn/document/e37514a6-5803-4abf-a5b6-6da844bd56f6

感谢您的理解与支持,祝您生活愉快!

Best Regards，
DJI大疆创新SDK技术支持
