### ISSUE TITLE
关于DJI Assistant 2支持的无人机机型

### ISSUE THREAD

**Issue by kimberz-git** [dji-sdk/Onboard-SDK#728]
您好:
     我在贵官网查看DJI Assistant 2的软件的时候，看了下几个DJI Assistant 2的版本， 下面所列出来的可支持的机型都没有M600pro这一款，请问现在官网列出的DJI Assistant 2这几个版本都不支持M600 pro吗？有可支持该版本呢的DJI Assistant 2 版本吗？

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/43849'>Zendesk ticket #43849</a>:<br><br>尊敬的开发者，

您好！感谢您联系DJI大疆创新。

M600 Pro机型使用的DJI Assistant2请前往下述链接下载：
https://www.dji.com/cn/downloads/softwares/assistant-dji-2-for-matrice
 ![](https://djisdksupport.zendesk.com/attachments/token/eutnUanlxaMbztEui5yYJjoFl/?name=inline-435684679.png)​

感谢您的理解与支持,祝您生活愉快!

Best Regards，
DJI大疆创新SDK技术支持<br><a href='https://djisdksupport.zendesk.com/attachments/token/eutnUanlxaMbztEui5yYJjoFl' target='zd_attach'>inline-435684679.png</a>

**Comment by kimberz-git** [comment]
> Agent comment from kyle.cai in [Zendesk ticket #43849](https://djisdksupport.zendesk.com/agent/tickets/43849):
> 
> 尊敬的开发者，
> 
> 您好！感谢您联系DJI大疆创新。
> 
> M600 Pro机型使用的DJI Assistant2请前往下述链接下载：
> https://www.dji.com/cn/downloads/softwares/assistant-dji-2-for-matrice
> ![](https://camo.githubusercontent.com/231702b03513bc03b51ea036e5c308e56801316a141325206cb41a985ec171e6/68747470733a2f2f646a6973646b737570706f72742e7a656e6465736b2e636f6d2f6174746163686d656e74732f746f6b656e2f6575746e55616e6c78614d627a744575693579594a6a6f466c2f3f6e616d653d696e6c696e652d3433353638343637392e706e67)​
> 
> 感谢您的理解与支持,祝您生活愉快!
> 
> Best Regards，
> DJI大疆创新SDK技术支持
> [inline-435684679.png](https://djisdksupport.zendesk.com/attachments/token/eutnUanlxaMbztEui5yYJjoFl)

好的，多谢
