### ISSUE TITLE
A simple program for reading telemetry data?

### ISSUE THREAD

**Issue by WenTheProgrammer** [dji-sdk/Onboard-SDK#731]
I have an M600 Pro and an onboard Ubuntu computer (RPi) which is used for reading data from the A3 Pro. The version of OSDK that I used is 3.9. I have been able to successfully compile and run the sample telemetry program. Since I do not have experience in C++, I'm not sure how to modify the sample program (telemetry_sample.cpp) or just write one from scratch for my own purpose. All I need is a simple program that reads and saves GPS (fused lat/lon/alt) and quaternion (x,y,z,w) information with specified frequency to file. I also need timestamps for the outputs. Any help is greatly appreciated!

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/43979'>Zendesk ticket #43979</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

The demo：telemetry_sample.cpp provides the sample to get telementry data, and save data to the file, it maybe give you some advices.
subscribeToDataAndSaveLogToFile(Vehicle* vehicle, int responseTimeout)
 ![](https://djisdksupport.zendesk.com/attachments/token/BoQLKBQrpItqnvWcGs5MQtEIc/?name=inline-1797914743.png)​

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team<br><a href='https://djisdksupport.zendesk.com/attachments/token/BoQLKBQrpItqnvWcGs5MQtEIc' target='zd_attach'>inline-1797914743.png</a>
