### ISSUE TITLE
TOPIC_GPS_FUSED for M600 Pro

### ISSUE THREAD

**Issue by WenTheProgrammer** [dji-sdk/Onboard-SDK#734]
I have a few questions regarding the telemetry topic TOPIC_GPS_FUSED for my M600 Pro:
1. Are the fused X-Y positions the results of fusing signals from all three GNSS units or only one GNSS unit of A3 Pro with IMU?
2. Does M600 Pro have a preference for using which GNSS unit first when all three of them are available?
3. Is there a way to tell the signals of which GNSS unit are being used through OSDK?

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/44084'>Zendesk ticket #44084</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

The GPS data is sent to the OSDK by the flight controller fusion. The multiple GNSS units of the M600 Pro are mutually backup, and only one can be used at the same time. You can check which one you are using through the remote control and APP. I'm sorry that the GNSS unit used cannot be distinguished through OSDK. Only the data sent by the flight controller can be obtained through TOPIC.

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
