### ISSUE TITLE
Gimbal yaw angle relative to aircraft heading

### ISSUE THREAD

**Issue by jaehanIm** [dji-sdk/Onboard-SDK#737]
Hello.

I've realized that there is a class returning 'gimbal yaw angle relative to aircraft heading' in MSDK.
Name of the property is 'yawRelativeToAircraftHeading' in DJIGimbalState class.

However, i cannot find same information in OSDK.
Is there any class in OSDK that returns this same information?

Thanks.
JH Im.

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/44284'>Zendesk ticket #44284</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

Sorry, currently OSDK obtains gimbal yaw angle based on NED coordinates，It may be necessary to obtain the head direction of the aircraft quaternion computer indirectly.

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
