### ISSUE TITLE
Create shared lib

### ISSUE THREAD

**Issue by user651** [dji-sdk/Onboard-SDK#739]
Hello,

i am currently working on a project where we want to use the osdk from a java environment (since java is the language of the main project). For this i want to modify the build files in order to get shared libs for osdk core and advanced sensing. I first built the project like it is described in the manual, where the project is built correctly. After modifying the CMakeFiles.txt in osdk-core/ and osdk-core/advanced-sensing/ (replace STATIC in add_library with SHARED), after fresh cmake and make the libs are built successfully (according to make) as .so files. 
During linking of the first example an error occurs  (![make](https://user-images.githubusercontent.com/79930301/109684949-10ee9180-7b81-11eb-834a-3db4489d01e6.PNG)).

Is there a way to obtain working shared libs of the osdk? Or are there other ways to communicate from java with the osdk?

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/44436'>Zendesk ticket #44436</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

Please check if advance sensing lib has been built and linked
 ![](https://djisdksupport.zendesk.com/attachments/token/XVOHS4gHqqCoSBESgUaF2cl4p/?name=inline-1131313165.png)​

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team<br><a href='https://djisdksupport.zendesk.com/attachments/token/XVOHS4gHqqCoSBESgUaF2cl4p' target='zd_attach'>inline-1131313165.png</a>
