### ISSUE TITLE
Can't activate or read data from M600

### ISSUE THREAD

**Issue by TheJerms** [dji-sdk/Onboard-SDK#74]
Followed the instructions on the Onboard SDK website, but once I confirm the port is open and hit activate in the Qt example, nothing happens. Nothing also happens when I hit obtain control. Any advice would be appreciated.

Other things to note:
- OES is a Windows laptop running Qt
- Baud rates are synced to 115200 through a USB port
- [Screenshot](https://postimg.org/image/uajttz06d/)
- Would like to read flight telemetry data from the M600

**Comment by lanyusea** [comment]
the baudrate in your screenshot is 230400 instead of 115200

**Comment by TheJerms** [comment]
* Oops I must have changed it back to 230400 after testing. It gives the same result with 115 200 on both the assistant and the GUI.

**Comment by lanyusea** [comment]
em....  could you check if there are data stream sent from A3? by using some software like serial port monitor maybe this one https://sourceforge.net/projects/realterm/

**Comment by TheJerms** [comment]
Used the Free Device Monitoring Studio, I see the program writing to the port but not reading anything. Also this is what the wiring looks like on the A3 (not sure if there is an issue here): [wiring](https://postimg.org/image/duay7z58j/)

**Comment by TheJerms** [comment]
* Regarding the previous image:
White = RX
Green = TX
Black = GND

**Comment by lanyusea** [comment]
if there is no data, it seems to be a hardware config issue.

the pin of API (from left to right) is: VCC GND TX RX 
   (the figure in our document is actually upside down compared with the real situation
  which means you should connect GND to the GND of your USB-TTL, and connect the TX to your RX, connect the RX to your TX

**Comment by TheJerms** [comment]
Oh I see. It's working now! Thank you!

**Comment by lanyusea** [comment]
:)
