### ISSUE TITLE
Handshake with drone but can't run the sample

### ISSUE THREAD

**Issue by gerhardmalberg88** [dji-sdk/Onboard-SDK#741]
Hello,
I got handshake with drone but no matter what sample I try to run it gives same error.

- UserConfig.txt file set up done correctly
- DJI ASSISTANT app set up correctly
- Logged and opened the drone in DJI GO app
- Permission given to USB/ACM
- I have plugged in both cables the UART and also USB
- Drone blinks green light every 1 second 

My setup:
DJI M100
OSDK 4.1.0
Ubuntu 18.04
Nvidia Jetson Nano Dev Kit

UserConfig.txt file looks like this, xxxx replaced with id and key
app_id : xxxx
app_key : xxxx
device : /dev/ttyUSB0
baudrate : 921600
acm_port : /dev/ttyACM0

Ideas:
Is the L298 an issue? Advanced sensing should not be on, I m running the DJI samples. Project was build not using ADVANCED SENSING neither WAYPOINT features.
Can it assume that I m using advanced sensing somehown in DJI sample codes?
Version compatibility problems?

uwb5@uwb5-desktop:~/uwb/Onboard-SDK/build/bin$ ./djiosdk-logging-sample UserConfig.txt
Read App ID
User Configuration read successfully. 

[499861.928]STATUS/1 @ getDroneVersion, L1702: ret = 0
[499861.928]STATUS/1 @ parseDroneVersionInfo, L1122: Device Serial No. = 041DF31988
[499861.928]STATUS/1 @ parseDroneVersionInfo, L1124: Firmware = 3.1.10.0
[499861.928]STATUS/1 @ parseDroneVersionInfo, L1127: Version CRC = 0xA6453AAC
[499861.928]STATUS/1 @ functionalSetUp, L279: Shake hand with drone successfully by getting drone version.
[499861.928]ERRORLOG/1 @ functionalSetUp, L298: Only support M210 V2 series and M300!

[499861.928]STATUS/1 @ activate, L1329: version 0x3010A00

Segmentation fault (core dumped)

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/44818'>Zendesk ticket #44818</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

The M100 only supports OSDK version 3.9 and below, and OSDK 3.9 is recommanded.
 ![](https://djisdksupport.zendesk.com/attachments/token/7hLYcW2M6onVEOYB5aUrIerxt/?name=inline187353425.png)​

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team<br><a href='https://djisdksupport.zendesk.com/attachments/token/7hLYcW2M6onVEOYB5aUrIerxt' target='zd_attach'>inline187353425.png</a>

**Comment by gerhardmalberg88** [comment]
Hello,

Using release 3.9.0 solved the problem.

Thank You,
Best Regards,
Gerhard
