### ISSUE TITLE
subscribeFrontStereoDisparity function causes segmentation fault if replaced in stereo_vision_single_thread_sample.cpp

### ISSUE THREAD

**Issue by ahmadhasan2k8** [dji-sdk/Onboard-SDK#743]
If I replace 
```
case 'b':
    {
      vehicle->advancedSensing->subscribeFrontStereoVGA(AdvancedSensingProtocol::FREQ_20HZ, &stereoImgVGACallback, NULL);
      isVGA = true;
    }
```
with 
```
 case 'b':
    {
        vehicle->advancedSensing->subscribeFrontStereoDisparity(
            &stereoImgVGACallback, NULL);
        isVGA = true;

    }
```
and comment out the callback function the first one continues to run as expected but second one produces a segmentation fault.

gdb trace is 
```
0x000055555565f66d in DJI::OSDK::AdvancedSensingProtocol::send (this=0x0, cmd=0x7fffffffd6c0, 
    data=0x7fffffffd811, data_len=200)
    at /home/$USER/dji_ws/Onboard-SDK/osdk-core/advanced-sensing/protocol/src/dji_advanced_sensing_protocol.cpp:134
134	  return sendInterface((void*)&cmdContainer);

``` 
Not sure why, is the disparity image not being published? Can we expect subscribeFrontStereoDisparity to return a disparity/depth image directly?

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/45199'>Zendesk ticket #45199</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

About disparity/depth image，please refer to the sample：
https://github.com/dji-sdk/Onboard-SDK/blob/2c38de17f7aad0064056f27eaa219d4ed30ab82a/sample/platform/linux/advanced-sensing/stereo_vision_depth_perception_sample/stereo_vision_depth_perception_sample.cpp#L106

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
