### ISSUE TITLE
请问OSDK可以设置焦距环吗

### ISSUE THREAD

**Issue by Challovactor** [dji-sdk/Onboard-SDK#744]
相机设置为MANUAL模式后，没有找到可以设置焦距环的函数，请问焦距环的值可以自定义设置吗？
![image](https://user-images.githubusercontent.com/16700966/111931997-6a4e3e80-8af7-11eb-8294-4ee90e596e39.png)

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/45283'>Zendesk ticket #45283</a>:<br><br>尊敬的开发者，

您好！感谢您联系DJI大疆创新。

当前OSDK不支持设置焦距环，可以评估使用设置变焦API，参考代码文件：
https://github.com/dji-sdk/Onboard-SDK/blob/master/osdk-core/api/inc/dji_camera_manager.hpp

感谢您的理解与支持,祝您生活愉快!

Best Regards，
DJI大疆创新SDK技术支持
