### ISSUE TITLE
GPS spoofing problem

### ISSUE THREAD

**Issue by deadman2000** [dji-sdk/Onboard-SDK#745]
Hi guys, 
We have a question for you regarding drone operation from SDK:

1). In our country jamming is real problem. Amount of places where we can face it really huge and mostly they made to harm DJI drones.
2). Most of them made for changing coordinates on NFZ zones (airport). 
3). In this case drone start landing without ability to operate him

We have two questions here
If we are flying through SDK and we catch jamming , what shall we do? 

If drone land down automatically without control, how sensers will operate? If they will see obstacle – would it stop or now while landing in NFZ? How sensors will act in collision prevention while landing in NFZ?

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/45315'>Zendesk ticket #45315</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

Sorry, if the GPS is interfered and the drone starts to land, the SDK cannot control it. It is recommended to stay away from the GPS interference area when using OSDK to control the drone.

For more information about NFZ landing and control, you can also contact DJI after-sales (support@dji.com) with email.

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
