### ISSUE TITLE
程序运行一段时间后自动core dump ，提示无法获得无人机版本；M300+OSDK4.1

### ISSUE THREAD

**Issue by Chauncy-Guo** [dji-sdk/Onboard-SDK#756]
M300搭配OSDK4.1时产生的错误：

osdk的程序正常运行一段时间后，OSDK会自动与飞机断开链接，core dump上一行输出提示与飞机失去链接。再次运行编译后的程序，则会报无法获得无人机版本，请检查TX&RX。我的TX和RX顺序一直是正常与飞机连接的，并且Assistant也将OSDK的选项进行了开启。

此时重启M300无人机才能恢复正常。

报错信息（从其他人的github中复制的，与我的 报错相同）：
ERRORLOG/1 @ getDroneVersion, L1377: Drone version not obtained! Please do not proceed.
Possible reasons:
	Serial port connection:
		* SDK is not enabled, please check DJI Assistant2 -> SDK -> [v] Enable API Control.
		* Baudrate is not correct, please double-check from DJI Assistant2 -> SDK -> baudrate.
		* TX and RX pins are inverted.
		* Serial port is occupied by another program.
		* Permission required. Please do 'sudo usermod -a -G dialout $USER' (you do not need to replace $USER with your username). Then logout and login againscalder@ubuntu1:~/dji_SDKs/OSDK_37/Onboard-SDK/build/bin$ ./djiosdk-flightcontrol-sample UserConfig.txt 
Read App ID
User Configuration read successfully.

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/46333'>Zendesk ticket #46333</a>:<br><br>尊敬的开发者，

您好！感谢您联系DJI大疆创新。

提供的报错信息显示串口不通或者通信异常，据您的描述为出现coredump后出现的，建议先排查core dump产生的地方或影响，再排查是否影响了串口通信。

感谢您的理解与支持,祝您生活愉快!

Best Regards，
DJI大疆创新SDK技术支持
