### ISSUE TITLE
M210-v1 w/ OSDK 3.9 -  Can't retrieve communication with main camera.

### ISSUE THREAD

**Issue by rodbelisario** [dji-sdk/Onboard-SDK#762]
Hello, 

we developed an application that captures frames from DJI M210-v1's main camera using OSDK 3.9 on NVIDIA Jetson-Nano. The program works well but sometimes it loses connection with the main camera during flight.

To try to restore connection by software we tried the code bellow that tries to retrieve connection when 5 seconds have passed without a new frame. But once lost connection, it isn't being restored. Any idea about why this is happening? 

```C++
// some previous code to establish communication between drone and nvidia jetson-nano...

bool mainCamResult = false;

mainCamResult = vehicle->advancedSensing->startMainCameraStream();
if (!mainCamResult)
{
        std::cout << "Failed to open MAIN Camera" << std::endl;
}

time_t last_frame_time = time(NULL);

while (true){
    if (mainCamResult && vehicle->advancedSensing->newMainCameraImageReady())
    {
        if (vehicle->advancedSensing->getMainCameraImage(mainImg))
        {
            last_frame_time = time(NULL);
            // Do some process...
        }
    }
    if ((time(NULL) - last_frame_time) >= 5)    // after 5 secs without new frame
    {
        mainCamResult = false;
        vehicle->advancedSensing->stopMainCameraStream();
        mainCamResult = vehicle->advancedSensing->startMainCameraStream();
        if (!mainCamResult)
        {
            std::cout << "Failed to open MAIN Camera" << std::endl;
        }
        else
        {
            std::cout << "Communication with MAIN Camera restored." << std::endl;
        }
    }
}
```

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/47025'>Zendesk ticket #47025</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

I would like to ask whether the connection loss is only occured during the actual flight? If so, please ensure that the USB hardware connection does not loosen during the flight and cause the USB communication to be disconnected.

If it also occured when the drone is stationary on the ground, you can operate"ping 192.168.42.2" (M210 drone IP) to check and ensure the USB commnuniction works.

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team<br><p><em><small>added by Git-Zen</small></em></p>
