### ISSUE TITLE
编译OSDK4.1出错

### ISSUE THREAD

**Issue by LiuXihao** [dji-sdk/Onboard-SDK#763]
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/home/nano/DJI/Onboard-SDK-4.1/osdk-core/FFMPEG_INCLUDE_DIR
   used as include directory in directory /home/nano/DJI/Onboard-SDK-4.1/osdk-core

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/47034'>Zendesk ticket #47034</a>:<br><br>尊敬的开发者，

您好！感谢您联系DJI大疆创新。

报错显示找不到ffmpeg，OSDK sample中有用到ffmpeg解码，可以先确认并安装ffmpeg后再编译，推荐使用版本为2.8.15，另OSDK 及Sample推荐环境可以参考下表：
 ![](https://djisdksupport.zendesk.com/attachments/token/zi5CZmWqO54Lyfk68b7c2415q/?name=inline-1599884883.png)​

感谢您的理解与支持,祝您生活愉快!

Best Regards，
DJI大疆创新SDK技术支持<br><a href='https://djisdksupport.zendesk.com/attachments/token/zi5CZmWqO54Lyfk68b7c2415q' target='zd_attach'>inline-1599884883.png</a><br><p><em><small>added by Git-Zen</small></em></p>
