### ISSUE TITLE
请问下M300自带的FPV镜头是定焦的还是变焦的呢？在手册中没有找到相关参数

### ISSUE THREAD

**Issue by Chauncy-Guo** [dji-sdk/Onboard-SDK#765]
请问FPV摄像头到底是定焦的还是自动变焦的呢？

现在自己需要做fpv摄像头的图像处理，所以需要知道fpv镜头的相关参数，烦请发下相关参数吧！！谢谢

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/47176'>Zendesk ticket #47176</a>:<br><br>您好，产品参数问题请联系 support@dji.com<br><p><em><small>°°°</small></em></p>
