### ISSUE TITLE
How to get aircraft  head direction

### ISSUE THREAD

**Issue by github4529** [dji-sdk/Onboard-SDK#778]
How to get aircraft head direction?

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/48456'>Zendesk ticket #48456</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

Yes, you can calculate the drone attitude with the quaternion.

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
<br><p><em><small>°°°</small></em></p>
