### ISSUE TITLE
不能同时启动两个OSDK程序吗

### ISSUE THREAD

**Issue by github4529** [dji-sdk/Onboard-SDK#779]

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/48512'>Zendesk ticket #48512</a>:<br><br>尊敬的开发者，

您好！感谢您联系DJI大疆创新。

无人机只能同时与一个OSDK程序进行通信，不能同时启动两个OSDK程序，可以评估在同一个程序中启用多个OSDK功能。

感谢您的理解与支持,祝您生活愉快!

Best Regards，
DJI大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>

**Comment by github4529** [comment]
通过订阅TOPIC_GPS_FUSED获取的Latitude":0.403783,"Longitude":1.976468,
可见卫星数为10左右

通过RTK获取的经纬度为23 ,113
范例为telemetry里面的，为何GPS获取的经纬度这么奇怪
