### ISSUE TITLE
Can't see data or antennae for RTK

### ISSUE THREAD

**Issue by TheJerms** [dji-sdk/Onboard-SDK#78]
I recently purchased the D-RTK and Datalink Pro for high-accuracy GPS location of my M600, but after completing the setup as described in the manuals, I can't pull data through the Onboard SDK and the antennae don't appear in DJI Assistant 2 for the M600. It's just one Ground System and one Air System, in full duplex mode. When set up in the field, both Ground System and Air System have green lights on the D-RTK's and Datalink Pros. But I can't set antennae offsets, and I am recording zeros for the RTK Latitude and Longitude. Please advise!

**Comment by lanyusea** [comment]
if you cannot find or config the RTK device in DJI Assistant2, it means the hardware are not well connected or configured to A3.

em.... maybe contact the after-sale support?
