### ISSUE TITLE
SDK for DJI mini 2

### ISSUE THREAD

**Issue by AlexanderPretel** [dji-sdk/Onboard-SDK#782]
Hi, has the SDK for the mini 2 been contemplated?

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/48639'>Zendesk ticket #48639</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

OSDK does not support DJI mini 2, Are you inquiry about Mobile SDK ?

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
<br><p><em><small>°°°</small></em></p>

**Comment by AlexanderPretel** [comment]
Hello again.  Yes, specifically with the mobile SDK for Android and IOS, do
you have any idea when they release that SDK from the mini 2 and mavic 2S?

-----------------

Cordialmente,


Alexander Pretel Diaz

Estudiante Ingeniería Topográfica
Representante Estudiantil ante el Comité del Programa Académico de
Ingeniería Topográfica
Facultad de Ingeniería
Universidad del Valle
Tel: 3166215704

Santiago de Cali-Colombia
2019-2
V. M.

**Comment by dji-kyle** [comment]
Please visit Mobile SDK Repository：
https://github.com/dji-sdk/Mobile-SDK-iOS
https://github.com/dji-sdk/Mobile-SDK-iOS
