### ISSUE TITLE
Only the SINGLE direction subscription is allowed in current OSDK version. 

### ISSUE THREAD

**Issue by TroalBrave** [dji-sdk/Onboard-SDK#783]
您好！
机型M300-RTK，板载计算机型号 Manifold 2G。
我现在使用OSDK订阅多个方向的红外传感器，就会报如下错误，请给予帮助，谢谢。
Only the SINGLE direction subscription is allowed in current OSDK version.

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/48679'>Zendesk ticket #48679</a>:<br><br>尊敬的开发者，

您好！感谢您联系DJI大疆创新。

OSDK本身不支持同时订阅多个方向上的视觉图像获取，可以尝试使用多线程来处理。

感谢您的理解与支持,祝您生活愉快!

Best Regards，
DJI大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>
