### ISSUE TITLE
关于M600 和M600 pro

### ISSUE THREAD

**Issue by kimberz-git** [dji-sdk/Onboard-SDK#784]
您好，
   请问一下，最近一直在着手基于M600的Onboard-SDK的开发， 可是在官方却发现显示缺货或者不在大陆销售了，
我看了下官方关于支持Onboard-SDK的机型的说明，只有M300 RTK， M600系列，M210系列，M100系列，N3/A3 飞控，
应该没有其他机型了把？ （如果还有，请帮忙指正）

可是M210, M100, M600 都在官网显示缺货或不在大陆销售，请问，目前是只是缺货后续还会可以买得到，还是说就直接以后停产，不再卖了？

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/48700'>Zendesk ticket #48700</a>:<br><br>尊敬的开发者，

您好！感谢您联系DJI大疆创新。

是的，OSDK支持的机型为您所列出的类型，以开发者官网上列出的支持机型为准。关于特定机型的销售具体信息，建议您可以直接咨询DJI store在线客服，或产品售后support@dji.com

感谢您的理解与支持,祝您生活愉快!

Best Regards，
DJI大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>
