### ISSUE TITLE
订阅获取的无人机电量与sample获取的不一致

### ISSUE THREAD

**Issue by github4529** [dji-sdk/Onboard-SDK#786]
订阅battery_info
uint32_t&nbsp;capacity
int32_t&nbsp;voltage
int32_t&nbsp;current
uint8_t&nbsp;percentage

获取数值为 6347，46920mV，1403mA，8(疑为ASCII 56)
而djiosdk-battery-sample获取的数值为
电池1-56%，46V，34°
电池2-56%，46V，34°

电压值大致一致，capacity 6347和56%差别有点大，
把8当成ASCII转成10进制是56和56%倒是一致

那么capacity 是什么单位呢

**Comment by github4529** [comment]
获取battery示例中，BatteryWholeInfo的数据全为空

**Comment by dji-kyle** [comment]
#787
