### ISSUE TITLE
无人机电池状态

### ISSUE THREAD

**Issue by github4529** [dji-sdk/Onboard-SDK#787]
订阅battery_info
uint32_t&nbsp;capacity
int32_t&nbsp;voltage
int32_t&nbsp;current
uint8_t&nbsp;percentage

获取数值为 6347，46920mV，1403mA，8(疑为ASCII 56)
而djiosdk-battery-sample获取的数值为
电池1-56%，46V，34°
电池2-56%，46V，34°

电压值大致一致，capacity 6347和56%差别有点大，
把8当成ASCII转成10进制是56和56%倒是一致

那么capacity 是什么单位呢

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/48809'>Zendesk ticket #48809</a>:<br><br>尊敬的开发者，

您好！感谢您联系DJI大疆创新。

M300仅支持获取单块电池。可通过此API获取，
 ![](https://djisdksupport.zendesk.com/attachments/token/qBJG1UhRm6CILLa7PfP6tGM3Y/?name=inline1160810683.png)
获取值定义和单位：
 ![](https://djisdksupport.zendesk.com/attachments/token/E481FcYgnJIpwHdLMOghFNe69/?name=inline1308525955.png)​​

感谢您的理解与支持,祝您生活愉快!

Best Regards，
DJI大疆创新SDK技术支持<br><a href='https://djisdksupport.zendesk.com/attachments/token/qBJG1UhRm6CILLa7PfP6tGM3Y' target='zd_attach'>inline1160810683.png</a><br><a href='https://djisdksupport.zendesk.com/attachments/token/E481FcYgnJIpwHdLMOghFNe69' target='zd_attach'>inline1308525955.png</a>
<br><p><em><small>°°°</small></em></p>
