### ISSUE TITLE
sample/core/waypoint_v2_sample.cpp 中函数命名错误

### ISSUE THREAD

**Issue by MisterYan** [dji-sdk/Onboard-SDK#789]
sample/core/waypoint_v2_sample.hpp 
82行：
`ErrorCode::ErrorCodeType uploadWapointActions(int timeout);`  ------------->`ErrorCode::ErrorCodeType uploadWaypointActions(int timeout);`

sample/core/waypoint_v2_sample.cpp 
334行：
`ErrorCode::ErrorCodeType WaypointV2MissionSample::uploadWapointActions(int timeout)` ----------------->`ErrorCode::ErrorCodeType WaypointV2MissionSample::uploadWaypointActions(int timeout)`

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/48884'>Zendesk ticket #48884</a>:<br><br>尊敬的开发者，

您好！感谢您联系DJI大疆创新。

感谢您的反馈，您提到的问题是命名规范问题，这个我们将提交review代码。因这部分命名再应用端sample部分，开发者也可以根据自己的习惯进行修改和命名。

感谢您的理解与支持,祝您生活愉快!

Best Regards，
DJI大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>
