### ISSUE TITLE
关于避障系统

### ISSUE THREAD

**Issue by github4529** [dji-sdk/Onboard-SDK#790]
OSDK中关于FlightController
有CollinsionAvoidance和upwardsAvoidance的enable相关的set和get，
我使用的是M300的无人机，遥控器中有感知避障设置 <水平设置，上方设置，下方设置等>
两个似乎并不相关？
我用FlightController进行set和get，好像只与自己有关，遥控器上开启关闭避障系统似乎与这里获取的enable/disable无关，两者没有交互

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/48886'>Zendesk ticket #48886</a>:<br><br>尊敬的开发者，

您好！感谢您联系DJI大疆创新。

是的，当前版本OSDK与遥控器的避障开关未同步，此问题将在后续版本中同步，您可以继续关注OSDK及飞机固件的发布及功能更新动态。

感谢您的理解与支持,祝您生活愉快!

Best Regards，
DJI大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>
