### ISSUE TITLE
Ubuntu16.04

### ISSUE THREAD

**Issue by TianFengChuYi** [dji-sdk/Onboard-SDK#794]
Hi:
I have spend a lot of time for building OSDK4.1 on Ubuntu16.04 as instruction. But met with the following problem which make me crazy. Can someone help on that?
1. Ubuntu 16.04
2. gcc 15.0
3. OSDK4.1
![image](https://user-images.githubusercontent.com/20918949/122640126-4ae3a380-d130-11eb-961a-99f2181f00c8.png)

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/49175'>Zendesk ticket #49175</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

The OSDK linker lib is used for 64-bit ubuntu on the X86 platform. The error message shows that your ubuntu should be 32-bit. It is recommended to replace the 64-bit ubuntu system for testing

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
<br><p><em><small>°°°</small></em></p>
