### ISSUE TITLE
Commanding M210v2 to fly at lower height

### ISSUE THREAD

**Issue by archielee** [dji-sdk/Onboard-SDK#798]
On our previous M210 RTK, we were able to use advanced flight control (`Control::flightCtrl(CtrlData data)`) in SDK v3.8.1 to control the drone. We used it to do tasks at low heights.

Using the new M210 RTK v2 and SDK v4.0.1, we found that commanding the drone to fly lower than 0.7 m will not do anything. The drone stays at 0.7 m altitude. Is there a way to avoid this problem?

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/49539'>Zendesk ticket #49539</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

When the downward vision obstacle avoidance function is turned on, there will be 0.7m protection, you can try to turn off the downward vision function, and use the VERTICAL_THRUST mode in the vertical control.

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
<br><p><em><small>°°°</small></em></p>

**Comment by archielee** [comment]
When doing this, do we have to use VERTICAL_THRUST? Is VERTICAL_POSITION no longer available?

**Comment by archielee** [comment]
Confirmed that I can disable it from the DJI Pilot app and still perform vertical position control. Closing this issue, thanks!
