### ISSUE TITLE
什么时候可以支持禅思L1的雷达数据呢？

### ISSUE THREAD

**Issue by shirley033** [dji-sdk/Onboard-SDK#799]

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/49681'>Zendesk ticket #49681</a>:<br><br>尊敬的开发者，

您好！感谢您联系DJI大疆创新。

抱歉，当前OSDK暂无支持L1的计划。

感谢您的理解与支持,祝您生活愉快!

Best Regards，
DJI大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>
