### ISSUE TITLE
OSDK能否控制纯红外与 红外变焦分屏

### ISSUE THREAD

**Issue by github4529** [dji-sdk/Onboard-SDK#803]
使用API changeH264source可以切换相机的图传模式，
OSDK定义了DEF、广角、变焦、红外四种模式

在红外模式中，遥控器设定为分屏或者不分屏，都是同一种OSDK_CAMERA_SOURCE_H20T_IR，能否不通过遥控器，使用OSDK切换红外模式中是否分屏

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/49978'>Zendesk ticket #49978</a>:<br><br>尊敬的开发者，

您好！感谢您联系DJI大疆创新。

当前OSDK不支持对红外镜头设置是否分屏，需要通过遥控器界面设置。若您有需要通过OSDK设置红外分屏，建议您可通过以下连接提交需求单，我们将提交评估。

链接：
https://djisdksupport.zendesk.com/hc/zh-cn/requests/new

为了更好的对您的需求进行评估和适配，建议提交信息包括以下内容：
 1.公司背景，
 2.项目描述，
 3.使用到该需求的描述
 4.个人背景介绍

感谢您的理解与支持,祝您生活愉快!

Best Regards，
DJI大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>
