### ISSUE TITLE
Allow specifying path to UserConfig.txt

### ISSUE THREAD

**Issue by chukcha2** [dji-sdk/Onboard-SDK#81]
osdk-wrapper's ReadUserConfig.cpp hard codes user configuration file name as "UserConfig.txt" and hardcodes the file's path to current directory. It would be useful for application developers who leverage osdk-wrapper library to be able to specify path of the user configuration file.

**Comment by lanyusea** [comment]
shoot me a pull request

**Comment by chukcha2** [comment]
Here it is: https://github.com/dji-sdk/Onboard-SDK/pull/82

**Comment by rohitsantdji** [comment]
Thanks! Merged.
