### ISSUE TITLE
OSDK能否控制遥控器开关机

### ISSUE THREAD

**Issue by github4529** [dji-sdk/Onboard-SDK#813]
M300

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/50540'>Zendesk ticket #50540</a>:<br><br>尊敬的开发者，

您好！感谢您联系DJI大疆创新。

OSDK不可以控制遥控器开关机。

感谢您的理解与支持,祝您生活愉快!

Best Regards，
DJI大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>
