### ISSUE TITLE
dji_log.hpp 中的#define DLOG定义与glog 中的DLOG冲突。

### ISSUE THREAD

**Issue by MisterYan** [dji-sdk/Onboard-SDK#814]
在项目中使用glog后，OSDK的dji_log.hpp 文件中的#define DLOG 宏定义与glog中的DLOG冲突。

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/50710'>Zendesk ticket #50710</a>:<br><br>尊敬的开发者，

您好！感谢您联系DJI大疆创新。

可以根据代码应用修改一下代码或者编译环境。

感谢您的理解与支持,祝您生活愉快!

Best Regards，
DJI大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>
