### ISSUE TITLE
stm32f407 linker problem

### ISSUE THREAD

**Issue by askariz** [dji-sdk/Onboard-SDK#815]
`arm-none-eabi-gcc "../Core/Src/sysmem.c" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -c -I../USB_HOST/App -I"/Users/askariz/STM32CubeIDE/workspace_1.5.1/dji_sdk1/Core/osdk-hal/utils" -I"/Users/askariz/STM32CubeIDE/workspace_1.5.1/dji_sdk1/Core/osdk-core/linker/STM32/inc" -I"/Users/askariz/STM32CubeIDE/workspace_1.5.1/dji_sdk1/Core/osdk-core/api/inc" -I"/Users/askariz/STM32CubeIDE/workspace_1.5.1/dji_sdk1/Core/osdk-core/logger/inc" -I"/Users/askariz/STM32CubeIDE/workspace_1.5.1/dji_sdk1/Core/osdk-core/platform/inc" -I"/Users/askariz/STM32CubeIDE/workspace_1.5.1/dji_sdk1/Core/osdk-core/utility/inc" -I"/Users/askariz/STM32CubeIDE/workspace_1.5.1/dji_sdk1/Core/osdk-core/api/inc" -I../USB_HOST/Target -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/sysmem.d" -MT"Core/Src/sysmem.o" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "Core/Src/sysmem.o"
arm-none-eabi-gcc "../Core/Src/system_stm32f4xx.c" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32F407xx -c -I../USB_HOST/App -I"/Users/askariz/STM32CubeIDE/workspace_1.5.1/dji_sdk1/Core/osdk-hal/utils" -I"/Users/askariz/STM32CubeIDE/workspace_1.5.1/dji_sdk1/Core/osdk-core/linker/STM32/inc" -I"/Users/askariz/STM32CubeIDE/workspace_1.5.1/dji_sdk1/Core/osdk-core/api/inc" -I"/Users/askariz/STM32CubeIDE/workspace_1.5.1/dji_sdk1/Core/osdk-core/logger/inc" -I"/Users/askariz/STM32CubeIDE/workspace_1.5.1/dji_sdk1/Core/osdk-core/platform/inc" -I"/Users/askariz/STM32CubeIDE/workspace_1.5.1/dji_sdk1/Core/osdk-core/utility/inc" -I"/Users/askariz/STM32CubeIDE/workspace_1.5.1/dji_sdk1/Core/osdk-core/api/inc" -I../USB_HOST/Target -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/system_stm32f4xx.d" -MT"Core/Src/system_stm32f4xx.o" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "Core/Src/system_stm32f4xx.o"
arm-none-eabi-g++ -o "dji_sdk1.elf" @"objects.list"   -mcpu=cortex-m4 -T"/Users/askariz/STM32CubeIDE/workspace_1.5.1/dji_sdk1/STM32F407VGTX_FLASH.ld" --specs=nosys.specs -Wl,-Map="dji_sdk1.map" -Wl,--gc-sections -static /Users/askariz/STM32CubeIDE/workspace_1.5.1/dji_sdk1/Core/osdk-core/linker/STM32/lib/sdk-linker.lib --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -Wl,--start-group -lc -lm -lstdc++ -lsupc++ -Wl,--end-group
collect2: fatal error: ld terminated with signal 11 [Segmentation fault: 11]
compilation terminated.
/Applications/STM32CubeIDE.app/Contents/Eclipse/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.7-2018-q2-update.macos64_1.5.0.202011040924/tools/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/bin/ld: warning: /Users/askariz/STM32CubeIDE/workspace_1.5.1/dji_sdk1/Core/osdk-core/linker/STM32/lib/sdk-linker.lib(osdk_md5.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use of wchar_t values across objects may fail
/Applications/STM32CubeIDE.app/Contents/Eclipse/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.7-2018-q2-update.macos64_1.5.0.202011040924/tools/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/bin/ld: warning: /Users/askariz/STM32CubeIDE/workspace_1.5.1/dji_sdk1/Core/osdk-core/linker/STM32/lib/sdk-linker.lib(osdk_hal.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use of wchar_t values across objects may fail
/Applications/STM32CubeIDE.app/Contents/Eclipse/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.7-2018-q2-update.macos64_1.5.0.202011040924/tools/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/bin/ld: warning: /Users/askariz/STM32CubeIDE/workspace_1.5.1/dji_sdk1/Core/osdk-core/linker/STM32/lib/sdk-linker.lib(osdk_osal.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use of wchar_t values across objects may fail
/Applications/STM32CubeIDE.app/Contents/Eclipse/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.7-2018-q2-update.macos64_1.5.0.202011040924/tools/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/bin/ld: warning: /Users/askariz/STM32CubeIDE/workspace_1.5.1/dji_sdk1/Core/osdk-core/linker/STM32/lib/sdk-linker.lib(osdk_logger.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use of wchar_t values across objects may fail
/Applications/STM32CubeIDE.app/Contents/Eclipse/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.7-2018-q2-update.macos64_1.5.0.202011040924/tools/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/bin/ld: warning: /Users/askariz/STM32CubeIDE/workspace_1.5.1/dji_sdk1/Core/osdk-core/linker/STM32/lib/sdk-linker.lib(dji_internal_command.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use of wchar_t values across objects may fail
/Applications/STM32CubeIDE.app/Contents/Eclipse/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.7-2018-q2-update.macos64_1.5.0.202011040924/tools/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/bin/ld: warning: /Users/askariz/STM32CubeIDE/workspace_1.5.1/dji_sdk1/Core/osdk-core/linker/STM32/lib/sdk-linker.lib(dji_linker.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use of wchar_t values across objects may fail
/Applications/STM32CubeIDE.app/Contents/Eclipse/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.7-2018-q2-update.macos64_1.5.0.202011040924/tools/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/bin/ld: warning: /Users/askariz/STM32CubeIDE/workspace_1.5.1/dji_sdk1/Core/osdk-core/linker/STM32/lib/sdk-linker.lib(osdk_root_task.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use of wchar_t values across objects may fail
/Applications/STM32CubeIDE.app/Contents/Eclipse/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.7-2018-q2-update.macos64_1.5.0.202011040924/tools/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/bin/ld: warning: /Users/askariz/STM32CubeIDE/workspace_1.5.1/dji_sdk1/Core/osdk-core/linker/STM32/lib/sdk-linker.lib(osdk_command.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use of wchar_t values across objects may fail
/Applications/STM32CubeIDE.app/Contents/Eclipse/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.7-2018-q2-update.macos64_1.5.0.202011040924/tools/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/bin/ld: warning: /Users/askariz/STM32CubeIDE/workspace_1.5.1/dji_sdk1/Core/osdk-core/linker/STM32/lib/sdk-linker.lib(osdk_channel.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use of wchar_t values across objects may fail
/Applications/STM32CubeIDE.app/Contents/Eclipse/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.7-2018-q2-update.macos64_1.5.0.202011040924/tools/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/bin/ld: warning: /Users/askariz/STM32CubeIDE/workspace_1.5.1/dji_sdk1/Core/osdk-core/linker/STM32/lib/sdk-linker.lib(osdk_list.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use of wchar_t values across objects may fail
/Applications/STM32CubeIDE.app/Contents/Eclipse/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.7-2018-q2-update.macos64_1.5.0.202011040924/tools/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/bin/ld: warning: /Users/askariz/STM32CubeIDE/workspace_1.5.1/dji_sdk1/Core/osdk-core/linker/STM32/lib/sdk-linker.lib(osdk_msgq.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use of wchar_t values across objects may fail
/Applications/STM32CubeIDE.app/Contents/Eclipse/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.7-2018-q2-update.macos64_1.5.0.202011040924/tools/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/bin/ld: warning: /Users/askariz/STM32CubeIDE/workspace_1.5.1/dji_sdk1/Core/osdk-core/linker/STM32/lib/sdk-linker.lib(osdk_work.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use of wchar_t values across objects may fail
/Applications/STM32CubeIDE.app/Contents/Eclipse/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.7-2018-q2-update.macos64_1.5.0.202011040924/tools/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/bin/ld: warning: /Users/askariz/STM32CubeIDE/workspace_1.5.1/dji_sdk1/Core/osdk-core/linker/STM32/lib/sdk-linker.lib(osdk_protocol.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use of wchar_t values across objects may fail
/Applications/STM32CubeIDE.app/Contents/Eclipse/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.7-2018-q2-update.macos64_1.5.0.202011040924/tools/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/bin/ld: warning: /Users/askariz/STM32CubeIDE/workspace_1.5.1/dji_sdk1/Core/osdk-core/linker/STM32/lib/sdk-linker.lib(osdk_protocol_sdk.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use of wchar_t values across objects may fail
/Applications/STM32CubeIDE.app/Contents/Eclipse/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.7-2018-q2-update.macos64_1.5.0.202011040924/tools/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/bin/ld: warning: /Users/askariz/STM32CubeIDE/workspace_1.5.1/dji_sdk1/Core/osdk-core/linker/STM32/lib/sdk-linker.lib(osdk_protocol_v1.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use of wchar_t values across objects may fail
/Applications/STM32CubeIDE.app/Contents/Eclipse/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.7-2018-q2-update.macos64_1.5.0.202011040924/tools/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/bin/ld: warning: /Users/askariz/STM32CubeIDE/workspace_1.5.1/dji_sdk1/Core/osdk-core/linker/STM32/lib/sdk-linker.lib(dji_aes.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use of wchar_t values across objects may fail
/Applications/STM32CubeIDE.app/Contents/Eclipse/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.7-2018-q2-update.macos64_1.5.0.202011040924/tools/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/bin/ld: warning: /Users/askariz/STM32CubeIDE/workspace_1.5.1/dji_sdk1/Core/osdk-core/linker/STM32/lib/sdk-linker.lib(osdk_crc.o) uses 2-byte wchar_t yet the output is to use 4-byte wchar_t; use of wchar_t values across objects may fail
make: *** [makefile:91: dji_sdk1.elf] Error 1
"make -j3 all" terminated with exit code 2. Build might be incomplete.
`

Is it cause by no enough RAM of STM32F407VGT or other problem?

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/50740'>Zendesk ticket #50740</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

It is recommended that you use Keil MDK 5.22 (armcc 5.06) and above to compile OSDK (STM32), and use STM32F4xx_DFP.2.13.0

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
<br><p><em><small>°°°</small></em></p>
