### ISSUE TITLE
stm32f4 discovery uart2 output wrong code 

### ISSUE THREAD

**Issue by askariz** [dji-sdk/Onboard-SDK#816]
![image](https://user-images.githubusercontent.com/39890252/127726293-d8e398ca-dd18-460d-b0c4-bb376312a429.png)

as you can see , whatever I change baudrate to 9600/115200/230400 is the same result .

**Comment by askariz** [comment]
![image](https://user-images.githubusercontent.com/39890252/127726394-2263fe9f-a15d-4797-ab37-38d227e1b438.png)

**Comment by askariz** [comment]
![image](https://user-images.githubusercontent.com/39890252/127726522-c5040349-c2d2-49a4-bea1-064b614ef6d4.png)


also uncheck RTS and DTR

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/51089'>Zendesk ticket #51089</a>:<br><br>尊敬的开发者，

您好！感谢您联系DJI大疆创新。

界面显示像是显示格式不对，建议看看是不是有设置显示格式，将分包显示勾选去掉试试看。

感谢您的理解与支持,祝您生活愉快!

Best Regards，
DJI大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>
