### ISSUE TITLE
控制飞行

### ISSUE THREAD

**Issue by JunGenius** [dji-sdk/Onboard-SDK#825]
你好，咨询两个问题
1.当我使用Joystick来控制飞行时，水平方向设置 HORIZONTAL_POSITION，坐标系设置 HORIZONTAL_BODY， x 是代表速度还是位置 ？比如说我向前飞行10m, x是否应该给10 ? 

2.我垂直方向设置VERTICAL_POSITION，坐标系设置 HORIZONTAL_BODY ，当我设置z =5 时，无人机会自动上升到5m处悬停，但当我水平方向设置时，无人机会一直向前飞., 请帮助分析下如何解决 ？ 非常感谢。

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/53780'>Zendesk ticket #53780</a>:<br><br>尊敬的开发者，

您好！感谢您联系DJI大疆创新。

首先关于OSDK joystick功能，因为考虑到OSDK的控制安全，OSDK需要以一定的频率实时发送控制指令给飞控，当以位置模式控制时，实时发送的位置参数就会存在差异。所以传给飞控的参数不是实际的位置偏移，位置偏移实际上是在OSDK端实时获取GPS位置并计算偏移后完成的闭环控制功能。这部分可以参考sample代码：moveByPositionOffset的实现，也可以参考论坛相关帖：
https://djisdksupport.zendesk.com/hc/zh-cn/articles/900006773463-OSDK-%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81%E8%A7%A3%E6%9E%90-%E9%A3%9E%E8%A1%8C%E6%8E%A7%E5%88%B6

1.当我使用Joystick来控制飞行时，水平方向设置 HORIZONTAL_POSITION，坐标系设置 HORIZONTAL_BODY， x 是代表速度还是位置 ？比如说我向前飞行10m, x是否应该给10 ?

-->当水平方向设置 HORIZONTAL_POSITION，函数positionAndYawCtrl中x参数实际可以看做是一个移动标志，为0不移动。


2.我垂直方向设置VERTICAL_POSITION，坐标系设置 HORIZONTAL_BODY ，当我设置z =5 时，无人机会自动上升到5m处悬停，但当我水平方向设置时，无人机会一直向前飞., 请帮助分析下如何解决 ？
      -->垂直方向设置VERTICAL_POSITION，参数z是相对起飞点高度，水平设置参考上述回答。可以参考demo中实时计算位置偏移，判断达到目标位置后参数给0，即在应用端完成（水平）位置控制闭环。

感谢您的理解与支持,祝您生活愉快!

Best Regards，
DJI大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>
