### ISSUE TITLE
There are multiple compilation warnings

### ISSUE THREAD

**Issue by chukcha2** [dji-sdk/Onboard-SDK#83]
Should we try to get rid of all compilation warnings? This should be mostly done by fixing code and in rare cases by adding a compiler flag to ignore a specific warning.
And then to prevent new warnings from being introduced, should we add -Wall and -Werror compiler flags?
Here are an example of a warning that should be fixed in code:

[-Wunused-variable]:

> Onboard-SDK/osdk-wrapper/src/ReadUserConfig.cpp:46:7: warning: unused variable ‘id’ [-Wunused-variable]

and [-Wreturn-type]:

> Onboard-SDK/sample/Linux/Non-Blocking/../../../platform/linux/inc/LinuxSerialDevice.h:55:71: warning: no return statement in function returning non-void [-Wreturn-type]
>      int serialRead(unsigned char *buf, int len) {_serialRead(buf,len);}

**Comment by lanyusea** [comment]
really appreciate if you can shoot me a pr
