### ISSUE TITLE
Vehicle initialization crashes when unclean subscription state

### ISSUE THREAD

**Issue by benbarkay** [dji-sdk/Onboard-SDK#868]
**Scenario:**
Initialization of an OSDK vehicle instance in an arm64 JVM environment with a drone (M300 in this case) that is already transmitting subscription data of packages from a previous session -- i.e. has "left over packages".

**Expected:**
The initialization process will remove the left-over packages and continue.

**Actual:**
The initialization process produces a segmentation fault and crashes.

The fault occurs at `SubscriptionPackage::packageRemoveSuccessHandler`:

```java
  // Step 1. Clear fields in TopicDataBase
  for (size_t i = 0; i < info.numberOfTopics; ++i) // <---- here
  {
```

The cause of the fault is that `info.numberOfTopics` has not been initialized to 0, and so when the allocated memory is dirty, sometimes produces a value greater than `Telemetry::TOTAL_TOPIC_NUMBER` (61), which results in a segmentation fault.

I was not able to reproduce this with the sample code, but it happens every odd run in our bigger app running in a JVM context.
Making a program to reproduce this is not so simple because it requires making the environment hand over a dirty page when SubscriptionPackage is initialized.

Thankfully, the solution is simple. We need to replace this:
```java
SubscriptionPackage::SubscriptionPackage()
  : occupied(false)
  , leftOverDataFlag(false)
  , incomingDataBuffer(NULL)
  , packageDataSize(0)
{
  userUnpackHandler.callback = NULL;
  userUnpackHandler.userData = NULL;
}
```

with this:
```java
SubscriptionPackage::SubscriptionPackage()
  : occupied(false)
  , leftOverDataFlag(false)
  , incomingDataBuffer(NULL)
  , packageDataSize(0)
{
  cleanUpPackage();
}
```

**Comment by benbarkay** [comment]
Created pull-request #869

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/60300'>Zendesk ticket #60300</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

Thanks for your feedback, we will further confirm this issue again.

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
<br><p><em><small>°°°</small></em></p>

**Comment by benbarkay** [comment]
You could try to reproduce this but I think this is one of those things that you don't really have to.

One can clearly see that `info.numberOfTopics` is being read without being initialized, and that the code expects it to be 0.
This is clearly a bug, as you rely on the whim of chance that the bytes of `numberOfTopics` that you received when invoking `new` happen to be 0 (which, they are not guaranteed to be).
Initializing `info.numberOfTopics` to 0 involves no risk or any additional complexity, and doesn't make the implementation any less elegant.

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/60300'>Zendesk ticket #60300</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

We have merged your PR into master, thank you for your feedback.

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
<br><p><em><small>°°°</small></em></p>
