### ISSUE TITLE
~/build/bin files not present after cmake on Raspberry pi 3

### ISSUE THREAD

**Issue by wellsa1** [dji-sdk/Onboard-SDK#89]
I cloned the "Raspberrypi-support" branch and ran cmake .. from ./build.  No errors were present but no files are in the ./build/bin folder as the documentation suggests.  raspberry pi 3 Jessie.

**Comment by rohitsantdji** [comment]
Did you run the `make` command after running cmake?

**Comment by rohitsantdji** [comment]
Please re-open this issue if you still face this issue after running `make`.
