### ISSUE TITLE
Using External Odometry

### ISSUE THREAD

**Issue by huseyintutan** [dji-sdk/Onboard-SDK#906]
Hi, Im trying to inject an external odometry source to DJI M600 with A3 Pro flight controller. I cant use GPS odometry because of an obligation so I want to use another odometry like Lidar, Visual etc. Is there any solution for this situtation in Onboard-SDK?

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/75697'>Zendesk ticket #75697</a>:<br><br>It does not support the input of external sensor data to the flight controller. You can develop positioning with your own odometry on the onboard computer, and just control the movement of the drone through the OSDK joystick attitude control mode.
<br><p><em><small>°°°</small></em></p>
