### ISSUE TITLE
A3 - OnboardSDK version mismatch.

### ISSUE THREAD

**Issue by SodanKerjuu** [dji-sdk/Onboard-SDK#91]
Latest A3 firmware doesn't recognize latest OnboardSDK version.
Tested both with fresh installs + factory settings.

"Your SDK version does not match the one reported by the drone."

I tried all version possibilities to the UserConfig.txt, most logical one being "VersionA3_32"

**Comment by rohitsantdji** [comment]
Duplicate of #88
