### ISSUE TITLE
Waypoint Mission Status Information

### ISSUE THREAD

**Issue by a2hill** [dji-sdk/Onboard-SDK#93]
I can't seem to find documentation on the status values returned during the execution of a waypoint mission. [This comment](https://github.com/dji-sdk/Onboard-SDK/blob/f4453c094a1c212bd4d2b95326a232684413c9ae/osdk-core/src/DJI_App.cpp#L223l) makes me think such documentation might not exist. 
  
Until someone get's around to writing said documentation do the return values follow the same order as the ones in the [mobile SDK](https://developer.dji.com/iframe/mobile-sdk-doc/android/reference/dji/sdk/missionmanager/DJIWaypointMission.DJIWaypointMissionExecutionState.html)?

Also can someone explain the difference between when we would use `setWayPointCallback` vs `setWayPointEventCallback`?

**Comment by lanyusea** [comment]
1. The document:

   https://developer.dji.com/onboard-sdk/documentation/introduction/ground-station-protocol.html


2. I think you can be clear about the differences after checking the code here:
https://github.com/dji-sdk/Onboard-SDK/blob/f4453c094a1c212bd4d2b95326a232684413c9ae/osdk-core/src/DJI_App.cpp#L172

``` c
switch ack_type:
   case mission_callback: 
      if you `setMisssionCallback` before
         do your own callback
      else we provide our own callback
         switch mission_type:
            case waypoint:
               if you `setWayPointCallback` before
                  do your own callback
               else
                   a simple printf 
               endif
            case hotpoint:
               if you `setHotPointCallback` before
                  do your own callback
               else
                   a simple printf 
               endif
            case follow:
               if you `setFollowPointCallback` before
                  do your own callback
               else
                   a simple printf 
               endif
            case IOC:
               if you `setIOCPointCallback` before
                  do your own callback
               else
                   a simple printf 
               endif
          endswitch
      endif

   case waypoint_event_callback:
      if you `setFollowPointCallback` before
         do your own callback
      else
         a simple printf 
      endif

endswitch
