### ISSUE TITLE
Questions on Tracking Module

### ISSUE THREAD

**Issue by Daniel-xsy** [dji-sdk/Onboard-SDK#932]
Hi,

May I have two questions:

1. I'm wondering if the Onboard-SDK can only be applied to Matrice series, which means I can't develop new features on other drones (e.g., the newest Mini 4 Pro).
2. I noticed the demo here: https://developer.dji.com/cn/onboard-sdk/documentation/sample-doc/advanced-sensing-target-tracking.html shows target tracking sample with only the gimbal rotated. I'm wondering if it's possible to build ActiveTrack using the SDK to send the tracking results to the control loop. If so, then can we implement a customized tracking algorithm in ActiveTrack?

Thanks so much.

**Comment by dji-dev** [comment]
Agent comment from xiaorong.zheng in <a href='https://djisdksupport.zendesk.com/agent/tickets/96416'>Zendesk ticket #96416</a>:<br><br>1. The Mini 4 Pro does not support Onboard-SDK and cannot be implemented. I apologize for any inconvenience this may cause.
2. Do you mean controlling the movement of the drone? This can also be achieved through Onboard-SDK.
<br><p><em><small>°°°</small></em></p>

**Comment by Daniel-xsy** [comment]
Thanks for your reply.

For the second question, I mean can we implement ActiveTrack using the Onboard-SDK, which uses vision tracking to follow a target.

**Comment by Daniel-xsy** [comment]
Also, is anyway to get the tracking results (e.g., `(x, y, w, h)`) of the ActiveTrack deployed on products? Thanks

**Comment by dji-dev** [comment]
Agent comment from xiaorong.zheng in <a href='https://djisdksupport.zendesk.com/agent/tickets/96416'>Zendesk ticket #96416</a>:<br><br>I apologize for the inconvenience. Onboard-SDK can only obtain visual information. If you need to implement the ActiveTrack function, you need to develop and implement it.
<br><p><em><small>°°°</small></em></p>
