### ISSUE TITLE
Unable to takeoff ! Strange Issue

### ISSUE THREAD

**Issue by ersien** [dji-sdk/Onboard-SDK#933]
Hi, as you see in this image, i used sdk and built an apk. 
Now i am trying to connect it.
It gives error : "Unable to takeoff" 
Another strange message : "Remote controller not connected/still approving connection situation."

I do not understand, if it is not connected, how do I see camera stream and turn camera right left up down ?

Another thing is ; whenever I run the app , I see an android notification like "Another 
Analyzing head dump"

![WhatsApp Image 2024-02-28 at 15 07 26](https://github.com/dji-sdk/Onboard-SDK/assets/2394112/b2043c6f-2445-40d5-8e11-fb689e6a4f37)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/101640'>Zendesk ticket #101640</a>:<br><br>This is an issue with the MOBILE SDK, and we will follow up on your problem at https://github.com/dji-sdk/Mobile-SDK-Android-V5/issues/277.

Thank you.
<br><p><em><small>°°°</small></em></p>
