### ISSUE TITLE
Waypoint Mission Crashing DJI GO app

### ISSUE THREAD

**Issue by natelannan-osu** [dji-sdk/Onboard-SDK#94]
I logged an issue to DJI as well since I suspect the problem is in the android DJI Go app.  I will update here as I hear back from support.  Running a Waypoint mission that ran successfully using previous SDK version is now crashing android DJI Go app.  The aircraft continues to run mission after app has crashed.

M600 FW - 1.0.0.80
android DJI GO version - 3.1.2
OSDK version -  3.2.1 with M600 patch

ios app 3.1.4 does not crash

**Comment by natelannan-osu** [comment]
DJI dev support got back to me.  This is a known issue they are actively working on.

**Comment by chukcha2** [comment]
why close it if it is not fixed yet or without referencing another issue that tracks it?
